-- Batch 3 Chunk 7
-- Batch 3
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-2ec04c21', 'XL Data FlexMax 6 GB 28 Hari', 'Data', 'XL', 2790000, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-63c3e73a', 'XL Xtra Combo Flex S+ 28 Hari', 'Data', 'XL', 2812500, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex S+","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-36a088ec', 'XL Data Bebas Puas 6rb/hr - 5 Hari', 'Data', 'XL', 2830400, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8c35b95f', 'XL Xtra Kuota Vidio 5 GB & Vidio Platinum F1 30 hari', 'Data', 'XL', 2839100, true, '{"type":"Xtra Kuota Vidio","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e15554ec', 'XL Data Games 6 GB 30 Hari', 'Data', 'XL', 2843200, true, '{"type":"Games","description":"DRP MAIN 3GB+GAMES 3GB 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-80eadc35', 'XL Data Bebas Puas 5.5 GB 11 Hari', 'Data', 'XL', 2852500, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-df8ab7e9', 'XL Data Bebas Puas 4.25 GB 17 Hari', 'Data', 'XL', 2872500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fbc05c31', 'XL Data Paket Harian XL 7 Hari', 'Data', 'XL', 2897500, true, '{"type":"Harian","description":"Paket Harian XL, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6061146c', 'XL Data Grab Gacor 6.5 GB 30 Hari', 'Data', 'XL', 2935000, true, '{"type":"Grab Gacor","description":"Paket Grab Gacor 6.5GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ed92bed7', 'XL Data Bebas Puas 12.6 GB 7 Hari', 'Data', 'XL', 2960000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4ed10293', 'XL Xtra Combo Special 8 GB 30 Hari', 'Data', 'XL', 3016500, true, '{"type":"Xtra Combo","description":"Xtra Combo Special 8GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f489507e', 'XL Data Bebas Puas 4.5 GB 18 Hari', 'Data', 'XL', 3022500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2d79fe5c', 'XL Data Bebas Puas 6 GB 12 Hari', 'Data', 'XL', 3090000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e592f48b', 'XL Data Bebas Puas 4.75 GB 19 Hari', 'Data', 'XL', 3142500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c72a62f5', 'XL Data Games 8 GB 30 Hari', 'Data', 'XL', 3160000, true, '{"type":"Games","description":"DRP MAIN+GAMES 8GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-aced449b', 'XL Data Flex S 28 Hari', 'Data', 'XL', 3171000, true, '{"type":"Xtra Combo Flex","description":"Flex S, 28hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f7fbd153', 'XL Data FlexMax 7 GB 28 Hari', 'Data', 'XL', 3183900, true, '{"type":"FlexMax","description":"7 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9c316bd2', 'XL Data Flex 7 GB 28 Hari', 'Data', 'XL', 3188800, true, '{"type":"Flex","description":"7 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f88eb22a', 'XL Data Bebas Puas 5 GB 20 Hari', 'Data', 'XL', 3262500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-31a38e19', 'XL Data FlexMax 10 GB 28 Hari', 'Data', 'XL', 3302500, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6a6524b3', 'XL Data Bebas Puas 6.5 GB 13 Hari', 'Data', 'XL', 3350000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f7405303', 'XL Data Bebas Puas 14.4 GB 8 Hari', 'Data', 'XL', 3420000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-116fef6e', 'XL Data Kuota Apps & Games 6 GB 30 Hari', 'Data', 'XL', 3450500, true, '{"type":"Apps Games","description":"Quota Apps & Games 6GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f7e15008', 'XL Xtra Combo Plus 5 GB 30 Hari', 'Data', 'XL', 3500000, true, '{"type":"Xtra Combo Plus","description":"Xtra Combo Plus 5GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-23bad4ec', 'XL Xtra Combo Plus 3 GB 30 Hari', 'Data', 'XL', 3500000, true, '{"type":"Xtra Combo Plus","description":"Xtra Combo Plus 3GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ebab8023', 'XL Data Bebas Puas 5.25 GB 21 Hari', 'Data', 'XL', 3500000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-78b36187', 'XL Data Flex Mini 40 GB 7 Hari', 'Data', 'XL', 3532500, true, '{"type":"Flex Mini","description":"40 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-20f02c31', 'XL Xtra Combo Flex M 28 Hari', 'Data', 'XL', 3550000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex M","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4eccf8d5', 'XL Data Flex Mini 15 GB 14 Hari', 'Data', 'XL', 3585300, true, '{"type":"Flex Mini","description":"15 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fb7da435', 'XL Data Bebas Puas 7 GB 14 Hari', 'Data', 'XL', 3610000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a44948b3', 'XL Data Bebas Puas 5.5 GB 22 Hari', 'Data', 'XL', 3670000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6c22c13e', 'XL Data Bebas Puas 7.5 GB 15 Hari', 'Data', 'XL', 3732500, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1f5c2f2d', 'XL Data Bebas Puas 16.2 GB 9 Hari', 'Data', 'XL', 3830000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-313ef359', 'XL Data Bebas Puas 5.75 GB 23 Hari', 'Data', 'XL', 3860000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-81bea787', 'XL Data Bebas Puas 6rb/hr - 7 Hari', 'Data', 'XL', 3962000, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-5fc52e07', 'XL Data Games 10 GB 30 Hari', 'Data', 'XL', 4002000, true, '{"type":"Games","description":"DRP MAIN+GAMES 10GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1144d703', 'XL Data Bebas Puas 6 GB 24 Hari', 'Data', 'XL', 4030000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2c355085', 'XL Data Bebas Puas 6.25 GB 25 Hari', 'Data', 'XL', 4160000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-67cfde13', 'XL Xtra Combo Special 14 GB 30 Hari', 'Data', 'XL', 4161100, true, '{"type":"Xtra Combo","description":"Xtra Combo Special 14GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9bf3d5f8', 'XL Data FlexMax 15 GB 28 Hari', 'Data', 'XL', 4185700, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ee2a0032', 'XL Data Bebas Puas 8 GB 16 Hari', 'Data', 'XL', 4210100, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3b8a8cd1', 'XL Data Bebas Puas 18 GB 10 Hari', 'Data', 'XL', 4230000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3fac8a2d', 'XL Data Flex Mini 75 GB 7 Hari', 'Data', 'XL', 4285500, true, '{"type":"Flex Mini","description":"75 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-06448e9d', 'XL Xtra Combo Flex M+ 28 Hari', 'Data', 'XL', 4350000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex M+","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a2efe6fe', 'XL Data Bebas Puas 6.5 GB 26 Hari', 'Data', 'XL', 4350000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-73c4c45b', 'XL Data Akrab S', 'Data', 'XL', 4402500, true, '{"type":"Paket Akrab","description":"Paket Akrab S, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0d7eadf3', 'XL Data Bebas Puas 8.5 GB 17 Hari', 'Data', 'XL', 4447500, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-51935863', 'XL Data Flex 13 GB 28 Hari', 'Data', 'XL', 4450000, true, '{"type":"Flex","description":"13 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d6c4c6f8', 'XL Data FlexMax 16 GB 28 Hari', 'Data', 'XL', 4450000, true, '{"type":"FlexMax","description":"16 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ce65ad85', 'XL Data Flex Mini 30 GB 14 Hari', 'Data', 'XL', 4479500, true, '{"type":"Flex Mini","description":"30 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
