-- Batch 5 Chunk 7
-- Batch 5
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-tri-caaf668e', 'Tri Data Mini 1.5 GB 7 Hari', 'Data', 'TRI', 860000, true, '{"type":"Mini","description":"1.5 GB Nasional, 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-89349eea', 'Tri Data Happy 6 GB 2 Hari', 'Data', 'TRI', 891000, true, '{"type":"Happy","description":"6 gb utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6569880a', 'Tri Data Happy 7 GB 2 Hari', 'Data', 'TRI', 900000, true, '{"type":"Happy","description":"7 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-57d17b8a', 'Tri Data Happy Kikida 5 GB 2 Hari', 'Data', 'TRI', 900500, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5877f0a3', 'Tri Data 1.5 GB Lokal / 7 Hari', 'Data', 'TRI', 901000, true, '{"type":"Lokal","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e78d65eb', 'Tri Data Happy 5 GB 1 Hari (Jawa Tengah)', 'Data', 'TRI', 913500, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c1fcde30', 'Tri Data Happy 3 GB 2 Hari (Jawa Tengah)', 'Data', 'TRI', 914000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-0a1e2c04', 'Tri Data Happy 4 GB 3 Hari', 'Data', 'TRI', 917500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-aaa8c245', '300 MB (semua jaringan) Mengikuti Masa Aktif Kartu', 'Data', 'TRI', 930500, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b761f83e', 'Tri Data Happy 1.5 GB 7 Hari (Jawa Tengah)', 'Data', 'TRI', 945000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1e4b456a', 'Tri Data KeepOn 5GB + Viu Premium 3 Hari', 'Data', 'TRI', 987700, true, '{"type":"KeepOn","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6284e271', 'Tri Data KeepOn 5GB + Genflix 3 Hari', 'Data', 'TRI', 987900, true, '{"type":"KeepOn","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-59817865', 'Tri Data Happy 3.5 GB 3 Hari', 'Data', 'TRI', 996000, true, '{"type":"Happy","description":"3.5 gb utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c89202ad', 'Tri Data Happy 2 GB 5 Hari', 'Data', 'TRI', 1003500, true, '{"type":"Happy","description":"Tri Data Happy 2 GB / 5 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b202bad5', 'Tri Data Mini 2 GB 5 Hari', 'Data', 'TRI', 1015900, true, '{"type":"Mini","description":"Tri Data Mini 2 GB / 5 Hari, nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4d4fe091', 'Tri Data 2 GB 30 Hari', 'Data', 'TRI', 1050000, true, '{"type":"Pure 30 Hari","description":"Tri Data 2 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7e8c4119', 'Tri Data Happy 3 GB 3 Hari (Jawa Tengah)', 'Data', 'TRI', 1051000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-86dad504', 'Tri Data H3RO UL1 + Voucher MLBB', 'Data', 'TRI', 1100000, true, '{"type":"H3RO","description":"Kuota Reguler 1 GB, kuota games unlimited FUP 512 MB per hari, voucher games 12 diamond MLBB, masa aktif 7 Hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7cb8ba17', 'Tri Data 2 GB 7 Hari', 'Data', 'TRI', 1121000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8a662ec7', 'Tri Data 2 GB 14 Hari', 'Data', 'TRI', 1123000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9509f881', 'Tri Data 1.5 GB Nasional + 500 MB Lokal / 30 Hari', 'Data', 'TRI', 1127500, true, '{"type":"Lokal","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8f494e67', 'Tri Mix Small 2.75 GB 3 Hari', 'Data', 'TRI', 1128000, true, '{"type":"Mix","description":"0.75 GB (semua jaringan) + 2 GB (jaringan 4G) , Masa Aktif 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-637ae933', 'Tri Data Happy 3.5 GB 5 Hari (Jawa Tengah)', 'Data', 'TRI', 1151000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-008f1cc0', 'Tri Data Happy Play Movies 3 GB 3 Hari', 'Data', 'TRI', 1154500, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1640e86d', 'Tri Data Happy Play Games 3 GB 3 Hari', 'Data', 'TRI', 1154500, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-d3898b6f', 'Tri Data Happy 3 GB 3 Hari (Jawa Barat)', 'Data', 'TRI', 1169900, true, '{"type":"Jawa Barat","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-a5edb46a', 'Tri Data Happy Kikida 3 GB 3 Hari', 'Data', 'TRI', 1175000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9d3ca882', '500 MB (semua jaringan) + 1 GB (Youtube + Netflix) 3Hari', 'Data', 'TRI', 1180500, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-72322d15', 'Tri Data Happy 6 GB 3 Hari', 'Data', 'TRI', 1185000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-288ce0e3', 'Tri Data Happy 5 GB 3 Hari', 'Data', 'TRI', 1207500, true, '{"type":"Happy","description":"Tri Data Happy 5 GB / 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b8c8fcdc', 'Tri Data Happy 8 GB 3 Hari', 'Data', 'TRI', 1210000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ec471ac4', 'Tri Data Happy 2.5 GB 28 Hari', 'Data', 'TRI', 1232500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-70ccd1dd', 'Tri Data Happy 5 GB 3 Hari (Jawa Barat)', 'Data', 'TRI', 1237500, true, '{"type":"Jawa Barat","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f2ddee7e', 'Tri Data Happy 3 GB 28 Hari', 'Data', 'TRI', 1272500, true, '{"type":"Happy","description":"Tri Data Happy 3 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5327b803', 'Tri Data Addon 6 GB 3 Hari', 'Data', 'TRI', 1275000, true, '{"type":"Addon","description":"1 GB 24 jam, 5 GB (01.00-09.00), 3 hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-96d5be63', 'Tri Mix Small 3 GB 3 Hari', 'Data', 'TRI', 1300000, true, '{"type":"Mix","description":"3 GB semua jaringan 24 jam, Masa Aktif 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ca28b413', 'Tri Data 2 GB Nasional + 1 GB Lokal / 30 Hari', 'Data', 'TRI', 1322000, true, '{"type":"Lokal","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-54555498', 'Tri Data Happy Kikida 6 GB 3 Hari', 'Data', 'TRI', 1325000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1640215a', 'Tri Data Happy 3.5 GB 5 Hari', 'Data', 'TRI', 1327500, true, '{"type":"Happy","description":"Tri Data Happy 3.5 GB / 5 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4729df8c', 'Tri Data Happy 4.5 GB 5 Hari', 'Data', 'TRI', 1337500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5c646264', 'Tri Data Happy 5 GB 5 Hari', 'Data', 'TRI', 1360000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9140d23e', 'Tri Data Happy 5 GB 3 Hari (Jawa Tengah)', 'Data', 'TRI', 1371000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-feb9d12a', 'Tri Data Happy 6 GB 5 Hari', 'Data', 'TRI', 1372500, true, '{"type":"Happy","description":"Tri Data Happy 6 GB / 5 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-0a7cab49', 'Tri Data 2.5 GB 14 Hari', 'Data', 'TRI', 1401000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-11d9d12e', 'Tri Data 2.5 GB 30 Hari', 'Data', 'TRI', 1406000, true, '{"type":"Pure 30 Hari","description":"Tri Data 2.5 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ceae94bd', 'Tri Data Mini 3 GB 7 Hari', 'Data', 'TRI', 1437200, true, '{"type":"Mini","description":"Tri Data Mini 3 GB / 7 Hari, nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8a923f9a', 'Tri Data Happy 3 GB 7 Hari', 'Data', 'TRI', 1442500, true, '{"type":"Happy","description":"Tri Data Happy 3 GB / 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e3821abb', 'Tri Data Happy 7 GB 5 Hari', 'Data', 'TRI', 1457500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9a24150b', 'Tri Data AlwaysOn 2.5 GB', 'Data', 'TRI', 1469500, true, '{"type":"AlwaysOn","description":"2.5 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-74b23a5e', 'Tri Data 3 GB 30 Hari', 'Data', 'TRI', 1486200, true, '{"type":"Pure 30 Hari","description":"Tri Data 3 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
