-- Batch 19 Chunk 6
-- Batch 19
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-7dc0f5bf', 'Telkomsel 166.000', 'Pulsa', 'TELKOMSEL', 16391700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c0a7e134', 'Telkomsel 167.000', 'Pulsa', 'TELKOMSEL', 16490400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c2189394', 'Telkomsel 168.000', 'Pulsa', 'TELKOMSEL', 16589100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-642e0ed9', 'Telkomsel 169.000', 'Pulsa', 'TELKOMSEL', 16687800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-dc650e69', 'Telkomsel 170.000', 'Pulsa', 'TELKOMSEL', 16786500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6625440c', 'Telkomsel 171.000', 'Pulsa', 'TELKOMSEL', 16885200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a9e8de1b', 'Telkomsel 172.000', 'Pulsa', 'TELKOMSEL', 16983900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-dfc70a34', 'Telkomsel 173.000', 'Pulsa', 'TELKOMSEL', 17082600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-dd95dd59', 'Telkomsel 174.000', 'Pulsa', 'TELKOMSEL', 17181300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-dcc41469', 'Telkomsel 175.000', 'Pulsa', 'TELKOMSEL', 17280000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f51739ee', 'Telkomsel 176.000', 'Pulsa', 'TELKOMSEL', 17378700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-88830626', 'Telkomsel 177.000', 'Pulsa', 'TELKOMSEL', 17477400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-08c1fb41', 'Telkomsel 178.000', 'Pulsa', 'TELKOMSEL', 17576100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4f9c233e', 'Telkomsel 179.000', 'Pulsa', 'TELKOMSEL', 17674800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d83a2d26', 'Telkomsel 180.000', 'Pulsa', 'TELKOMSEL', 17773500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f88e3579', 'Telkomsel 181.000', 'Pulsa', 'TELKOMSEL', 17872200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1b9563ee', 'Telkomsel 182.000', 'Pulsa', 'TELKOMSEL', 17970900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a416c0df', 'Telkomsel 183.000', 'Pulsa', 'TELKOMSEL', 18069600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-02a7bc02', 'Telkomsel 184.000', 'Pulsa', 'TELKOMSEL', 18168300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-14eed154', 'Telkomsel 185.000', 'Pulsa', 'TELKOMSEL', 18267000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-554fd5f6', 'Telkomsel 186.000', 'Pulsa', 'TELKOMSEL', 18365700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-38044f62', 'Telkomsel 187.000', 'Pulsa', 'TELKOMSEL', 18464400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d109b297', 'Telkomsel 188.000', 'Pulsa', 'TELKOMSEL', 18563100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-547e9c28', 'Telkomsel 189.000', 'Pulsa', 'TELKOMSEL', 18661800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0c24c120', 'Telkomsel 190.000', 'Pulsa', 'TELKOMSEL', 18758000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fa74f1e1', 'Telkomsel 191.000', 'Pulsa', 'TELKOMSEL', 18859200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-17cfb3e5', 'Telkomsel 192.000', 'Pulsa', 'TELKOMSEL', 18957900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1afed007', 'Telkomsel 193.000', 'Pulsa', 'TELKOMSEL', 19056600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-80d39452', 'Telkomsel 194.000', 'Pulsa', 'TELKOMSEL', 19155300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9dcfb597', 'Telkomsel 195.000', 'Pulsa', 'TELKOMSEL', 19254000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c13a61fa', 'Telkomsel 200.000', 'Pulsa', 'TELKOMSEL', 19312500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4a26f8cd', 'Telkomsel 196.000', 'Pulsa', 'TELKOMSEL', 19352700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-bb481d10', 'Telkomsel 197.000', 'Pulsa', 'TELKOMSEL', 19451400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-90784f3b', 'Telkomsel 198.000', 'Pulsa', 'TELKOMSEL', 19550100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8f4e7b99', 'Telkomsel 199.000', 'Pulsa', 'TELKOMSEL', 19648800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0a3c0841', 'Telkomsel 205.000', 'Pulsa', 'TELKOMSEL', 20241000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8e0fbf0f', 'Telkomsel 210.000', 'Pulsa', 'TELKOMSEL', 20734500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c36ea139', 'Telkomsel 215.000', 'Pulsa', 'TELKOMSEL', 21228000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b1a19507', 'Telkomsel 220.000', 'Pulsa', 'TELKOMSEL', 21721500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b184ca0a', 'Telkomsel 225.000', 'Pulsa', 'TELKOMSEL', 22215000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-62cde792', 'Telkomsel 230.000', 'Pulsa', 'TELKOMSEL', 22708500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-cec87836', 'Telkomsel 235.000', 'Pulsa', 'TELKOMSEL', 23202000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a338148f', 'Telkomsel 240.000', 'Pulsa', 'TELKOMSEL', 23695500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1938e684', 'Telkomsel 245.000', 'Pulsa', 'TELKOMSEL', 24189000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e5e46e79', 'Telkomsel 246.000', 'Pulsa', 'TELKOMSEL', 24287700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3970d08a', 'Telkomsel 247.000', 'Pulsa', 'TELKOMSEL', 24386400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b64b4d28', 'Telkomsel 248.000', 'Pulsa', 'TELKOMSEL', 24485100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a926167a', 'Telkomsel 249.000', 'Pulsa', 'TELKOMSEL', 24583800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e2246bd1', 'Telkomsel 250.000', 'Pulsa', 'TELKOMSEL', 24695000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-32efede6', 'Telkomsel 251.000', 'Pulsa', 'TELKOMSEL', 24781200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
