-- Batch 3 Chunk 5
-- Batch 3
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-97a2dc81', 'XL Data 4 GB 30 Hari', 'Data', 'XL', 1200000, true, '{"type":"Umum","description":"DRP DATA 4 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9eeeb8d7', 'XL Data Bebas Puas 6rb/hr - 2 Hari', 'Data', 'XL', 1211000, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a0d438b2', 'XL Xtra Kuota Vidio 5 GB & Vidio Platinum Mobile 30 hari', 'Data', 'XL', 1243500, true, '{"type":"Xtra Kuota Vidio","description":"Xtra Kuota Vidio 5GB & Vidio Platinum Mobile 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3d48621b', 'XL Data Paket Harian XS 10 Hari', 'Data', 'XL', 1250000, true, '{"type":"Harian","description":"Paket Harian XS, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-83a4b318', 'XL Data Bebas Puas 2.5 GB 5 Hari', 'Data', 'XL', 1250000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0f61869a', 'XL Data 1.5 GB 30 Hari', 'Data', 'XL', 1262500, true, '{"type":"Umum","description":"XL Data 1.5 GB 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-84b084df', 'XL Data Paket Harian M 5 Hari', 'Data', 'XL', 1287500, true, '{"type":"Harian","description":"Paket Harian M, 5hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3e155245', 'XL Data Flex Mini 12 GB 2 Hari', 'Data', 'XL', 1300000, true, '{"type":"Flex Mini","description":"12 GB Nasional 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a6d68140', 'XL XTRA ON 1GB', 'Data', 'XL', 1302300, true, '{"type":"Xtra On","description":"XTRA ON 1GB","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-92dbb208', 'XL Data Flex Mini 6 GB 3 Hari', 'Data', 'XL', 1305000, true, '{"type":"Flex Mini","description":"6 GB Nasional 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e412f5f1', 'XL Data Bebas Puas 5.4 GB 3 Hari', 'Data', 'XL', 1310000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a29a329f', 'XL Data Bebas Puas 2 GB 8 Hari', 'Data', 'XL', 1330000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-343ffb59', 'XL Xtra Combo Mini 2 GB 3 Hari', 'Data', 'XL', 1350500, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 2GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-674dbf2e', 'XL Data Games 3 GB 30 Hari', 'Data', 'XL', 1350500, true, '{"type":"Games","description":"DRP MAIN+GAMES 3GB 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-29c6420e', 'XL Data Mini 2.5 GB 7 Hari', 'Data', 'XL', 1370000, true, '{"type":"Mini","description":"2,5GB FULL 24 JAM NASIONAL, 7 HARI","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ae121d30', 'XL Data Kuota Apps & Games 2.5 GB 30 Hari', 'Data', 'XL', 1380500, true, '{"type":"Apps Games","description":"Quota Apps & Games 2,5GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ebc73210', 'XL Xtra Combo Mini 2.5 GB 7 Hari', 'Data', 'XL', 1383000, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 2.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1b93f3dc', 'XL Data Bonus Harian 6 GB 1 Hari', 'Data', 'XL', 1400000, true, '{"type":"Bonus Harian","description":"6 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ac361614', 'XL Data Bonus Harian 6 GB 2 Hari', 'Data', 'XL', 1400000, true, '{"type":"Bonus Harian","description":"6 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-23c241b6', 'XL XTRA Hotrod Special 2 GB 7 Hari - West', 'Data', 'XL', 1400000, true, '{"type":"West","description":"Xtra Hotrod Special 2GB, 7hr - West","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-11fcef01', 'XL Data 5 GB 30 Hari', 'Data', 'XL', 1402500, true, '{"type":"Umum","description":"DRP DATA 5 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b39ec7b1', 'XL XTRA Hotrod Special M 7 Hari', 'Data', 'XL', 1421000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special M, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-384d1678', 'XL Data Paket Harian S 7 Hari', 'Data', 'XL', 1425000, true, '{"type":"Harian","description":"Paket Harian S, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0917e298', 'XL XTRA Hotrod Special 2.5 GB / 7 Hari', 'Data', 'XL', 1429000, true, '{"type":"Hotrod Special","description":"1.5 GB nasional + 1 GB Youtube (00:00 - 12:00), berlaku 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e7d6a7b8', 'XL Xtra Combo Mini Gift 2.5 GB 7 Hari', 'Data', 'XL', 1430000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini Gift 2.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-beb2102c', 'XL Data Paket Harian L 5 Hari', 'Data', 'XL', 1437500, true, '{"type":"Harian","description":"Paket Harian L, 5hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2aec7fbc', 'XL XTRA Hotrod Special 3 GB 7 Hari', 'Data', 'XL', 1438800, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 3GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a1b6e174', 'XL Data Flex Mini 4 GB 7 Hari', 'Data', 'XL', 1448400, true, '{"type":"Flex Mini","description":"4 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a7ffac72', 'XL XTRA HotRod Special 3 GB 10 Hari', 'Data', 'XL', 1449000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 3GB, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-19f83742', 'XL HOTROD 3 GB 5 Hari', 'Data', 'XL', 1456000, true, '{"type":"Hotrod","description":"HotRod Baru 3GB, 5hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9122364a', 'XL Data Paket Harian S 10 Hari', 'Data', 'XL', 1495000, true, '{"type":"Harian","description":"Paket Harian S, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-86e8cb7f', 'XL Data Mini 4 GB 7 Hari', 'Data', 'XL', 1495000, true, '{"type":"Mini","description":"4GB FULL 24 JAM NASIONAL, 7 HARI","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4d58e81f', 'XL Data Bonus Harian 7 GB 1 Hari', 'Data', 'XL', 1500000, true, '{"type":"Bonus Harian","description":"7 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f33f22a6', 'XL Data Bonus Harian 7 GB 2 Hari', 'Data', 'XL', 1500000, true, '{"type":"Bonus Harian","description":"7 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a6aa5071', 'XL Data Bebas Puas 2.25 GB 9 Hari', 'Data', 'XL', 1500000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2b38ac5f', 'XL XTRA ON 2GB', 'Data', 'XL', 1501000, true, '{"type":"Xtra On","description":"XTRA ON 2GB","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c36c313c', 'XL Data Bebas Puas 3 GB 6 Hari', 'Data', 'XL', 1537500, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-5bda99f0', 'XL Data Bonus Harian 8 GB 1 Hari', 'Data', 'XL', 1600000, true, '{"type":"Bonus Harian","description":"8 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d9353aa7', 'XL HOTROD 3 GB 7 Hari', 'Data', 'XL', 1620000, true, '{"type":"Hotrod","description":"Hotrod 3GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a767a596', 'XL XTRA HotRod Special 4 GB 10 Hari', 'Data', 'XL', 1653000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 4GB, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-59f35cf4', 'XL Data Bebas Puas 2.5 GB 10 Hari', 'Data', 'XL', 1680000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-15f5aa31', 'XL Data Bebas Puas 6rb/hr - 3 Hari', 'Data', 'XL', 1698400, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-06db12a4', 'XL Data Bonus Harian 8 GB 2 Hari', 'Data', 'XL', 1700000, true, '{"type":"Bonus Harian","description":"8 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-12f5ab3e', 'XL Xtra Kuota Vidio 5 GB & Vidio Platinum Big Screen 30 hari', 'Data', 'XL', 1742500, true, '{"type":"Xtra Kuota Vidio","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-62a3ecc8', 'XL Data Grab Gacor 4 GB 7 Hari', 'Data', 'XL', 1743500, true, '{"type":"Grab Gacor","description":"Paket Grab Gacor 4GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9023105d', 'XL Data Bebas Puas 3.5 GB 7 Hari', 'Data', 'XL', 1750000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-61f2e0e3', 'XL Data Kuota Apps & Games 3.5 GB 30 Hari', 'Data', 'XL', 1751000, true, '{"type":"Apps Games","description":"Quota Apps & Games 3,5GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-92137698', 'XL Data Bebas Puas 7.2 GB 4 Hari', 'Data', 'XL', 1770000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-cc745979', 'XL Data Flex Mini 6 GB 7 Hari', 'Data', 'XL', 1785000, true, '{"type":"Flex Mini","description":"6 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3c172373', 'XL Xtra Combo Mini 4 GB 7 Hari', 'Data', 'XL', 1790000, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 4GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
