-- Batch 3 Chunk 3
-- Batch 3
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-54d0a8d5', 'XL Xtra Kuota Vidio 250 MB & Vidio Platinum Mobile 1 hari', 'Data', 'XL', 160500, true, '{"type":"Xtra Kuota Vidio","description":"Xtra Kuota Vidio 250MB & Vidio Platinum Mobile 1hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-51458fb4', 'XL Data 200 MB 30 Hari', 'Data', 'XL', 160500, true, '{"type":"Umum","description":"DRP DATA 200MB Utama 30Hri, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-781dbae2', 'XL Data Bebas Puas 250 MB 1 Hari', 'Data', 'XL', 185000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-31dfe12a', 'XL Xtra Conference 2 GB 1 Hari', 'Data', 'XL', 194700, true, '{"type":"Conference","description":"Xtra Conference 2GB, 1hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-73d1cb8e', 'XL Xtra Edukasi 5 GB 3 Hari', 'Data', 'XL', 252000, true, '{"type":"Edukasi","description":"Xtra Edukasi 5GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7608ebd7', 'XL Data Bebas Puas 500 MB 1 Hari', 'Data', 'XL', 278800, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a57a290f', 'XL Xtra Conference 5 GB 3 Hari', 'Data', 'XL', 299000, true, '{"type":"Conference","description":"Xtra Conference 5GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ea3b0e4d', 'XL Data 500 MB 30 Hari', 'Data', 'XL', 315500, true, '{"type":"Umum","description":"DRP DATA 500 MB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-31149186', 'XL HOTROD 120 MB 7 Hari', 'Data', 'XL', 350000, true, '{"type":"Hotrod","description":"HotRod 120MB 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-40348cbf', 'XL Data Bebas Puas 500 MB 2 Hari', 'Data', 'XL', 355500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b067b22b', 'XL HOTROD 500 MB 7 Hari', 'Data', 'XL', 388500, true, '{"type":"Hotrod","description":"HotRod 500MB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0d5a61b6', 'XL HOTROD 1 GB 2 Hari', 'Data', 'XL', 430500, true, '{"type":"Hotrod","description":"HOTROD 1GB, 2hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6c14de57', 'XL Data Bebas Puas 1.8 GB 1 Hari', 'Data', 'XL', 436300, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-de292cb0', 'XL Data Pure Games 1 GB 30 Hari', 'Data', 'XL', 445500, true, '{"type":"Games","description":"DRP GAMES 1GB 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a4f00616', 'XL Data Blue 1 GB 2 Hari', 'Data', 'XL', 452000, true, '{"type":"Blue","description":"Paket Blue 1GB, 2hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3a7e17fc', 'XL Data Games 1 GB 30 Hari', 'Data', 'XL', 467500, true, '{"type":"Games","description":"DRP MAIN+GAMES 1GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-357ad686', 'XL Data Bonus Harian 1 GB 2 Hari', 'Data', 'XL', 498000, true, '{"type":"Bonus Harian","description":"1 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-385514b6', 'XL Data Bebas Puas 750 MB 3 Hari', 'Data', 'XL', 520000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-81ed2ac1', 'XL Data Bebas Puas 1 GB 2 Hari', 'Data', 'XL', 520000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-426d9ad4', 'XL Data 800 MB 30 Hari', 'Data', 'XL', 535000, true, '{"type":"Umum","description":"DRP DATA 800 MB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f0bf6f31', 'XL XTRA KUOTA 2 GB Facebook 3 Hari', 'Data', 'XL', 543600, true, '{"type":"Xtra Kuota","description":"XTRA Kuota Facebook 2GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-33800e7b', 'XL XTRA KUOTA 2 GB Instagram - 3 Hari', 'Data', 'XL', 543600, true, '{"type":"Xtra Kuota","description":"2 GB Instagram 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a0d39e65', 'XL XTRA KUOTA 2 GB Youtube 3 Hari', 'Data', 'XL', 543600, true, '{"type":"Xtra Kuota","description":"XTRA Kuota YouTube 2GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b6ead23c', 'XL XTRA KUOTA 2 GB TikTok 3 Hari', 'Data', 'XL', 543600, true, '{"type":"Xtra Kuota","description":"XTRA Kuota TikTok 2GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c5f71cd3', 'XL Data Bonus Harian 1 GB 1 Hari', 'Data', 'XL', 545500, true, '{"type":"Bonus Harian","description":"1 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b895da35', 'XL Data 700 MB 30 Hari', 'Data', 'XL', 560500, true, '{"type":"Umum","description":"DRP DATA 700MB Utama 30Hri, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-665589f7', 'XL Data Bebas Puas 6rb/hr - 1 Hari', 'Data', 'XL', 566300, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-604d54aa', 'XL Data 1 GB 30 Hari', 'Data', 'XL', 588000, true, '{"type":"Umum","description":"DRP DATA 1 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-050ffb85', 'XL Data Bonus Harian 2 GB 1 Hari', 'Data', 'XL', 600000, true, '{"type":"Bonus Harian","description":"2 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b5bb911d', 'XL Data Flex Mini 3 GB 1 Hari', 'Data', 'XL', 600000, true, '{"type":"Flex Mini","description":"3 GB Nasional 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-49bbec43', 'XL Data Blue 2 GB 2 Hari', 'Data', 'XL', 600500, true, '{"type":"Blue","description":"Paket Blue 2GB, 2hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8d93130f', 'XL HOTROD 800 MB 30 Hari', 'Data', 'XL', 626000, true, '{"type":"Hotrod","description":"HotRod 800MB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-bd121444', 'XL Data Bebas Puas 1 GB 4 Hari', 'Data', 'XL', 680000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4e81aac0', 'XL Data Bonus Harian 1 GB 3 Hari', 'Data', 'XL', 695500, true, '{"type":"Bonus Harian","description":"1 GB Nasional, 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-219c9c7f', 'XL Data Bonus Harian 2 GB 2 Hari', 'Data', 'XL', 700000, true, '{"type":"Bonus Harian","description":"2 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1bd00493', 'XL Data Bonus Harian 3 GB 1 Hari', 'Data', 'XL', 700000, true, '{"type":"Bonus Harian","description":"3 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c2473b2c', 'XL HOTROD 1 GB 7 Hari', 'Data', 'XL', 725500, true, '{"type":"Hotrod","description":"HotRod 1GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e92ead0a', 'XL Data Bonus Harian 5 GB 3 Hari', 'Data', 'XL', 745000, true, '{"type":"Bonus Harian","description":"5 GB Nasional, 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-be746ec7', 'XL Xtra Edukasi 15 GB 7 Hari', 'Data', 'XL', 752000, true, '{"type":"Edukasi","description":"Xtra Edukasi 15GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-88df7e01', 'XL Xtra Kuota Vidio 3 GB & Vidio Platinum Mobile 7 hari', 'Data', 'XL', 794300, true, '{"type":"Xtra Kuota Vidio","description":"Xtra Kuota Vidio 3GB & Vidio Platinum Mobile 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4a5d5192', 'XL Data Pure Games 2 GB 30 Hari', 'Data', 'XL', 795000, true, '{"type":"Games","description":"DRP GAMES 2GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-5bd77687', 'XL Data Bonus Harian 3 GB 2 Hari', 'Data', 'XL', 800000, true, '{"type":"Bonus Harian","description":"3 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-803cf054', 'XL Data Bebas Puas 1.5 GB 3 Hari', 'Data', 'XL', 800000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-af463adf', 'XL Data Games 2 GB 30 Hari', 'Data', 'XL', 808500, true, '{"type":"Games","description":"DRP MAIN+GAMES 2GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-85620297', 'XL Data Mini 1.5 GB 7 Hari', 'Data', 'XL', 820000, true, '{"type":"Mini","description":"1,5GB  FULL 24 JAM NASIONAL, 7 HARI","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-07e0b64d', 'XL Data Bebas Puas 1.25 GB 5 Hari', 'Data', 'XL', 830000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-987f4fe6', 'XL Data Paket Harian S 3 Hari', 'Data', 'XL', 845000, true, '{"type":"Harian","description":"Paket Harian S, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-166e97f1', 'XL Data Flex Mini 10 GB 1 Hari', 'Data', 'XL', 862500, true, '{"type":"Flex Mini","description":"10 GB Nasional 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4bd44442', 'XL Data Bonus Harian 4 GB 1 Hari', 'Data', 'XL', 890000, true, '{"type":"Bonus Harian","description":"4 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-22777516', 'XL Data Mini 1 GB 7 Hari', 'Data', 'XL', 890000, true, '{"type":"Mini","description":"1GB NASIONAL SEMUA JARINGAN, 7 HARI","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
