-- Batch 3 Chunk 8
-- Batch 3
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-ac2cebaf', 'XL Xtra Combo Weekend 5 GB + 5 GB / 30 Hari', 'Data', 'XL', 4500000, true, '{"type":"Xtra Combo Weekend","description":"5GB + 5GB (Youtube)+20Menit All 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a803a4c5', 'XL Data Bebas Puas 6.75 GB 27 Hari', 'Data', 'XL', 4530000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2769ab9b', 'XL Data FlexMax 20 GB 28 Hari', 'Data', 'XL', 4584100, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ba546d30', 'XL Xtra Combo Flex L 28 Hari', 'Data', 'XL', 4590500, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex L","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a63e57b1', 'XL Data Bebas Puas 9 GB 18 Hari', 'Data', 'XL', 4650000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4cb7e427', 'XL Data Bebas Puas 7 GB 28 Hari', 'Data', 'XL', 4680000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ce4e6afa', 'XL Data 30 GB 30 Hari', 'Data', 'XL', 4692500, true, '{"type":"Umum","description":"XL Data 30 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a8af239e', 'XL Data FlexMax 33 GB 14 Hari', 'Data', 'XL', 4705500, true, '{"type":"FlexMax","description":"33 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-be4a3e0b', 'XL Data Bebas Puas 19.8 GB 11 Hari', 'Data', 'XL', 4742500, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8efa4aae', 'XL Data Bebas Puas 7.25 GB 29 Hari', 'Data', 'XL', 4885000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-97649565', 'XL Data Bebas Puas 7.5 GB 30 Hari', 'Data', 'XL', 4892500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-dbfe69e4', 'XL Data Bebas Puas 9.5 GB 19 Hari', 'Data', 'XL', 4910000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-654f84d9', 'XL Data Grab Gacor 12 GB 30 Hari', 'Data', 'XL', 4912500, true, '{"type":"Grab Gacor","description":"Paket Grab Gacor 12GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-bbabeeed', 'XL Xtra Kuota Vidio 5 GB & Vidio Diamond Mobile 30 hari', 'Data', 'XL', 4977500, true, '{"type":"Xtra Kuota Vidio","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fe7c5675', 'XL Data Bebas Puas 10 GB 20 Hari', 'Data', 'XL', 5150000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-79a92c45', 'XL Data Bebas Puas 21.6 GB 12 Hari', 'Data', 'XL', 5172500, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e77c570c', 'XL Xtra Combo Plus Gift 10 GB 30 Hari', 'Data', 'XL', 5295000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Plus Gift 10GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e717dffb', 'XL Xtra Combo Gift 10 GB / 30 Hari', 'Data', 'XL', 5350000, true, '{"type":"Xtra Combo Gift","description":"10 GB Utama + 2 GB Aplikasi + 3 GB Lokal + 20 Menit Sesama, 30 Hari, jalur gift","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1da638fe', 'XL Data Bebas Puas 10.5 GB 21 Hari', 'Data', 'XL', 5410000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-125b00b8', 'XL Data Flex 19 GB 28 Hari', 'Data', 'XL', 5420400, true, '{"type":"Flex","description":"19 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-65fb3526', 'XL Data FlexMax 23 GB 28 Hari', 'Data', 'XL', 5423200, true, '{"type":"FlexMax","description":"23 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7c49a6bf', 'XL Data FlexMax 25 GB 28 Hari', 'Data', 'XL', 5480500, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0f6cf0c2', 'XL Data FlexMax 12 GB 28 Hari (East Kalsul)', 'Data', 'XL', 5480500, true, '{"type":"East Kalsul","description":"12 GB Utama + Lokal East Kalsul","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-34dc29ac', 'XL Data FlexMax 12 GB 28 Hari (Sumatera)', 'Data', 'XL', 5520000, true, '{"type":"Sumatera","description":"XL Data FlexMax 12 GB 28 Hari (Sumatera)","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a9c01d6a', 'XL Data Bebas Puas 23.4 GB 13 Hari', 'Data', 'XL', 5530000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8df9cf04', 'XL Xtra Combo 5 GB + 10 GB 28 Hari', 'Data', 'XL', 5550000, true, '{"type":"Xtra Combo","description":"Xtra Combo 5+10 Double Youtube","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b2996f51', 'XL Data Bebas Puas 11 GB 22 Hari', 'Data', 'XL', 5600000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-953bbcbe', 'XL Data Bebas Puas 6rb/hr - 10 Hari', 'Data', 'XL', 5602500, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f01acc9b', 'XL Xtra Combo Plus 10 GB 30 Hari', 'Data', 'XL', 5613100, true, '{"type":"Xtra Combo Plus","description":"Xtra Combo Plus 10GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4691e5c1', 'XL Data Akrab Kuota Bersama 10 GB / 30 Hari', 'Data', 'XL', 5615000, true, '{"type":"Paket Akrab","description":"cek deskripsi pada link https://www.xl.co.id/id/mobile/prabayar/paket-dan-tarif/internet/paket-akrab","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e7c2b50f', 'XL Xtra Combo VIP Gift 10 GB 30 Hari', 'Data', 'XL', 5700000, true, '{"type":"Xtra Combo VIP Gift","description":"Xtra Combo VIP Plus Gift 10GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d72c37ae', 'XL Data Bebas Puas 11.5 GB 23 Hari', 'Data', 'XL', 5930000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-70a497f2', 'XL Xtra Kuota Vidio 5 GB & Vidio Diamond Big Screen 30 hari', 'Data', 'XL', 5977000, true, '{"type":"Xtra Kuota Vidio","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4de42a03', 'XL Xtra Combo Weekend 10 GB + 10 GB / 30 Hari', 'Data', 'XL', 6000000, true, '{"type":"Xtra Combo Weekend","description":"10GB + 10GB (Youtube)+30Menit All 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6e24d528', 'XL Data Bebas Puas 25.2 GB 14 Hari', 'Data', 'XL', 6032500, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-005868dc', 'XL XTRA ON 20 GB 365 Hari', 'Data', 'XL', 6052500, true, '{"type":"Xtra On","description":"XL XTRA ON 20 GB 365 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-20fe2558', 'XL Data FlexMax 31 GB 28 Hari', 'Data', 'XL', 6092500, true, '{"type":"FlexMax","description":"31 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-27284879', 'XL Data Bebas Puas 12 GB 24 Hari', 'Data', 'XL', 6100000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-bcd4ef0d', 'XL Data Flex 26 GB 28 Hari', 'Data', 'XL', 6132500, true, '{"type":"Flex","description":"26 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-55f1ad1b', 'XL Data Bebas Puas 27 GB 15 Hari', 'Data', 'XL', 6142500, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7fa67b6b', 'XL Xtra Combo Flex L+ 28 Hari', 'Data', 'XL', 6152500, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex L+","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c4a6b7f2', 'XL Xtra Combo Flex XL 28 Hari', 'Data', 'XL', 6190000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-048ebf63', 'XL Data FlexMax 32 GB 28 Hari', 'Data', 'XL', 6282500, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b6cc40ef', 'XL Xtra Combo VIP Plus 10 GB / 30 Hari', 'Data', 'XL', 6285000, true, '{"type":"Xtra Combo VIP Plus","description":"https://www.xl.co.id/id/mobile/prabayar/paket-dan-tarif/internet/xtra-combo-plus","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4fddf372', 'XL Xtra Combo VIP 5 GB + 10 GB 30 Hari', 'Data', 'XL', 6335400, true, '{"type":"Xtra Combo","description":"Xtra Combo 5+10 VIP Double Youtube","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4ebc9778', 'XL Combo Lite L', 'Data', 'XL', 6400000, true, '{"type":"Combo Lite","description":"deskripsi produk cek di link https://www.xl.co.id/id/bantuan/produk/xtra-combo-lite","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-16a9fbe4', 'XL Data Bebas Puas 12.5 GB 25 Hari', 'Data', 'XL', 6440000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-09321e7f', 'XL Data Bebas Puas 13 GB 26 Hari', 'Data', 'XL', 6620000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-22d0fb3b', 'XL Data Flex Mini 75 GB 14 Hari', 'Data', 'XL', 6710500, true, '{"type":"Flex Mini","description":"75 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d5931b3e', 'XL Data FlexMax 75 GB 14 Hari', 'Data', 'XL', 6757900, true, '{"type":"FlexMax","description":"75 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
