-- Batch 19 Chunk 7
-- Batch 19
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-89e065c2', 'Telkomsel 252.000', 'Pulsa', 'TELKOMSEL', 24879900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-25f1de6c', 'Telkomsel 253.000', 'Pulsa', 'TELKOMSEL', 24978600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2e6166ff', 'Telkomsel 254.000', 'Pulsa', 'TELKOMSEL', 25077300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9280dccb', 'Telkomsel 255.000', 'Pulsa', 'TELKOMSEL', 25176000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ef511eff', 'Telkomsel 256.000', 'Pulsa', 'TELKOMSEL', 25274700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9806d977', 'Telkomsel 257.000', 'Pulsa', 'TELKOMSEL', 25373400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0ada436e', 'Telkomsel 258.000', 'Pulsa', 'TELKOMSEL', 25472100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a6cf9800', 'Telkomsel 259.000', 'Pulsa', 'TELKOMSEL', 25570800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6818324f', 'Telkomsel 260.000', 'Pulsa', 'TELKOMSEL', 25669500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-60bda283', 'Telkomsel 261.000', 'Pulsa', 'TELKOMSEL', 25768200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-166b2228', 'Telkomsel 262.000', 'Pulsa', 'TELKOMSEL', 25866900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b0c85077', 'Telkomsel 263.000', 'Pulsa', 'TELKOMSEL', 25965600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1df27419', 'Telkomsel 264.000', 'Pulsa', 'TELKOMSEL', 26064300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-254d6e17', 'Telkomsel 265.000', 'Pulsa', 'TELKOMSEL', 26163000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1644ceec', 'Telkomsel 266.000', 'Pulsa', 'TELKOMSEL', 26261700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2f413a58', 'Telkomsel 267.000', 'Pulsa', 'TELKOMSEL', 26360400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1d563717', 'Telkomsel 268.000', 'Pulsa', 'TELKOMSEL', 26459100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8819268b', 'Telkomsel 269.000', 'Pulsa', 'TELKOMSEL', 26557800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-471d6a80', 'Telkomsel 270.000', 'Pulsa', 'TELKOMSEL', 26656500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0c0e876d', 'Telkomsel 271.000', 'Pulsa', 'TELKOMSEL', 26755200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4008f80c', 'Telkomsel 272.000', 'Pulsa', 'TELKOMSEL', 26853900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0071cddb', 'Telkomsel 273.000', 'Pulsa', 'TELKOMSEL', 26952600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-17afc4fc', 'Telkomsel 274.000', 'Pulsa', 'TELKOMSEL', 27051300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-cd97ff01', 'Telkomsel 275.000', 'Pulsa', 'TELKOMSEL', 27162500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d0809caf', 'Telkomsel 276.000', 'Pulsa', 'TELKOMSEL', 27248700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ef7cf8c9', 'Telkomsel 277.000', 'Pulsa', 'TELKOMSEL', 27347400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-254f3545', 'Telkomsel 278.000', 'Pulsa', 'TELKOMSEL', 27446100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c11d9901', 'Telkomsel 279.000', 'Pulsa', 'TELKOMSEL', 27544800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-329a508f', 'Telkomsel 280.000', 'Pulsa', 'TELKOMSEL', 27643500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e6bbf463', 'Telkomsel 281.000', 'Pulsa', 'TELKOMSEL', 27742200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-17fc641d', 'Telkomsel 282.000', 'Pulsa', 'TELKOMSEL', 27840900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-231d08d2', 'Telkomsel 283.000', 'Pulsa', 'TELKOMSEL', 27939600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-09c33df3', 'Telkomsel 284.000', 'Pulsa', 'TELKOMSEL', 28038300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-23f783df', 'Telkomsel 285.000', 'Pulsa', 'TELKOMSEL', 28137000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3cde8f55', 'Telkomsel 286.000', 'Pulsa', 'TELKOMSEL', 28235700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-62b897c2', 'Telkomsel 287.000', 'Pulsa', 'TELKOMSEL', 28334400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2c02867a', 'Telkomsel 288.000', 'Pulsa', 'TELKOMSEL', 28433100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-70ab5d75', 'Telkomsel 289.000', 'Pulsa', 'TELKOMSEL', 28531800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2b166001', 'Telkomsel 290.000', 'Pulsa', 'TELKOMSEL', 28630500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-80e89d0f', 'Telkomsel 291.000', 'Pulsa', 'TELKOMSEL', 28729200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fee56082', 'Telkomsel 292.000', 'Pulsa', 'TELKOMSEL', 28827900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-13d655c8', 'Telkomsel 293.000', 'Pulsa', 'TELKOMSEL', 28926600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-35ffa421', 'Telkomsel 300.000', 'Pulsa', 'TELKOMSEL', 28962500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3cf04f93', 'Telkomsel 294.000', 'Pulsa', 'TELKOMSEL', 29025300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2103f2bd', 'Telkomsel 295.000', 'Pulsa', 'TELKOMSEL', 29124000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-16b48134', 'Telkomsel 296.000', 'Pulsa', 'TELKOMSEL', 29222700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8dfd1661', 'Telkomsel 297.000', 'Pulsa', 'TELKOMSEL', 29321400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9f30f674', 'Telkomsel 298.000', 'Pulsa', 'TELKOMSEL', 29420100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b93d1288', 'Telkomsel 299.000', 'Pulsa', 'TELKOMSEL', 29518800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-44d2cd19', 'Telkomsel 325.000', 'Pulsa', 'TELKOMSEL', 32220000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
