-- Batch 19 Chunk 8
-- Batch 19
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-e6b4cdaa', 'Telkomsel 350.000', 'Pulsa', 'TELKOMSEL', 34582500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5e437c23', 'Telkomsel 375.000', 'Pulsa', 'TELKOMSEL', 37200000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-195ae1a8', 'Telkomsel 400.000', 'Pulsa', 'TELKOMSEL', 39602500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c941af5c', 'Telkomsel 425.000', 'Pulsa', 'TELKOMSEL', 41992500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-56b84faa', 'Telkomsel 450.000', 'Pulsa', 'TELKOMSEL', 44462500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-38efca70', 'Telkomsel 475.000', 'Pulsa', 'TELKOMSEL', 46932500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c080a290', 'Telkomsel 500.000', 'Pulsa', 'TELKOMSEL', 49402500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-986078bf', 'Telkomsel 1.000.000', 'Pulsa', 'TELKOMSEL', 98802500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-tri-98b6edc2', 'Three 5.000', 'Pulsa', 'TRI', 449000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-fe02a25e', 'Three 10.000', 'Pulsa', 'TRI', 900000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-8d24072e', 'Three 15.000', 'Pulsa', 'TRI', 1377000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-cc6f2ab8', 'Three 20.000', 'Pulsa', 'TRI', 1810000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-21299ed0', 'Three 25.000', 'Pulsa', 'TRI', 2315000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-781e5db2', 'Three 30.000', 'Pulsa', 'TRI', 2820000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-b680f9bf', 'Three 35.000', 'Pulsa', 'TRI', 3388000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-a08826d6', 'Three 40.000', 'Pulsa', 'TRI', 3770000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-1eba4fdb', 'Three 45.000', 'Pulsa', 'TRI', 4082500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-396b6bbe', 'Three 50.000', 'Pulsa', 'TRI', 4617500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-5d16795e', 'Three 55.000', 'Pulsa', 'TRI', 4995000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-3810add1', 'Three 60.000', 'Pulsa', 'TRI', 5507500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-f48ee4fa', 'Three 65.000', 'Pulsa', 'TRI', 5865600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-a12f5bdc', 'Three 70.000', 'Pulsa', 'TRI', 6424500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-7d5fa27c', 'Three 75.000', 'Pulsa', 'TRI', 6780000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-90c3faeb', 'Three 80.000', 'Pulsa', 'TRI', 7350000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-59783a6e', 'Three 85.000', 'Pulsa', 'TRI', 7632500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-f70e9478', 'Three 90.000', 'Pulsa', 'TRI', 8480000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-d3e0e1a4', 'Three 100.000', 'Pulsa', 'TRI', 9200000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-386a8578', 'Three 95.000', 'Pulsa', 'TRI', 9239800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-16561568', 'Three 125.000', 'Pulsa', 'TRI', 11649300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-4cdd4451', 'Three 150.000', 'Pulsa', 'TRI', 13986000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-fff9f4be', 'Three 200.000', 'Pulsa', 'TRI', 18761000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-ac0c2cfa', 'Three 250.000', 'Pulsa', 'TRI', 23876000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-3ef1db24', 'Three 300.000', 'Pulsa', 'TRI', 27790000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-9571e394', 'Three 400.000', 'Pulsa', 'TRI', 38889000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-746b9c0c', 'Three 500.000', 'Pulsa', 'TRI', 46851300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-tri-7b828516', 'Three 1.000.000', 'Pulsa', 'TRI', 98000000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('pulsa-xl-70f7da87', 'Xl 5.000', 'Pulsa', 'XL', 450500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-25d09e62', 'Xl 10.000', 'Pulsa', 'XL', 930000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-10e14192', 'Xl 15.000', 'Pulsa', 'XL', 1390000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-0372e4c8', 'Xl 25.000', 'Pulsa', 'XL', 2330000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-2589dccf', 'XL 30.000', 'Pulsa', 'XL', 2850000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-121f34bd', 'XL 40.000', 'Pulsa', 'XL', 3815000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-2a42b7e3', 'Xl 50.000', 'Pulsa', 'XL', 4720000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-d489def3', 'Xl 60.000', 'Pulsa', 'XL', 5900000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-4ac2d858', 'Xl 70.000', 'Pulsa', 'XL', 6922500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-927cfd54', 'Xl 80.000', 'Pulsa', 'XL', 7900000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-d2819011', 'Xl 90.000', 'Pulsa', 'XL', 8925000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-73e160c3', 'Xl 100.000', 'Pulsa', 'XL', 9650000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-5bb5e388', 'Xl 150.000', 'Pulsa', 'XL', 14962500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('pulsa-xl-ae3e4464', 'Xl 200.000', 'Pulsa', 'XL', 19917500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
