-- Batch 3 Chunk 6
-- Batch 3
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-39b3fdd9', 'XL Xtra Combo Mini Gift 4 GB 7 Hari', 'Data', 'XL', 1800000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini Gift 4GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0f33168d', 'XL XTRA Hotrod Special L 7 Hari', 'Data', 'XL', 1800000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special L, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-732db64c', 'XL XTRA Hotrod Special 4 GB / 7 Hari', 'Data', 'XL', 1818500, true, '{"type":"Hotrod Special","description":"2 GB nasional + 2 GB Youtube (00:00 - 12:00), berlaku 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-73f071d3', 'XL Data Paket Harian M 7 Hari', 'Data', 'XL', 1822500, true, '{"type":"Harian","description":"Paket Harian M, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-82be324c', 'XL Data Mini 6 GB 7 Hari', 'Data', 'XL', 1825000, true, '{"type":"Mini","description":"6GB FULL24 JAM  NASIONAL, 7 HARI","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-be17787c', 'XL Data Flex Mini 3 GB 14 Hari', 'Data', 'XL', 1844000, true, '{"type":"Flex Mini","description":"3 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-08446070', 'XL HOTROD 1.5 GB 30 Hari', 'Data', 'XL', 1857500, true, '{"type":"Hotrod","description":"Hotrod 1.5GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-44e78438', 'XL Data Bebas Puas 2.75 GB 11 Hari', 'Data', 'XL', 1861000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-bf36a626', 'XL Data Flex Mini 20 GB 3 Hari', 'Data', 'XL', 1877000, true, '{"type":"Flex Mini","description":"20 GB Nasional 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ad32016d', 'XL Data Games 4 GB 30 Hari', 'Data', 'XL', 1890500, true, '{"type":"Games","description":"DRP MAIN+GAMES 4GB 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7819cedf', 'XL Data Paket Harian M 10 Hari', 'Data', 'XL', 1895000, true, '{"type":"Harian","description":"Paket Harian M, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fe7d11fa', 'XL XTRA Hotrod Special 4.5 GB 7 Hari', 'Data', 'XL', 1903700, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 4.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4b3a029d', 'XL Xtra Combo Flex S 14 Hari', 'Data', 'XL', 1931000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex S, 14hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e4a886a0', 'XL Xtra Combo Flex S 21 Hari', 'Data', 'XL', 1990000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex S, 21hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-53b0c73b', 'XL XTRA Hotrod Special 2.5 GB 3 Hari - East', 'Data', 'XL', 2000000, true, '{"type":"East","description":"Xtra Hotrod Special 2.5GB, 3hr - East","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-94e7eb22', 'XL Data 6 GB 30 Hari', 'Data', 'XL', 2000000, true, '{"type":"Umum","description":"DRP DATA 6 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-11d81ea6', 'XL Data 7 GB 30 Hari', 'Data', 'XL', 2000000, true, '{"type":"Umum","description":"DRP DATA 7 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2d2d6bd1', 'XL Xtra Combo Flex XS 28 Hari', 'Data', 'XL', 2001000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex Xs","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-353b7aab', 'XL Data Bebas Puas 3 GB 12 Hari', 'Data', 'XL', 2010000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-08d07e86', 'XL XTRA HotRod Special 6 GB 10 Hari', 'Data', 'XL', 2011000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 6GB, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ee2bbd92', 'XL Data Bebas Puas 4 GB 8 Hari', 'Data', 'XL', 2020000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-99311310', 'XL Combo Lite M', 'Data', 'XL', 2050000, true, '{"type":"Combo Lite","description":"Xtra Combo Lite M, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-04918dd0', 'XL Data Bebas Puas 9 GB 5 Hari', 'Data', 'XL', 2150000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ce613808', 'XL XTRA Hotrod Special XL 7 Hari', 'Data', 'XL', 2187500, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special XL, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b0cfc50a', 'XL Data 10 GB 30 Hari', 'Data', 'XL', 2192500, true, '{"type":"Umum","description":"XL Data 10 GB 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-06ada804', 'XL Data Bebas Puas 3.25 GB 13 Hari', 'Data', 'XL', 2192500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-cffd98ff', 'XL Combo Lite S', 'Data', 'XL', 2200000, true, '{"type":"Combo Lite","description":"deskripsi produk cek di link https://www.xl.co.id/id/bantuan/produk/xtra-combo-lite","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-25f37553', 'XL Data Flex Mini 6 GB 14 Hari', 'Data', 'XL', 2226000, true, '{"type":"Flex Mini","description":"6 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-837387fd', 'XL Data Grab Gacor 4.5 GB 30 Hari', 'Data', 'XL', 2236000, true, '{"type":"Grab Gacor","description":"Paket Grab Gacor 4.5GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b206669d', 'XL Data Flex Mini 10 GB 7 Hari', 'Data', 'XL', 2248500, true, '{"type":"Flex Mini","description":"10 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b7b763bc', 'XL Xtra Combo Mini 6 GB 7 Hari', 'Data', 'XL', 2250000, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 6GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3832b3d2', 'XL Data Paket Harian L 7 Hari', 'Data', 'XL', 2285000, true, '{"type":"Harian","description":"Paket Harian L, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8298cd63', 'XL Data 8 GB 30 Hari', 'Data', 'XL', 2300000, true, '{"type":"Umum","description":"DRP DATA 8 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b88c31d5', 'XL XTRA Hotrod Special 6.5 GB 7 Hari', 'Data', 'XL', 2301000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 6.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-96d4856a', 'XL Data Bebas Puas 4.5 GB 9 Hari', 'Data', 'XL', 2315000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b6f148f0', 'XL Xtra Combo Mini Gift 6 GB 7 Hari', 'Data', 'XL', 2335200, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini Gift 6GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-26b1b804', 'XL XTRA Hotrod Special 6 GB 7 Hari', 'Data', 'XL', 2341000, true, '{"type":"Hotrod Special","description":"3 GB nasional + 3 GB Youtube (00:00 - 12:00), berlaku 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c60cab88', 'XL Data Bebas Puas 3.5 GB 14 Hari', 'Data', 'XL', 2350000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fc60cfe6', 'XL Data 9 GB 30 Hari', 'Data', 'XL', 2400000, true, '{"type":"Umum","description":"XL Data 9 GB 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6bf84723', 'XL Data Bebas Puas 3.75 GB 15 Hari', 'Data', 'XL', 2442500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e30167af', 'XL Data Bebas Puas 5 GB 10 Hari', 'Data', 'XL', 2540000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e9ce486c', 'XL Data Flex Mini 8 GB 14 Hari', 'Data', 'XL', 2588000, true, '{"type":"Flex Mini","description":"8 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-72f61a4a', 'XL XTRA Hotrod Special 2 GB 7 Hari - East', 'Data', 'XL', 2600000, true, '{"type":"East","description":"Xtra Hotrod Special 2GB, 7hr - East","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b15fa8a6', 'XL Data Bebas Puas 4 GB 16 Hari', 'Data', 'XL', 2690000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f44d7b4d', 'XL Data Bebas Puas 10.8 GB 6 Hari', 'Data', 'XL', 2720000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ebdcedbd', 'XL Data Flex Mini 20 GB 7 Hari', 'Data', 'XL', 2733500, true, '{"type":"Flex Mini","description":"20 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8e22bb0c', 'XL Data Kuota Apps & Games 5 GB 30 Hari', 'Data', 'XL', 2760500, true, '{"type":"Apps Games","description":"Quota Apps & Games 5GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a49227b7', 'XL Data Flex Mini 15 GB 7 Hari', 'Data', 'XL', 2762500, true, '{"type":"Flex Mini","description":"15 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b725545a', 'XL Xtra Combo Flex S 28 Hari', 'Data', 'XL', 2780000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex S","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b3f09e8c', 'XL Xtra Combo 2 GB + 4 GB / 30 Hari', 'Data', 'XL', 2785000, true, '{"type":"Xtra Combo","description":"2GB (2G/3G/4G) + Nelp Anynet 20 mins. Youtube 24 Jam 4GB. Youtube 01:00-06:00 Tanpa kuota Unlimited.\n","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
