-- Batch 19 Chunk 2
-- Batch 19
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-smartfren-7890c57d', 'Smartfren 9.000', 'Pulsa', 'SMARTFREN', 873500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-437e0a19', 'Smartfren 10.000', 'Pulsa', 'SMARTFREN', 890000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-ebdd5ec7', 'Smartfren 11.000', 'Pulsa', 'SMARTFREN', 1068000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-bb8f84fb', 'Smartfren 12.000', 'Pulsa', 'SMARTFREN', 1176600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-7b50447b', 'Smartfren 15.000', 'Pulsa', 'SMARTFREN', 1399000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-b5530872', 'Smartfren 20.000', 'Pulsa', 'SMARTFREN', 1840000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-afe652b6', 'Smartfren 25.000', 'Pulsa', 'SMARTFREN', 2290000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-616a3348', 'Smartfren 30.000', 'Pulsa', 'SMARTFREN', 2817500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-ff195038', 'Smartfren 35.000', 'Pulsa', 'SMARTFREN', 3277500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-d48e13b8', 'Smartfren 40.000', 'Pulsa', 'SMARTFREN', 3775000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-6d8d5ccc', 'Smartfren 45.000', 'Pulsa', 'SMARTFREN', 4199000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-ce77b899', 'Smartfren 50.000', 'Pulsa', 'SMARTFREN', 4675000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-f71c1f96', 'Smartfren 55.000', 'Pulsa', 'SMARTFREN', 5160000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-3b227073', 'Smartfren 60.000', 'Pulsa', 'SMARTFREN', 5655000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-5c03981f', 'Smartfren 65.000', 'Pulsa', 'SMARTFREN', 6180000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-b316a2a3', 'Smartfren 70.000', 'Pulsa', 'SMARTFREN', 6700000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-ba1d161a', 'Smartfren 72.000', 'Pulsa', 'SMARTFREN', 7052500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-f74e2c8d', 'Smartfren 75.000', 'Pulsa', 'SMARTFREN', 7175000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-97bba043', 'Smartfren 80.000', 'Pulsa', 'SMARTFREN', 7495000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-0b50c906', 'Smartfren 85.000', 'Pulsa', 'SMARTFREN', 8090000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-bae79062', 'Smartfren 90.000', 'Pulsa', 'SMARTFREN', 8482500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-262e8904', 'Smartfren 95.000', 'Pulsa', 'SMARTFREN', 9065000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-154c284e', 'Smartfren 100.000', 'Pulsa', 'SMARTFREN', 9370000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-01e82c18', 'Smartfren 125.000', 'Pulsa', 'SMARTFREN', 12215500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-1a143455', 'Smartfren 150.000', 'Pulsa', 'SMARTFREN', 14624300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-7b52dc44', 'Smartfren 200.000', 'Pulsa', 'SMARTFREN', 19497500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-1aa9e607', 'Smartfren 300.000', 'Pulsa', 'SMARTFREN', 24722500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-7406780a', 'Smartfren 250.000', 'Pulsa', 'SMARTFREN', 24907500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-80ad0b54', 'Smartfren 400.000', 'Pulsa', 'SMARTFREN', 38853200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-70c055a7', 'Smartfren 500.000', 'Pulsa', 'SMARTFREN', 48747500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-7abb06c0', 'Smartfren 600.000', 'Pulsa', 'SMARTFREN', 58902500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-b8f45f03', 'Smartfren 700.000', 'Pulsa', 'SMARTFREN', 68782500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-4f390a45', 'Smartfren 800.000', 'Pulsa', 'SMARTFREN', 78582500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-ebe61e95', 'Smartfren 900.000', 'Pulsa', 'SMARTFREN', 88582500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-d376cbcc', 'Smartfren 1.000.000', 'Pulsa', 'SMARTFREN', 97607500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-telkomsel-8e9b76c3', 'Cek Hutang Pulsa Telkomsel', 'Pulsa', 'TELKOMSEL', 600, true, '{"type":"Cek Hutang","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0bc34c28', 'Telkomsel 2.000', 'Pulsa', 'TELKOMSEL', 210500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-cb89ebcb', 'Telkomsel 3.000', 'Pulsa', 'TELKOMSEL', 335500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5c07d745', 'Telkomsel 5.000', 'Pulsa', 'TELKOMSEL', 400000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6d86a674', 'Telkomsel 4.000', 'Pulsa', 'TELKOMSEL', 435500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-99da3943', 'Telkomsel 6.000', 'Pulsa', 'TELKOMSEL', 644000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d3613670', 'Telkomsel 7.000', 'Pulsa', 'TELKOMSEL', 750000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-72dae05c', 'Telkomsel 8.000', 'Pulsa', 'TELKOMSEL', 844000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-41dc1cbd', 'Telkomsel 10.000', 'Pulsa', 'TELKOMSEL', 844500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-77f225cb', 'Telkomsel 9.000', 'Pulsa', 'TELKOMSEL', 944000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-11801065', 'Telkomsel 11.000', 'Pulsa', 'TELKOMSEL', 1176000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8229c258', 'Telkomsel 12.000', 'Pulsa', 'TELKOMSEL', 1276000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-78ded3d0', 'Telkomsel 13.000', 'Pulsa', 'TELKOMSEL', 1376000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b32b269a', 'Telkomsel 15.000', 'Pulsa', 'TELKOMSEL', 1400000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1ae77a18', 'Telkomsel 14.000', 'Pulsa', 'TELKOMSEL', 1476000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
