-- Batch 19 Chunk 5
-- Batch 19
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-c843412b', 'Telkomsel 116.000', 'Pulsa', 'TELKOMSEL', 11456700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5d04fd93', 'Telkomsel 117.000', 'Pulsa', 'TELKOMSEL', 11555400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fdf1674f', 'Telkomsel 118.000', 'Pulsa', 'TELKOMSEL', 11654100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1e1ccbc7', 'Telkomsel 119.000', 'Pulsa', 'TELKOMSEL', 11752800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8a51ee42', 'Telkomsel 120.000', 'Pulsa', 'TELKOMSEL', 11851500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-29e6572f', 'Telkomsel 121.000', 'Pulsa', 'TELKOMSEL', 11950200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5f1f8b41', 'Telkomsel 122.000', 'Pulsa', 'TELKOMSEL', 12048900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e7b9c261', 'Telkomsel 123.000', 'Pulsa', 'TELKOMSEL', 12147600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7d0b530f', 'Telkomsel 124.000', 'Pulsa', 'TELKOMSEL', 12246300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-40e0c893', 'Telkomsel 125.000', 'Pulsa', 'TELKOMSEL', 12345000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-22bd21cd', 'Telkomsel 126.000', 'Pulsa', 'TELKOMSEL', 12443700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8c4dc319', 'Telkomsel 127.000', 'Pulsa', 'TELKOMSEL', 12542400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4aa69d73', 'Telkomsel 128.000', 'Pulsa', 'TELKOMSEL', 12641100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d6d8c4d5', 'Telkomsel 129.000', 'Pulsa', 'TELKOMSEL', 12739800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f9be86a3', 'Telkomsel 130.000', 'Pulsa', 'TELKOMSEL', 12838500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a9fa6bb5', 'Telkomsel 131.000', 'Pulsa', 'TELKOMSEL', 12937200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-160c1565', 'Telkomsel 132.000', 'Pulsa', 'TELKOMSEL', 13035900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-46e52a94', 'Telkomsel 133.000', 'Pulsa', 'TELKOMSEL', 13134600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7d5df007', 'Telkomsel 134.000', 'Pulsa', 'TELKOMSEL', 13233300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-72698a65', 'Telkomsel 135.000', 'Pulsa', 'TELKOMSEL', 13332000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-11399d58', 'Telkomsel 136.000', 'Pulsa', 'TELKOMSEL', 13430700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2594e70e', 'Telkomsel 137.000', 'Pulsa', 'TELKOMSEL', 13529400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6fc3414b', 'Telkomsel 138.000', 'Pulsa', 'TELKOMSEL', 13628100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-48eb842f', 'Telkomsel 139.000', 'Pulsa', 'TELKOMSEL', 13726800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5727ddab', 'Telkomsel 140.000', 'Pulsa', 'TELKOMSEL', 13825500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8d589760', 'Telkomsel 141.000', 'Pulsa', 'TELKOMSEL', 13924200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7fcc1794', 'Telkomsel 142.000', 'Pulsa', 'TELKOMSEL', 14022900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9c14dae4', 'Telkomsel 143.000', 'Pulsa', 'TELKOMSEL', 14121600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e26014bf', 'Telkomsel 144.000', 'Pulsa', 'TELKOMSEL', 14220300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-29cf5683', 'Telkomsel 145.000', 'Pulsa', 'TELKOMSEL', 14319000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ef70c268', 'Telkomsel 146.000', 'Pulsa', 'TELKOMSEL', 14417700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-51a58d2f', 'Telkomsel 150.000', 'Pulsa', 'TELKOMSEL', 14482500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fcc42066', 'Telkomsel 147.000', 'Pulsa', 'TELKOMSEL', 14516400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b5b0aa79', 'Telkomsel 148.000', 'Pulsa', 'TELKOMSEL', 14615100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f8ce584c', 'Telkomsel 149.000', 'Pulsa', 'TELKOMSEL', 14713800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d67755c5', 'Telkomsel 151.000', 'Pulsa', 'TELKOMSEL', 14911200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9c0c2271', 'Telkomsel 152.000', 'Pulsa', 'TELKOMSEL', 15009900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-548a5d1c', 'Telkomsel 153.000', 'Pulsa', 'TELKOMSEL', 15108600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-cc8a4446', 'Telkomsel 154.000', 'Pulsa', 'TELKOMSEL', 15207300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4c288433', 'Telkomsel 155.000', 'Pulsa', 'TELKOMSEL', 15306000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fea9c7bc', 'Telkomsel 156.000', 'Pulsa', 'TELKOMSEL', 15404700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-816d62a8', 'Telkomsel 157.000', 'Pulsa', 'TELKOMSEL', 15503400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-65c77d93', 'Telkomsel 158.000', 'Pulsa', 'TELKOMSEL', 15602100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-92f25b00', 'Telkomsel 159.000', 'Pulsa', 'TELKOMSEL', 15700800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f3e98e48', 'Telkomsel 160.000', 'Pulsa', 'TELKOMSEL', 15799500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8e2759e8', 'Telkomsel 161.000', 'Pulsa', 'TELKOMSEL', 15898200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0ceb186a', 'Telkomsel 162.000', 'Pulsa', 'TELKOMSEL', 15996900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-59df239d', 'Telkomsel 163.000', 'Pulsa', 'TELKOMSEL', 16095600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7e06621d', 'Telkomsel 164.000', 'Pulsa', 'TELKOMSEL', 16194300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3749f355', 'Telkomsel 165.000', 'Pulsa', 'TELKOMSEL', 16293000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
