-- Batch 5 Chunk 6
-- Batch 5
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-tri-081aba77', 'Tri Data Unlimited Games COD 1 Hari', 'Data', 'TRI', 292500, true, '{"type":"Unlimited Games","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f9f00655', 'Tri Data Unlimited Sosmed Instagram 1 Hari', 'Data', 'TRI', 292500, true, '{"type":"Unlimited Sosmed","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-270f95bd', 'Tri Data Unlimited Sosmed Facebook 1 Hari', 'Data', 'TRI', 292500, true, '{"type":"Unlimited Sosmed","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8cbbc69d', 'Tri Data Unlimited Sosmed Twitter 1 Hari', 'Data', 'TRI', 292500, true, '{"type":"Unlimited Sosmed","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-018ff465', 'Tri Data 500 MB 14 Hari', 'Data', 'TRI', 292700, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-0ebfd6f0', 'Tri Data Happy 1.5 GB 1 Hari', 'Data', 'TRI', 313600, true, '{"type":"Happy","description":"Tri Data Happy 1.5 GB / 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-88fb71c0', 'Tri Data Happy 1 GB 3 Hari', 'Data', 'TRI', 352500, true, '{"type":"Happy","description":"Tri Data Happy 1 GB / 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-a38329a4', 'Tri Data Happy 1 GB 1 Hari', 'Data', 'TRI', 353500, true, '{"type":"Happy","description":"Tri Data Happy 1 GB / 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-67092b07', 'Tri Data Happy 2 GB 1 Hari', 'Data', 'TRI', 374200, true, '{"type":"Happy","description":"Tri Data Happy 2 GB / 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-34d06d39', 'Tri Data Happy 2.5 GB 1 Hari', 'Data', 'TRI', 396900, true, '{"type":"Happy","description":"Tri Data Happy 2.5 GB / 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7da97db7', 'Tri Data Happy 1.5 GB 1 Hari (Jawa Tengah)', 'Data', 'TRI', 420500, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ea7bde8a', 'Tri Data 750 MB 30 Hari', 'Data', 'TRI', 429200, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4d6de89c', 'Tri Data 750 MB 14 Hari', 'Data', 'TRI', 430300, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-107bccad', 'Tri Mix Small 2.5 GB 1 Hari', 'Data', 'TRI', 483000, true, '{"type":"Mix","description":"0.5 GB 24 jam, 2 GB (01.00-09.00), 1 hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c91645ba', 'Tri Data Addon 2.5 GB 1 Hari', 'Data', 'TRI', 485500, true, '{"type":"Addon","description":"1 GB 24 jam, 1.5 GB (01.00-09.00), 1 hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8f113146', 'Tri Data 1 GB + 1.5 GB (01-09) 1 Hari', 'Data', 'TRI', 485500, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7b9cdb3c', 'Kuota++ 80MB Semua Jaringan 1 Hari', 'Data', 'TRI', 490500, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c07fa1c4', 'Tri Mix Small 5 GB 1 Hari', 'Data', 'TRI', 501500, true, '{"type":"Mix","description":"1 GB (24 jam) + 4 GB (12 malam - 9 pagi) semua jaringan, Masa Aktif 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-a689d21f', '1GB Nasional + 4GB (01.00 - 09.00) 1 Hari', 'Data', 'TRI', 503000, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1d5cff82', 'Tri Data 1 GB 30 Hari', 'Data', 'TRI', 540000, true, '{"type":"Pure 30 Hari","description":"Tri Data 1 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3bf0fb3d', 'Tri Data Mini 1 GB 5 Hari', 'Data', 'TRI', 545000, true, '{"type":"Mini","description":"1 GB Nasional, 5 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-84c2b76e', 'Tri Mix Small 3 GB 1 Hari', 'Data', 'TRI', 550500, true, '{"type":"Mix","description":"1 GB (24 jam) + 2 GB (1 - 9 pagi) semua jaringan, Masa Aktif 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-24447a0b', 'Tri Data Happy 1 GB 5 Hari', 'Data', 'TRI', 557300, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4148a726', 'Tri Data 1 GB 14 Hari', 'Data', 'TRI', 560500, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-69db945d', 'Tri Data 1 GB 7 Hari', 'Data', 'TRI', 565500, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8dbf14d6', 'Three Data Transfer Unlimited Youtube / 1 Hari', 'Data', 'TRI', 570500, true, '{"type":"Data Transfer","description":"Unlimited Youtube / 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8e236206', 'Tri Data Unlimited Streaming Youtube 1 Hari', 'Data', 'TRI', 585000, true, '{"type":"Unlimited Streaming","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-2a5dee8c', 'Tri Data Unlimited Streaming Netflix 1 Hari', 'Data', 'TRI', 585000, true, '{"type":"Unlimited Streaming","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f380ea89', 'Tri Data Happy 3 GB 1 Hari', 'Data', 'TRI', 586800, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-66c246ee', 'Tri Data 750 MB 7 Hari', 'Data', 'TRI', 590500, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-69e0111e', 'Tri Data 1 GB Nasional + 500 MB Lokal / 30 Hari', 'Data', 'TRI', 623000, true, '{"type":"Lokal","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-a61942aa', 'Tri Data Happy 1.5 GB 3 Hari', 'Data', 'TRI', 632500, true, '{"type":"Happy","description":"Tri Data Happy 1.5 GB / 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-762e66fd', 'Tri Data Happy 5 GB 1 Hari', 'Data', 'TRI', 638500, true, '{"type":"Happy","description":"Tri Data Happy 5 GB / 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-df7e3d57', 'Tri Data Addon 1 GB 1 Hari', 'Data', 'TRI', 645500, true, '{"type":"Addon","description":"300 MB 24 jam, 700 MB (01.00-06.00), 1 hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-d1a8052b', 'Tri Data Happy Kikida 2 GB 1 Hari', 'Data', 'TRI', 645500, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e7884c4c', 'Tri Data Happy 6 GB 1 Hari', 'Data', 'TRI', 650000, true, '{"type":"Happy","description":"6 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b2ff4272', 'Tri Data Happy 2.5 GB 1 Hari (Jawa Tengah)', 'Data', 'TRI', 650500, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-eabb1534', 'Tri Data 1 GB Lokal / 5 Hari', 'Data', 'TRI', 655500, true, '{"type":"Lokal","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8c0c3aa7', 'Tri Data Happy Kikida 3 GB 1 Hari', 'Data', 'TRI', 691500, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c094b85a', 'Tri Data Happy 1 GB 3 Hari (Jawa Tengah)', 'Data', 'TRI', 700500, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-233a108e', 'Tri Data Happy 10 GB 1 Hari', 'Data', 'TRI', 759500, true, '{"type":"Happy","description":"10 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f9efe2cc', 'Tri Data Happy 5G 6 GB 1 Hari', 'Data', 'TRI', 775500, true, '{"type":"Happy 5G","description":"4 GB Utama + 2 GB 5G 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5964da16', 'Tri Data Happy 5 GB 2 Hari', 'Data', 'TRI', 800000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-45bf414b', 'Tri Data Happy 1.5 GB 7 Hari', 'Data', 'TRI', 800500, true, '{"type":"Happy","description":"Tri Data Happy 1.5 GB / 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7cd99a58', 'Tri Data Happy 3 GB 2 Hari', 'Data', 'TRI', 807500, true, '{"type":"Happy","description":"Tri Data Happy 3 GB / 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-df9a6fe5', 'Tri Data Mini 1.5 GB 5 Hari', 'Data', 'TRI', 835000, true, '{"type":"Mini","description":"1.5 GB Nasional, 5 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-23d962db', 'Tri Data 1.5 GB 30 Hari', 'Data', 'TRI', 848000, true, '{"type":"Pure 30 Hari","description":"Tri Data 1.5 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-85598070', 'Three Data Transfer 5 GB / 1 Hari', 'Data', 'TRI', 850000, true, '{"type":"Data Transfer","description":"750 MB Reguler + 4.25 GB jam 01.00 - 09.00, Berlaku 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b0a7982d', 'Tri Data Happy 3 GB 3 Hari', 'Data', 'TRI', 850400, true, '{"type":"Happy","description":"Tri Data Happy 3 GB / 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-73017f3a', 'Tri Data 1.5 GB 14 Hari', 'Data', 'TRI', 853000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
