-- Batch 18 Chunk 8
-- Batch 18
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('games-gunsofglory-97995d4d', 'Guns of Glory 100.000 Diamonds', 'Games', 'Guns of Glory', 1558746400, true, '{"type":"Umum","description":"Masukkan User ID","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-49ebf86701f49d3c27f49382ae4b3aed.jpg"}'),
  ('games-ragnaroktwilight-67a7c6b3', 'Ragnarok Twilight 8.000 Big Cat Gem', 'Games', 'Ragnarok Twilight', 1686707400, true, '{"type":"Umum","description":"Masukkan ID","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-814174a6bf183bd9122c4446ed9a7774.jpg"}'),
  ('games-whiteoutsurvivalfroststar-e4d725d4', 'Whiteout Survival 99.990 Frost Star', 'Games', 'Whiteout Survival Frost Star', 1829313400, true, '{"type":"Umum","description":"Masukkan User ID.","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-17a61d47b710aefef573f1ea747707ff.jpg"}'),
  ('games-ragnarokmeternallove-20cae049', '9012 Big Cat Coins', 'Games', 'Ragnarok M: Eternal Love', 1847862600, true, '{"type":"Umum","description":"9012 Big Cat Coins","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-46fcdb6927aa9481f8c16492e0aff68d.jpg"}'),
  ('games-ragnaroktwilight-59127edd', 'Ragnarok Twilight 10.000 Big Cat Gem', 'Games', 'Ragnarok Twilight', 2104584800, true, '{"type":"Umum","description":"Masukkan ID","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-814174a6bf183bd9122c4446ed9a7774.jpg"}'),
  ('games-onepunchman-6415860d', 'One Punch Man 16.013 Kupon', 'Games', 'One Punch Man', 2530082500, true, '{"type":"Umum","description":"Format no tujuan [UID]|[Server]","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-dd9e0a2aaed4f87edf07628539737f93.jpg"}'),
  ('pascabayar-plnpascabayar-53eaaf29', 'PLN PASCABAYAR', 'Pascabayar', 'PLN PASCABAYAR', NaN, true, '{"type":"Pascabayar","description":"PLN PASCABAYAR","image_url":null}'),
  ('pascabayar-pdam-5bc3c25f', 'PDAM', 'Pascabayar', 'PDAM', NaN, true, '{"type":"Pascabayar","description":"PDAM","image_url":null}'),
  ('pascabayar-hppascabayar-0fa50aa4', 'HP PASCABAYAR', 'Pascabayar', 'HP PASCABAYAR', NaN, true, '{"type":"Pascabayar","description":"HP PASCABAYAR","image_url":null}'),
  ('pascabayar-internetpascabayar-68716ad3', 'INTERNET PASCABAYAR', 'Pascabayar', 'INTERNET PASCABAYAR', NaN, true, '{"type":"Pascabayar","description":"INTERNET PASCABAYAR","image_url":null}'),
  ('pascabayar-bpjskesehatan-bd545fe9', 'BPJS KESEHATAN', 'Pascabayar', 'BPJS KESEHATAN', NaN, true, '{"type":"Pascabayar","description":"BPJS KESEHATAN","image_url":null}'),
  ('pascabayar-multifinance-b6757ad5', 'MULTIFINANCE', 'Pascabayar', 'MULTIFINANCE', NaN, true, '{"type":"Pascabayar","description":"MULTIFINANCE","image_url":null}'),
  ('pascabayar-pbb-20c05b4b', 'PBB', 'Pascabayar', 'PBB', NaN, true, '{"type":"Pascabayar","description":"PBB","image_url":null}'),
  ('pascabayar-gasnegara-b519d63a', 'GAS NEGARA', 'Pascabayar', 'GAS NEGARA', NaN, true, '{"type":"Pascabayar","description":"GAS NEGARA","image_url":null}'),
  ('pascabayar-tvpascabayar-452f1721', 'TV PASCABAYAR', 'Pascabayar', 'TV PASCABAYAR', NaN, true, '{"type":"Pascabayar","description":"TV PASCABAYAR","image_url":null}'),
  ('pascabayar-samsat-94946d37', 'SAMSAT', 'Pascabayar', 'SAMSAT', NaN, true, '{"type":"Pascabayar","description":"SAMSAT","image_url":null}'),
  ('pascabayar-bpjsketenagakerjaan-e478c431', 'BPJS KETENAGAKERJAAN', 'Pascabayar', 'BPJS KETENAGAKERJAAN', NaN, true, '{"type":"Pascabayar","description":"BPJS KETENAGAKERJAAN","image_url":null}'),
  ('pascabayar-plnnontaglis-5b730b77', 'PLN NONTAGLIS', 'Pascabayar', 'PLN NONTAGLIS', NaN, true, '{"type":"Pascabayar","description":"PLN NONTAGLIS","image_url":null}'),
  ('pascabayar-emoney-c9b551a3', 'E-MONEY', 'Pascabayar', 'E-MONEY', NaN, true, '{"type":"Pascabayar","description":"E-MONEY","image_url":null}'),
  ('pascabayar-telkomselomni-fc6e6256', 'Telkomsel Omni', 'Pascabayar', 'Telkomsel Omni', NaN, true, '{"type":"Pascabayar","description":"Telkomsel Omni","image_url":null}'),
  ('pascabayar-indosatonly4u-5a9718b4', 'Indosat Only4u', 'Pascabayar', 'Indosat Only4u', NaN, true, '{"type":"Pascabayar","description":"Indosat Only4u","image_url":null}'),
  ('pascabayar-tricuanmax-f7c4fc42', 'Tri CuanMax', 'Pascabayar', 'Tri CuanMax', NaN, true, '{"type":"Pascabayar","description":"Tri CuanMax","image_url":null}'),
  ('pascabayar-xlaxiscuanku-773af369', 'XL Axis Cuanku', 'Pascabayar', 'XL Axis Cuanku', NaN, true, '{"type":"Pascabayar","description":"XL Axis Cuanku","image_url":null}'),
  ('pascabayar-byu-2dfe3c2c', 'by.U', 'Pascabayar', 'by.U', NaN, true, '{"type":"Pascabayar","description":"by.U","image_url":null}'),
  ('pln-pln-f8a03b37', 'Cek Nama Token PLN', 'PLN', 'PLN', 500, true, '{"type":"Umum","description":"Cek Nama Token PLN","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-63d50389', 'PLN 5.000', 'PLN', 'PLN', 640000, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-043d97d7', 'PLN 10.000', 'PLN', 'PLN', 1140000, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-8511ef6f', 'PLN 15.000', 'PLN', 'PLN', 1640000, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-3b7b774e', 'PLN 20.000', 'PLN', 'PLN', 1950000, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-589b1286', 'PLN 25.000', 'PLN', 'PLN', 2628500, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-db706107', 'PLN 50.000', 'PLN', 'PLN', 4952500, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-83376cfd', 'PLN 100.000', 'PLN', 'PLN', 9782500, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-6fd9243d', 'PLN 200.000', 'PLN', 'PLN', 20050000, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-3627d6be', 'PLN 500.000', 'PLN', 'PLN', 49950000, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pln-pln-a73efab3', 'PLN 1.000.000', 'PLN', 'PLN', 99972500, true, '{"type":"Umum","description":"masukkan nomor meter/id pelanggan","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-eef4a9697efeb2e67c6a96199aa8ed6f.jpg"}'),
  ('pulsa-axis-88f9cf1b', 'Axis 5.000', 'Pulsa', 'AXIS', 440000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-23ea5921', 'Axis 10.000', 'Pulsa', 'AXIS', 940000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-10f89bf3', 'Axis 15.000', 'Pulsa', 'AXIS', 1399000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-60ff2f43', 'Axis 20.000', 'Pulsa', 'AXIS', 2028500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-d529326d', 'Axis 25.000', 'Pulsa', 'AXIS', 2315000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-104f9ab6', 'Axis 30.000', 'Pulsa', 'AXIS', 2890000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-d14e14f5', 'Axis 40.000', 'Pulsa', 'AXIS', 3922500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-0c266fec', 'Axis 50.000', 'Pulsa', 'AXIS', 4760000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-5dff65bf', 'Axis 60.000', 'Pulsa', 'AXIS', 5945000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-18da329d', 'Axis 70.000', 'Pulsa', 'AXIS', 6942500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-3354652a', 'Axis 80.000', 'Pulsa', 'AXIS', 7900000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-3468813e', 'Axis 90.000', 'Pulsa', 'AXIS', 8910000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-122d485c', 'Axis 100.000', 'Pulsa', 'AXIS', 9670000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-e7d24cb9', 'Axis 150.000', 'Pulsa', 'AXIS', 14905000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}'),
  ('pulsa-axis-860d4218', 'Axis 200.000', 'Pulsa', 'AXIS', 19872500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
