-- Batch 19 Chunk 1
-- Batch 19
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-byu-0abee8f3', 'by.U 100.000', 'Pulsa', 'by.U', 9699500, true, '{"type":"Umum","description":"Reguler","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-ff9ca5877c7b6a00afb1b0b8d36356a1.jpg"}'),
  ('pulsa-byu-7726c4bb', 'by.U 98.000', 'Pulsa', 'by.U', 9723800, true, '{"type":"Umum","description":"Reguler","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-ff9ca5877c7b6a00afb1b0b8d36356a1.jpg"}'),
  ('pulsa-byu-286f95cf', 'by.U 99.000', 'Pulsa', 'by.U', 9823000, true, '{"type":"Umum","description":"Reguler","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-ff9ca5877c7b6a00afb1b0b8d36356a1.jpg"}'),
  ('pulsa-byu-3fc6e13f', 'by.U 150.000', 'Pulsa', 'by.U', 14510500, true, '{"type":"Umum","description":"Reguler","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-ff9ca5877c7b6a00afb1b0b8d36356a1.jpg"}'),
  ('pulsa-byu-7489400a', 'by.U 200.000', 'Pulsa', 'by.U', 19325000, true, '{"type":"Umum","description":"Reguler","image_url":"https://digiflazz.s3.ap-southeast-1.amazonaws.com/brand/brand-ff9ca5877c7b6a00afb1b0b8d36356a1.jpg"}'),
  ('pulsa-indosat-ee98daac', 'Indosat 5.000', 'Pulsa', 'INDOSAT', 479000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-48809fa2', 'Indosat 10.000', 'Pulsa', 'INDOSAT', 975000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-d5144712', 'Indosat 12.000', 'Pulsa', 'INDOSAT', 1146000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-d82c7e0d', 'Indosat 15.000', 'Pulsa', 'INDOSAT', 1395000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-3f574be1', 'Indosat 12.000 + 1 GB', 'Pulsa', 'INDOSAT', 1901000, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-c84548f4', 'Indosat 20.000', 'Pulsa', 'INDOSAT', 1905000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-36579811', 'Indosat 15.000 + 1 GB', 'Pulsa', 'INDOSAT', 2251000, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-ca2f8753', 'Indosat 25.000', 'Pulsa', 'INDOSAT', 2305000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-95e9c38a', 'Indosat 20.000 + 500 MB', 'Pulsa', 'INDOSAT', 2391000, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-e81b79a6', 'Indosat 20.000 + 1 GB', 'Pulsa', 'INDOSAT', 2652500, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-45eb6109', 'Indosat 30.000', 'Pulsa', 'INDOSAT', 2840000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-2ecf3950', 'Indosat 25.000 + 500 MB', 'Pulsa', 'INDOSAT', 2872500, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-ea67a1c6', 'Indosat 25.000 + 1 GB', 'Pulsa', 'INDOSAT', 3152500, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-13124dee', 'Indosat 35.000', 'Pulsa', 'INDOSAT', 3492000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-02dcf507', 'Indosat 40.000', 'Pulsa', 'INDOSAT', 3875000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-671f535b', 'Indosat 45.000', 'Pulsa', 'INDOSAT', 4429700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-57b52292', 'Indosat 50.000', 'Pulsa', 'INDOSAT', 4650000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-976cff7d', 'Indosat 55.000', 'Pulsa', 'INDOSAT', 5402700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-22084d7b', 'Indosat 60.000', 'Pulsa', 'INDOSAT', 5730000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-1b63ec3c', 'Indosat 65.000', 'Pulsa', 'INDOSAT', 6375700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-4c314a7b', 'Indosat 70.000', 'Pulsa', 'INDOSAT', 6680000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-0be45208', 'Indosat 80.000', 'Pulsa', 'INDOSAT', 7664500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-1c997e6e', 'Indosat 85.000', 'Pulsa', 'INDOSAT', 8293500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-ce20f464', 'Indosat 90.000', 'Pulsa', 'INDOSAT', 8644500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-66e89a82', 'Indosat 100.000', 'Pulsa', 'INDOSAT', 9250000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-f19e5a6a', 'Indosat 105.000', 'Pulsa', 'INDOSAT', 10267700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-5c0f8f6e', 'Indosat 115.000', 'Pulsa', 'INDOSAT', 11240700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-f197b259', 'Indosat 125.000', 'Pulsa', 'INDOSAT', 11824000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-34f5ed03', 'Indosat 150.000', 'Pulsa', 'INDOSAT', 14199600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-a878910a', 'Indosat 175.000', 'Pulsa', 'INDOSAT', 17117000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-8e166062', 'Indosat 200.000', 'Pulsa', 'INDOSAT', 19048700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-e9317653', 'Indosat 225.000', 'Pulsa', 'INDOSAT', 22019600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-dfb2c536', 'Indosat 250.000', 'Pulsa', 'INDOSAT', 24427100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-e3ddf6ca', 'Indosat 300.000', 'Pulsa', 'INDOSAT', 28801000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-6c2da528', 'Indosat 340.000', 'Pulsa', 'INDOSAT', 33156100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-74765960', 'Indosat 400.000', 'Pulsa', 'INDOSAT', 38650800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-a55877dc', 'Indosat 500.000', 'Pulsa', 'INDOSAT', 47500000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-indosat-2fb33323', 'Indosat 1.000.000', 'Pulsa', 'INDOSAT', 98540000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}'),
  ('pulsa-smartfren-18213761', 'Smartfren 2.000', 'Pulsa', 'SMARTFREN', 194900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-41524e2d', 'Smartfren 3.000', 'Pulsa', 'SMARTFREN', 291500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-7263449a', 'Smartfren 4.000', 'Pulsa', 'SMARTFREN', 388500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-fc7bd1fe', 'Smartfren 5.000', 'Pulsa', 'SMARTFREN', 420000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-41992e1d', 'Smartfren 6.000', 'Pulsa', 'SMARTFREN', 582500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-421193df', 'Smartfren 7.000', 'Pulsa', 'SMARTFREN', 677200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}'),
  ('pulsa-smartfren-19c087b7', 'Smartfren 8.000', 'Pulsa', 'SMARTFREN', 773700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
