-- Batch 19 Chunk 3
-- Batch 19
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-02d8b104', 'Telkomsel 16.000', 'Pulsa', 'TELKOMSEL', 1676000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-19adc975', 'Telkomsel 17.000', 'Pulsa', 'TELKOMSEL', 1776000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9cd9a6c0', 'Telkomsel 20.000', 'Pulsa', 'TELKOMSEL', 1830000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4e67740e', 'Telkomsel 18.000', 'Pulsa', 'TELKOMSEL', 1876000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-848a3616', 'Telkomsel 19.000', 'Pulsa', 'TELKOMSEL', 1973500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ec10e4e7', 'Telkomsel 21.000', 'Pulsa', 'TELKOMSEL', 2080500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-07ef8efd', 'Telkomsel 22.000', 'Pulsa', 'TELKOMSEL', 2179500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4dddc8a9', 'Telkomsel 23.000', 'Pulsa', 'TELKOMSEL', 2278500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0b9aba13', 'Telkomsel 25.000', 'Pulsa', 'TELKOMSEL', 2320000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-af3add0b', 'Telkomsel 24.000', 'Pulsa', 'TELKOMSEL', 2377500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8e0eb499', 'Telkomsel 26.000', 'Pulsa', 'TELKOMSEL', 2571100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ada0af72', 'Telkomsel 27.000', 'Pulsa', 'TELKOMSEL', 2669700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d3d9fbaa', 'Telkomsel 28.000', 'Pulsa', 'TELKOMSEL', 2768300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9005dcad', 'Telkomsel 30.000', 'Pulsa', 'TELKOMSEL', 2777500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fe3e550f', 'Telkomsel 29.000', 'Pulsa', 'TELKOMSEL', 2866900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9e925596', 'Telkomsel 31.000', 'Pulsa', 'TELKOMSEL', 3064100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5822cd0c', 'Telkomsel 32.000', 'Pulsa', 'TELKOMSEL', 3164100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e59dee31', 'Telkomsel 33.000', 'Pulsa', 'TELKOMSEL', 3262900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5406d2ae', 'Telkomsel 35.000', 'Pulsa', 'TELKOMSEL', 3277500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8d123286', 'Telkomsel 34.000', 'Pulsa', 'TELKOMSEL', 3361700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-44e25053', 'Telkomsel 36.000', 'Pulsa', 'TELKOMSEL', 3552100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3ed42e74', 'Telkomsel 37.000', 'Pulsa', 'TELKOMSEL', 3650700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-676adda3', 'Telkomsel 38.000', 'Pulsa', 'TELKOMSEL', 3749300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-389d7684', 'Telkomsel 39.000', 'Pulsa', 'TELKOMSEL', 3847900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1e6b755f', 'Telkomsel 40.000', 'Pulsa', 'TELKOMSEL', 3865000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-45923bfb', 'Telkomsel 41.000', 'Pulsa', 'TELKOMSEL', 4047600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e43b938e', 'Telkomsel 42.000', 'Pulsa', 'TELKOMSEL', 4143700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f6cbea37', 'Telkomsel 43.000', 'Pulsa', 'TELKOMSEL', 4244800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4c339188', 'Telkomsel 44.000', 'Pulsa', 'TELKOMSEL', 4340900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9f766634', 'Telkomsel 46.000', 'Pulsa', 'TELKOMSEL', 4372500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6c49ef35', 'Telkomsel 45.000', 'Pulsa', 'TELKOMSEL', 4417500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a293324e', 'Telkomsel 47.000', 'Pulsa', 'TELKOMSEL', 4636700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-46d59af4', 'Telkomsel 50.000', 'Pulsa', 'TELKOMSEL', 4670000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b960cfdd', 'Telkomsel 48.000', 'Pulsa', 'TELKOMSEL', 4735300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-efe4c85a', 'Telkomsel 49.000', 'Pulsa', 'TELKOMSEL', 4833900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3da8024a', 'Telkomsel 51.000', 'Pulsa', 'TELKOMSEL', 5038600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1ae0d821', 'Telkomsel 52.000', 'Pulsa', 'TELKOMSEL', 5137200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1e64dd9b', 'Telkomsel 53.000', 'Pulsa', 'TELKOMSEL', 5235800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-22feb1ea', 'Telkomsel 54.000', 'Pulsa', 'TELKOMSEL', 5334400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-eee6c6c9', 'Telkomsel 55.000', 'Pulsa', 'TELKOMSEL', 5400000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-20c7fdb2', 'Telkomsel 56.000', 'Pulsa', 'TELKOMSEL', 5531600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-90d679c3', 'Telkomsel 57.000', 'Pulsa', 'TELKOMSEL', 5630200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7c3acb9c', 'Telkomsel 58.000', 'Pulsa', 'TELKOMSEL', 5728800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-09811d0d', 'Telkomsel 59.000', 'Pulsa', 'TELKOMSEL', 5827400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e94b62f9', 'Telkomsel 60.000', 'Pulsa', 'TELKOMSEL', 5835000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d862ea58', 'Telkomsel 61.000', 'Pulsa', 'TELKOMSEL', 6024600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4ecf2cab', 'Telkomsel 62.000', 'Pulsa', 'TELKOMSEL', 6123200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9bb1557b', 'Telkomsel 63.000', 'Pulsa', 'TELKOMSEL', 6221800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-da47aee3', 'Telkomsel 64.000', 'Pulsa', 'TELKOMSEL', 6320400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-524cf027', 'Telkomsel 65.000', 'Pulsa', 'TELKOMSEL', 6385000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
