-- Batch 19 Chunk 4
-- Batch 19
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-71fecd67', 'Telkomsel 66.000', 'Pulsa', 'TELKOMSEL', 6517600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a90f2aea', 'Telkomsel 67.000', 'Pulsa', 'TELKOMSEL', 6616200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ec8d84c3', 'Telkomsel 70.000', 'Pulsa', 'TELKOMSEL', 6702500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f2a241a6', 'Telkomsel 68.000', 'Pulsa', 'TELKOMSEL', 6714800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-891ed91b', 'Telkomsel 69.000', 'Pulsa', 'TELKOMSEL', 6813400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9f5f75fb', 'Telkomsel 71.000', 'Pulsa', 'TELKOMSEL', 7010600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-946bd9a4', 'Telkomsel 72.000', 'Pulsa', 'TELKOMSEL', 7109200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b938ef88', 'Telkomsel 73.000', 'Pulsa', 'TELKOMSEL', 7207800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0997eced', 'Telkomsel 75.000', 'Pulsa', 'TELKOMSEL', 7250000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-52c80045', 'Telkomsel 74.000', 'Pulsa', 'TELKOMSEL', 7306400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8c07b85a', 'Telkomsel 76.000', 'Pulsa', 'TELKOMSEL', 7503600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-06867196', 'Telkomsel 77.000', 'Pulsa', 'TELKOMSEL', 7602200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-02ac9f1b', 'Telkomsel 78.000', 'Pulsa', 'TELKOMSEL', 7700800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6e4acd72', 'Telkomsel 79.000', 'Pulsa', 'TELKOMSEL', 7799400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f6300dbc', 'Telkomsel 80.000', 'Pulsa', 'TELKOMSEL', 7830000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5b861cb6', 'Telkomsel 81.000', 'Pulsa', 'TELKOMSEL', 7996600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1b2b5dda', 'Telkomsel 82.000', 'Pulsa', 'TELKOMSEL', 8095200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6b85c9b8', 'Telkomsel 83.000', 'Pulsa', 'TELKOMSEL', 8193800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8ace105d', 'Telkomsel 84.000', 'Pulsa', 'TELKOMSEL', 8292400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e069b52a', 'Telkomsel 85.000', 'Pulsa', 'TELKOMSEL', 8350000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7aa82086', 'Telkomsel 86.000', 'Pulsa', 'TELKOMSEL', 8489600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-75f45e25', 'Telkomsel 87.000', 'Pulsa', 'TELKOMSEL', 8588200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6fd9c2c5', 'Telkomsel 88.000', 'Pulsa', 'TELKOMSEL', 8686800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ce56d394', 'Telkomsel 89.000', 'Pulsa', 'TELKOMSEL', 8785400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f3fd2349', 'Telkomsel 90.000', 'Pulsa', 'TELKOMSEL', 8822500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-de3f9b87', 'Telkomsel 91.000', 'Pulsa', 'TELKOMSEL', 8982600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6685ee71', 'Telkomsel 92.000', 'Pulsa', 'TELKOMSEL', 9081200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c6ec600c', 'Telkomsel 93.000', 'Pulsa', 'TELKOMSEL', 9179800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fe128a1d', 'Telkomsel 94.000', 'Pulsa', 'TELKOMSEL', 9278400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5106fdfa', 'Telkomsel 95.000', 'Pulsa', 'TELKOMSEL', 9300000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-63f9098b', 'Telkomsel 100.000', 'Pulsa', 'TELKOMSEL', 9440000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-49ec0a0b', 'Telkomsel 96.000', 'Pulsa', 'TELKOMSEL', 9475600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3872865c', 'Telkomsel 97.000', 'Pulsa', 'TELKOMSEL', 9574200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-493db445', 'Telkomsel 98.000', 'Pulsa', 'TELKOMSEL', 9672800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a0a085dc', 'Telkomsel 99.000', 'Pulsa', 'TELKOMSEL', 9771400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ac565170', 'Telkomsel 101.000', 'Pulsa', 'TELKOMSEL', 9976200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ca192ebf', 'Telkomsel 102.000', 'Pulsa', 'TELKOMSEL', 10074900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8757ecb4', 'Telkomsel 103.000', 'Pulsa', 'TELKOMSEL', 10173600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4d160662', 'Telkomsel 104.000', 'Pulsa', 'TELKOMSEL', 10272300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-98db9e4a', 'Telkomsel 105.000', 'Pulsa', 'TELKOMSEL', 10371000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-78b49687', 'Telkomsel 106.000', 'Pulsa', 'TELKOMSEL', 10469700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8027e4f8', 'Telkomsel 107.000', 'Pulsa', 'TELKOMSEL', 10568400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-36508c1e', 'Telkomsel 108.000', 'Pulsa', 'TELKOMSEL', 10667100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ec6eaedc', 'Telkomsel 109.000', 'Pulsa', 'TELKOMSEL', 10765800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-75b061cd', 'Telkomsel 110.000', 'Pulsa', 'TELKOMSEL', 10864500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d0c63838', 'Telkomsel 111.000', 'Pulsa', 'TELKOMSEL', 10963200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b43df76a', 'Telkomsel 112.000', 'Pulsa', 'TELKOMSEL', 11061900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-798fe424', 'Telkomsel 113.000', 'Pulsa', 'TELKOMSEL', 11160600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d4763595', 'Telkomsel 114.000', 'Pulsa', 'TELKOMSEL', 11259300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9aa08207', 'Telkomsel 115.000', 'Pulsa', 'TELKOMSEL', 11358000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
