-- Batch 5 Chunk 8
-- Batch 5
INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-tri-adcbd24b', 'Tri Data Happy Kikida 4.5 GB 5 Hari', 'Data', 'TRI', 1548000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-184ff851', 'Three Data Transfer 5 GB / 7 Hari', 'Data', 'TRI', 1591000, true, '{"type":"Data Transfer","description":"2.5 GB Reguler + 2.5 GB jam 01.00 - 09.00, Berlaku 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-42ed5319', 'Tri Data Happy Ramadan 20 GB 3 Hari', 'Data', 'TRI', 1602200, true, '{"type":"Ramadan","description":"Kuota Utama 20 GB","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6836902c', 'Tri Data 2.75 GB 7 Hari', 'Data', 'TRI', 1644500, true, '{"type":"Umum","description":"750MB + 2 GB 4G, 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-317d1944', 'Tri Data Happy 10 GB 5 Hari', 'Data', 'TRI', 1648500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f28a2d68', 'Tri Data Happy 8 GB 5 Hari', 'Data', 'TRI', 1650000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-60269060', 'Tri Data 3 GB 14 Hari', 'Data', 'TRI', 1679000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-eee142a7', 'Tri Data Happy 5G 12 GB 3 Hari', 'Data', 'TRI', 1690000, true, '{"type":"Happy 5G","description":"9 GB Utama + 3 GB 5G 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c7c8c3ea', 'Tri Data 3 GB 7 Hari', 'Data', 'TRI', 1696000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-635aacf7', 'Tri Data AlwaysOn 2 GB', 'Data', 'TRI', 1768000, true, '{"type":"AlwaysOn","description":"2 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4d76e699', 'Tri Data Happy Kikida 7 GB 5 Hari', 'Data', 'TRI', 1801000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9b93f23e', 'Tri Data Happy 4.5 GB 7 Hari', 'Data', 'TRI', 1852500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3c578531', 'Tri Data Happy 5 GB 7 Hari', 'Data', 'TRI', 1852500, true, '{"type":"Happy","description":"Tri Data Happy 5 GB / 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5f7e0c00', 'Tri Data Happy 8 GB 7 Hari', 'Data', 'TRI', 1857500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-93d15799', 'Tri Data GetMore 4 GB / 30 Hari', 'Data', 'TRI', 1890000, true, '{"type":"GetMore","description":"2 GB 24 Jam (60 Hari) + 2 GB Youtube dan Netflix Jam 01.00 - 17.00 (30 hari)","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5a370b1c', 'Tri Data AlwaysOn 1.5 GB', 'Data', 'TRI', 1900000, true, '{"type":"AlwaysOn","description":"1.5 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7660f55d', 'Tri Data Happy 6 GB 5 Hari (Jawa Tengah)', 'Data', 'TRI', 1901000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-38f404e4', 'Tri Data Mini 5 GB 7 Hari', 'Data', 'TRI', 1901800, true, '{"type":"Mini","description":"2.5 GB Nasional, 2.5 GB (01.00 - 09.00), 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-24b1af97', 'Tri Data ++ 650 MB', 'Data', 'TRI', 1911000, true, '{"type":"Umum","description":"Kuota 650 MB mengikuti masa aktif kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c9b10c89', 'Tri Data Happy 11 GB 5 Hari', 'Data', 'TRI', 1949900, true, '{"type":"Happy","description":"11 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-117d1562', 'Tri Data Happy 3.5 GB 28 Hari', 'Data', 'TRI', 1962500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-82b23766', 'Tri Data AlwaysOn 3.5 GB', 'Data', 'TRI', 1970500, true, '{"type":"AlwaysOn","description":"3.5 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-acb879f4', 'Tri Data Happy 9 GB 7 Hari', 'Data', 'TRI', 1980500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e22ababf', 'Tri Data Happy 9 GB 7 Hari (Kalisumapa)', 'Data', 'TRI', 1985000, true, '{"type":"Kalisumapa","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e15a5179', 'Tri Data Happy 5 GB 7 Hari (Jawa Tengah)', 'Data', 'TRI', 1991000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3dc08450', 'Tri Data Happy 3 GB 14 Hari', 'Data', 'TRI', 1999000, true, '{"type":"Happy","description":"Tri Data Happy 3 GB / 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9728c341', 'Tri Data Happy 9 GB 5 Hari', 'Data', 'TRI', 2000000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-40978022', 'Tri Data Happy 10 GB 7 Hari', 'Data', 'TRI', 2002500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c476abf7', 'Tri Data Happy 3 GB 20 Hari', 'Data', 'TRI', 2011700, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4556396d', 'Tri Mix Small 3.75 GB 7 Hari', 'Data', 'TRI', 2026000, true, '{"type":"Mix","description":"1.75 GB (semua jaringan) + 2 GB (jaringan 4G), Masa Aktif 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5633595c', 'Tri Data AlwaysOn 3 GB', 'Data', 'TRI', 2050000, true, '{"type":"AlwaysOn","description":"3 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-66c10ac0', 'Tri Data Happy 7 GB 14 Hari', 'Data', 'TRI', 2072300, true, '{"type":"Happy","description":"7 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3a6383b1', 'Tri Data Happy 4.5 GB 28 Hari', 'Data', 'TRI', 2072500, true, '{"type":"Happy","description":"Tri Data Happy 4.5 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6c6b4c67', 'Tri Data Happy 15 GB 7 Hari', 'Data', 'TRI', 2075000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8af99398', 'Tri Data HiFi Air Booster 20 GB', 'Data', 'TRI', 2091000, true, '{"type":"HiFi Air","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b880b805', 'Tri Mix Small 3.75 GB 14 Hari', 'Data', 'TRI', 2125000, true, '{"type":"Mix","description":"1.75 GB (semua jaringan) + 2 GB (jaringan 4G), Masa Aktif 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-22576a04', 'Tri Data Happy 12 GB 7 Hari', 'Data', 'TRI', 2192500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-a5ae8b99', 'Tri Data Happy Travel 10 GB + 500 MB Roaming 3 Hari', 'Data', 'TRI', 2194800, true, '{"type":"Happy Travel","description":"Malaysia, Singapore, China dan Australia","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-241a9967', 'Tri Data 4 GB 30 Hari', 'Data', 'TRI', 2200000, true, '{"type":"Pure 30 Hari","description":"4 GB Nasional 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e07662bd', 'Tri Data Happy 9 GB 7 Hari (EJBN)', 'Data', 'TRI', 2201000, true, '{"type":"EJBN","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-56668659', 'Tri Data Happy Kikida 10 GB 7 Hari', 'Data', 'TRI', 2231000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5ba6da42', 'Tri Data 4 GB 7 Hari', 'Data', 'TRI', 2232000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b313b0a8', 'Tri Data 4 GB 14 Hari', 'Data', 'TRI', 2235000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-69fabfed', 'Tri Data Happy 9 GB 7 Hari (Jawa Tengah)', 'Data', 'TRI', 2241000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3bf45bdf', 'Tri Data Happy 6 GB 28 Hari', 'Data', 'TRI', 2244700, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-676bc90a', 'Tri Data Happy Play Games 6 GB 7 Hari', 'Data', 'TRI', 2402500, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5692e55b', 'Tri Data Happy Play Movies 6 GB 7 Hari', 'Data', 'TRI', 2404200, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-19281bd7', 'Tri Data Happy 5 GB 28 Hari', 'Data', 'TRI', 2416800, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-728378dc', 'Tri Data Happy 4 GB 28 Hari', 'Data', 'TRI', 2421800, true, '{"type":"Happy","description":"4 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-2135a358', 'Tri Data Happy 7 GB 28 Hari', 'Data', 'TRI', 2435000, true, '{"type":"Happy","description":"Tri Data Happy 7 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
