-- Chunk 005 from batch-001
-- Products: 50

INSERT INTO demo_products (
  sku_digiflazz, name, category, provider, 
  base_price_minor, is_active, metadata,
  main_category, sub_category, product_type
)
VALUES
  ('pulsa-telkomsel-f2db775e', 'Telkomsel 205.000', 'Pulsa', 'TELKOMSEL', 20241000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum',
  ('pulsa-telkomsel-d95c3ec7', 'Telkomsel 210.000', 'Pulsa', 'TELKOMSEL', 20734500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-b7387248', 'Telkomsel 215.000', 'Pulsa', 'TELKOMSEL', 21228000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-df07908c', 'Telkomsel 220.000', 'Pulsa', 'TELKOMSEL', 21721500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-1ce1eeff', 'Telkomsel 225.000', 'Pulsa', 'TELKOMSEL', 22215000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-88039a93', 'Telkomsel 230.000', 'Pulsa', 'TELKOMSEL', 22708500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-ca5daa5a', 'Telkomsel 235.000', 'Pulsa', 'TELKOMSEL', 23202000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-b5685b90', 'Telkomsel 240.000', 'Pulsa', 'TELKOMSEL', 23695500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5314854b', 'Telkomsel 245.000', 'Pulsa', 'TELKOMSEL', 24189000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-c170216e', 'Telkomsel 246.000', 'Pulsa', 'TELKOMSEL', 24287700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-99afb4af', 'Telkomsel 247.000', 'Pulsa', 'TELKOMSEL', 24386400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-aff5e288', 'Telkomsel 248.000', 'Pulsa', 'TELKOMSEL', 24485100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-01f76387', 'Telkomsel 249.000', 'Pulsa', 'TELKOMSEL', 24583800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-9e260839', 'Telkomsel 250.000', 'Pulsa', 'TELKOMSEL', 24695000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-9b69c9c1', 'Telkomsel 251.000', 'Pulsa', 'TELKOMSEL', 24781200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-3fa98fef', 'Telkomsel 252.000', 'Pulsa', 'TELKOMSEL', 24879900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-f9efab43', 'Telkomsel 253.000', 'Pulsa', 'TELKOMSEL', 24978600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-bb83eb6c', 'Telkomsel 254.000', 'Pulsa', 'TELKOMSEL', 25077300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-4cf43902', 'Telkomsel 255.000', 'Pulsa', 'TELKOMSEL', 25176000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-38e22577', 'Telkomsel 256.000', 'Pulsa', 'TELKOMSEL', 25274700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-f19b887b', 'Telkomsel 257.000', 'Pulsa', 'TELKOMSEL', 25373400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-aa07280c', 'Telkomsel 258.000', 'Pulsa', 'TELKOMSEL', 25472100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-3f9c0c18', 'Telkomsel 259.000', 'Pulsa', 'TELKOMSEL', 25570800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-2ceb7638', 'Telkomsel 260.000', 'Pulsa', 'TELKOMSEL', 25669500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-857a4471', 'Telkomsel 261.000', 'Pulsa', 'TELKOMSEL', 25768200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0c5ad41d', 'Telkomsel 262.000', 'Pulsa', 'TELKOMSEL', 25866900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0e7b380d', 'Telkomsel 263.000', 'Pulsa', 'TELKOMSEL', 25965600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-73d2382d', 'Telkomsel 264.000', 'Pulsa', 'TELKOMSEL', 26064300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-a665d881', 'Telkomsel 265.000', 'Pulsa', 'TELKOMSEL', 26163000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-c7025a00', 'Telkomsel 266.000', 'Pulsa', 'TELKOMSEL', 26261700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-db2084b7', 'Telkomsel 267.000', 'Pulsa', 'TELKOMSEL', 26360400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-de06b818', 'Telkomsel 268.000', 'Pulsa', 'TELKOMSEL', 26459100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-da09e4aa', 'Telkomsel 269.000', 'Pulsa', 'TELKOMSEL', 26557800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-052f4ce8', 'Telkomsel 270.000', 'Pulsa', 'TELKOMSEL', 26656500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-92e87e19', 'Telkomsel 271.000', 'Pulsa', 'TELKOMSEL', 26755200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-bd674817', 'Telkomsel 272.000', 'Pulsa', 'TELKOMSEL', 26853900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-f522499e', 'Telkomsel 273.000', 'Pulsa', 'TELKOMSEL', 26952600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-d75b318a', 'Telkomsel 274.000', 'Pulsa', 'TELKOMSEL', 27051300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-05e188b3', 'Telkomsel 275.000', 'Pulsa', 'TELKOMSEL', 27162500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-6bb3aac5', 'Telkomsel 276.000', 'Pulsa', 'TELKOMSEL', 27248700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-795a0189', 'Telkomsel 277.000', 'Pulsa', 'TELKOMSEL', 27347400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-e5948d79', 'Telkomsel 278.000', 'Pulsa', 'TELKOMSEL', 27446100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-08c865d4', 'Telkomsel 279.000', 'Pulsa', 'TELKOMSEL', 27544800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-ae93fc83', 'Telkomsel 280.000', 'Pulsa', 'TELKOMSEL', 27643500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-22276f99', 'Telkomsel 281.000', 'Pulsa', 'TELKOMSEL', 27742200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-a3402936', 'Telkomsel 282.000', 'Pulsa', 'TELKOMSEL', 27840900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-c540bbf4', 'Telkomsel 283.000', 'Pulsa', 'TELKOMSEL', 27939600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-65a3967a', 'Telkomsel 284.000', 'Pulsa', 'TELKOMSEL', 28038300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-9a36c7a5', 'Telkomsel 285.000', 'Pulsa', 'TELKOMSEL', 28137000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  'pulsa-telkomsel-5c90adea', 'Telkomsel 286.000', 'Pulsa', 'TELKOMSEL', 28235700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum')
ON CONFLICT (sku_digiflazz) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  provider = EXCLUDED.provider,
  base_price_minor = EXCLUDED.base_price_minor,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  main_category = EXCLUDED.main_category,
  sub_category = EXCLUDED.sub_category,
  product_type = EXCLUDED.product_type,
  updated_at = NOW();
