-- Chunk 002 from batch-001
-- Products: 50

INSERT INTO demo_products (
  sku_digiflazz, name, category, provider, 
  base_price_minor, is_active, metadata,
  main_category, sub_category, product_type
)
VALUES
  ('pulsa-telkomsel-e0e40dcc', 'Telkomsel 51.000', 'Pulsa', 'TELKOMSEL', 5038600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum',
  ('pulsa-telkomsel-e03329da', 'Telkomsel 52.000', 'Pulsa', 'TELKOMSEL', 5137200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-a535e069', 'Telkomsel 53.000', 'Pulsa', 'TELKOMSEL', 5235800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-45aea665', 'Telkomsel 54.000', 'Pulsa', 'TELKOMSEL', 5334400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-9ef78c41', 'Telkomsel 55.000', 'Pulsa', 'TELKOMSEL', 5400000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-da6af978', 'Telkomsel 56.000', 'Pulsa', 'TELKOMSEL', 5531600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-1b79432e', 'Telkomsel 57.000', 'Pulsa', 'TELKOMSEL', 5630200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-79176101', 'Telkomsel 58.000', 'Pulsa', 'TELKOMSEL', 5728800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5120cb86', 'Telkomsel 59.000', 'Pulsa', 'TELKOMSEL', 5827400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-1d718c08', 'Telkomsel 60.000', 'Pulsa', 'TELKOMSEL', 5835000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-f6738ed0', 'Telkomsel 61.000', 'Pulsa', 'TELKOMSEL', 6024600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-b3dd67fa', 'Telkomsel 62.000', 'Pulsa', 'TELKOMSEL', 6123200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-cab55bfe', 'Telkomsel 63.000', 'Pulsa', 'TELKOMSEL', 6221800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-06a34895', 'Telkomsel 64.000', 'Pulsa', 'TELKOMSEL', 6320400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-9fd8bb3e', 'Telkomsel 65.000', 'Pulsa', 'TELKOMSEL', 6385000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-ef2743b2', 'Telkomsel 66.000', 'Pulsa', 'TELKOMSEL', 6517600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-1ce9c4d2', 'Telkomsel 67.000', 'Pulsa', 'TELKOMSEL', 6616200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-8552c5f2', 'Telkomsel 70.000', 'Pulsa', 'TELKOMSEL', 6702500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-bad5b21e', 'Telkomsel 68.000', 'Pulsa', 'TELKOMSEL', 6714800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-7c2c0d70', 'Telkomsel 69.000', 'Pulsa', 'TELKOMSEL', 6813400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-51bdf146', 'Telkomsel 71.000', 'Pulsa', 'TELKOMSEL', 7010600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-227f7697', 'Telkomsel 72.000', 'Pulsa', 'TELKOMSEL', 7109200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-77b381f2', 'Telkomsel 73.000', 'Pulsa', 'TELKOMSEL', 7207800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-9f5a1dc0', 'Telkomsel 75.000', 'Pulsa', 'TELKOMSEL', 7250000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-2c957924', 'Telkomsel 74.000', 'Pulsa', 'TELKOMSEL', 7306400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-7f88a945', 'Telkomsel 76.000', 'Pulsa', 'TELKOMSEL', 7503600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5b7b7922', 'Telkomsel 77.000', 'Pulsa', 'TELKOMSEL', 7602200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-a3fbf15c', 'Telkomsel 78.000', 'Pulsa', 'TELKOMSEL', 7700800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-aad7f9dd', 'Telkomsel 79.000', 'Pulsa', 'TELKOMSEL', 7799400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-666a66f6', 'Telkomsel 80.000', 'Pulsa', 'TELKOMSEL', 7830000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-2d32cc2e', 'Telkomsel 81.000', 'Pulsa', 'TELKOMSEL', 7996600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0271ced1', 'Telkomsel 82.000', 'Pulsa', 'TELKOMSEL', 8095200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-749a28f6', 'Telkomsel 83.000', 'Pulsa', 'TELKOMSEL', 8193800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-daa89e5b', 'Telkomsel 84.000', 'Pulsa', 'TELKOMSEL', 8292400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-b7505f94', 'Telkomsel 85.000', 'Pulsa', 'TELKOMSEL', 8350000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-95e85506', 'Telkomsel 86.000', 'Pulsa', 'TELKOMSEL', 8489600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-145e87ae', 'Telkomsel 87.000', 'Pulsa', 'TELKOMSEL', 8588200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-c10bed7c', 'Telkomsel 88.000', 'Pulsa', 'TELKOMSEL', 8686800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-06ee3838', 'Telkomsel 89.000', 'Pulsa', 'TELKOMSEL', 8785400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-ada8075f', 'Telkomsel 90.000', 'Pulsa', 'TELKOMSEL', 8822500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-cf6c27af', 'Telkomsel 91.000', 'Pulsa', 'TELKOMSEL', 8982600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-e92adf7b', 'Telkomsel 92.000', 'Pulsa', 'TELKOMSEL', 9081200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-19031ed8', 'Telkomsel 93.000', 'Pulsa', 'TELKOMSEL', 9179800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5528e9e5', 'Telkomsel 94.000', 'Pulsa', 'TELKOMSEL', 9278400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5b10f709', 'Telkomsel 95.000', 'Pulsa', 'TELKOMSEL', 9300000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-36c4f9c8', 'Telkomsel 100.000', 'Pulsa', 'TELKOMSEL', 9440000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-460511c9', 'Telkomsel 96.000', 'Pulsa', 'TELKOMSEL', 9475600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-86d7f0e1', 'Telkomsel 97.000', 'Pulsa', 'TELKOMSEL', 9574200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-95c78c13', 'Telkomsel 98.000', 'Pulsa', 'TELKOMSEL', 9672800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  'pulsa-telkomsel-66963be8', 'Telkomsel 99.000', 'Pulsa', 'TELKOMSEL', 9771400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum')
ON CONFLICT (sku_digiflazz) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  provider = EXCLUDED.provider,
  base_price_minor = EXCLUDED.base_price_minor,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  main_category = EXCLUDED.main_category,
  sub_category = EXCLUDED.sub_category,
  product_type = EXCLUDED.product_type,
  updated_at = NOW();
