-- Chunk 007 from batch-001
-- Products: 50

INSERT INTO demo_products (
  sku_digiflazz, name, category, provider, 
  base_price_minor, is_active, metadata,
  main_category, sub_category, product_type
)
VALUES
  ('pulsa-indosat-acaf5b54', 'Indosat 30.000', 'Pulsa', 'INDOSAT', 2840000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum',
  ('pulsa-indosat-e68e12a6', 'Indosat 25.000 + 500 MB', 'Pulsa', 'INDOSAT', 2872500, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Combo Data'),
  ('pulsa-indosat-40bc9b1b', 'Indosat 25.000 + 1 GB', 'Pulsa', 'INDOSAT', 3152500, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Combo Data'),
  ('pulsa-indosat-d5a1729e', 'Indosat 35.000', 'Pulsa', 'INDOSAT', 3492000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-f8a7f3d8', 'Indosat 40.000', 'Pulsa', 'INDOSAT', 3875000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-3c82ea47', 'Indosat 45.000', 'Pulsa', 'INDOSAT', 4429700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-e3467a9f', 'Indosat 50.000', 'Pulsa', 'INDOSAT', 4650000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-5fd9cb46', 'Indosat 55.000', 'Pulsa', 'INDOSAT', 5402700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-51bf1d20', 'Indosat 60.000', 'Pulsa', 'INDOSAT', 5730000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-af9bdae8', 'Indosat 65.000', 'Pulsa', 'INDOSAT', 6375700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-1633762b', 'Indosat 70.000', 'Pulsa', 'INDOSAT', 6680000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-fe623806', 'Indosat 80.000', 'Pulsa', 'INDOSAT', 7664500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-8f144524', 'Indosat 85.000', 'Pulsa', 'INDOSAT', 8293500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-dafcece8', 'Indosat 90.000', 'Pulsa', 'INDOSAT', 8644500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-392d996b', 'Indosat 100.000', 'Pulsa', 'INDOSAT', 9250000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-aa3c241a', 'Indosat 105.000', 'Pulsa', 'INDOSAT', 10267700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-fcd5434a', 'Indosat 115.000', 'Pulsa', 'INDOSAT', 11240700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-465ef40c', 'Indosat 125.000', 'Pulsa', 'INDOSAT', 11824000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-a8da7aed', 'Indosat 150.000', 'Pulsa', 'INDOSAT', 14199600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-2860eb11', 'Indosat 175.000', 'Pulsa', 'INDOSAT', 17117000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-e5bb605e', 'Indosat 200.000', 'Pulsa', 'INDOSAT', 19048700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-a0a249f0', 'Indosat 225.000', 'Pulsa', 'INDOSAT', 22019600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-a502828b', 'Indosat 250.000', 'Pulsa', 'INDOSAT', 24427100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-4c853b27', 'Indosat 300.000', 'Pulsa', 'INDOSAT', 28801000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-e6b2f7dd', 'Indosat 340.000', 'Pulsa', 'INDOSAT', 33156100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-edcca37e', 'Indosat 400.000', 'Pulsa', 'INDOSAT', 38650800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-1431f77e', 'Indosat 500.000', 'Pulsa', 'INDOSAT', 47500000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-0ff3638b', 'Indosat 1.000.000', 'Pulsa', 'INDOSAT', 98540000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-tri-3546941a', 'Three 5.000', 'Pulsa', 'TRI', 449000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-50e02cdd', 'Three 10.000', 'Pulsa', 'TRI', 900000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-d0065c97', 'Three 15.000', 'Pulsa', 'TRI', 1377000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-5be691da', 'Three 20.000', 'Pulsa', 'TRI', 1810000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-efd37dfa', 'Three 25.000', 'Pulsa', 'TRI', 2315000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-024034d6', 'Three 30.000', 'Pulsa', 'TRI', 2820000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-ae382d28', 'Three 35.000', 'Pulsa', 'TRI', 3388000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-8948056e', 'Three 40.000', 'Pulsa', 'TRI', 3770000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-010d1dd4', 'Three 45.000', 'Pulsa', 'TRI', 4082500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-15918977', 'Three 50.000', 'Pulsa', 'TRI', 4617500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-0d5a5c29', 'Three 55.000', 'Pulsa', 'TRI', 4995000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-64907b10', 'Three 60.000', 'Pulsa', 'TRI', 5507500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-17aaef5c', 'Three 65.000', 'Pulsa', 'TRI', 5865600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-dff7cd92', 'Three 70.000', 'Pulsa', 'TRI', 6424500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-fb57d7e0', 'Three 75.000', 'Pulsa', 'TRI', 6780000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-fb0dfa8f', 'Three 80.000', 'Pulsa', 'TRI', 7350000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-5cd0c7ce', 'Three 85.000', 'Pulsa', 'TRI', 7632500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-53c24ca7', 'Three 90.000', 'Pulsa', 'TRI', 8480000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-3c82130d', 'Three 100.000', 'Pulsa', 'TRI', 9200000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-1c2e11d2', 'Three 95.000', 'Pulsa', 'TRI', 9239800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-35fa469e', 'Three 125.000', 'Pulsa', 'TRI', 11649300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  'pulsa-tri-520154c0', 'Three 150.000', 'Pulsa', 'TRI', 13986000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum')
ON CONFLICT (sku_digiflazz) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  provider = EXCLUDED.provider,
  base_price_minor = EXCLUDED.base_price_minor,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  main_category = EXCLUDED.main_category,
  sub_category = EXCLUDED.sub_category,
  product_type = EXCLUDED.product_type,
  updated_at = NOW();
