-- Chunk 001 from batch-001
-- Products: 50

INSERT INTO demo_products (
  sku_digiflazz, name, category, provider, 
  base_price_minor, is_active, metadata,
  main_category, sub_category, product_type
)
VALUES
  (('pulsa-telkomsel-b5323f2e', 'Cek Hutang Pulsa Telkomsel', 'Pulsa', 'TELKOMSEL', 600, true, '{"type":"Cek Hutang","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Cek Hutang'),
  ('pulsa-telkomsel-5c5bcc30', 'Telkomsel 2.000', 'Pulsa', 'TELKOMSEL', 210500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-b8f074c8', 'Telkomsel 3.000', 'Pulsa', 'TELKOMSEL', 335500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-ad871fe0', 'Telkomsel 5.000', 'Pulsa', 'TELKOMSEL', 400000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-d2530434', 'Telkomsel 4.000', 'Pulsa', 'TELKOMSEL', 435500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-65f2397f', 'Telkomsel 6.000', 'Pulsa', 'TELKOMSEL', 644000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-b4d378b5', 'Telkomsel 7.000', 'Pulsa', 'TELKOMSEL', 750000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-54e7bb2a', 'Telkomsel 8.000', 'Pulsa', 'TELKOMSEL', 844000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-f54fb88b', 'Telkomsel 10.000', 'Pulsa', 'TELKOMSEL', 844500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-3d7573ce', 'Telkomsel 9.000', 'Pulsa', 'TELKOMSEL', 944000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-099d586f', 'Telkomsel 11.000', 'Pulsa', 'TELKOMSEL', 1176000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-148cbdee', 'Telkomsel 12.000', 'Pulsa', 'TELKOMSEL', 1276000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-65581f23', 'Telkomsel 13.000', 'Pulsa', 'TELKOMSEL', 1376000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-a84558c6', 'Telkomsel 15.000', 'Pulsa', 'TELKOMSEL', 1400000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-832e6ac9', 'Telkomsel 14.000', 'Pulsa', 'TELKOMSEL', 1476000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-69729e42', 'Telkomsel 16.000', 'Pulsa', 'TELKOMSEL', 1676000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5638057d', 'Telkomsel 17.000', 'Pulsa', 'TELKOMSEL', 1776000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0970ad04', 'Telkomsel 20.000', 'Pulsa', 'TELKOMSEL', 1830000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-e4d62df4', 'Telkomsel 18.000', 'Pulsa', 'TELKOMSEL', 1876000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-776550e7', 'Telkomsel 19.000', 'Pulsa', 'TELKOMSEL', 1973500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-27b6b9d9', 'Telkomsel 21.000', 'Pulsa', 'TELKOMSEL', 2080500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-542086d7', 'Telkomsel 22.000', 'Pulsa', 'TELKOMSEL', 2179500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-800791aa', 'Telkomsel 23.000', 'Pulsa', 'TELKOMSEL', 2278500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-a313eab6', 'Telkomsel 25.000', 'Pulsa', 'TELKOMSEL', 2320000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-fe5fabdc', 'Telkomsel 24.000', 'Pulsa', 'TELKOMSEL', 2377500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-6dc3f5a9', 'Telkomsel 26.000', 'Pulsa', 'TELKOMSEL', 2571100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-6c160c34', 'Telkomsel 27.000', 'Pulsa', 'TELKOMSEL', 2669700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-92b85f0f', 'Telkomsel 28.000', 'Pulsa', 'TELKOMSEL', 2768300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-953c14d1', 'Telkomsel 30.000', 'Pulsa', 'TELKOMSEL', 2777500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-6c280806', 'Telkomsel 29.000', 'Pulsa', 'TELKOMSEL', 2866900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-fe310b99', 'Telkomsel 31.000', 'Pulsa', 'TELKOMSEL', 3064100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-34f5a6af', 'Telkomsel 32.000', 'Pulsa', 'TELKOMSEL', 3164100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-4f0d2f8b', 'Telkomsel 33.000', 'Pulsa', 'TELKOMSEL', 3262900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-c3b62465', 'Telkomsel 35.000', 'Pulsa', 'TELKOMSEL', 3277500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-b570d77f', 'Telkomsel 34.000', 'Pulsa', 'TELKOMSEL', 3361700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-e4d8562f', 'Telkomsel 36.000', 'Pulsa', 'TELKOMSEL', 3552100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-7b8670aa', 'Telkomsel 37.000', 'Pulsa', 'TELKOMSEL', 3650700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-53178a6b', 'Telkomsel 38.000', 'Pulsa', 'TELKOMSEL', 3749300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-74e08310', 'Telkomsel 39.000', 'Pulsa', 'TELKOMSEL', 3847900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-7e1102e0', 'Telkomsel 40.000', 'Pulsa', 'TELKOMSEL', 3865000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-07b2ec55', 'Telkomsel 41.000', 'Pulsa', 'TELKOMSEL', 4047600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-cf5c5ae5', 'Telkomsel 42.000', 'Pulsa', 'TELKOMSEL', 4143700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-a4a7539b', 'Telkomsel 43.000', 'Pulsa', 'TELKOMSEL', 4244800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-13101bc6', 'Telkomsel 44.000', 'Pulsa', 'TELKOMSEL', 4340900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-2888d34b', 'Telkomsel 46.000', 'Pulsa', 'TELKOMSEL', 4372500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-68fb596c', 'Telkomsel 45.000', 'Pulsa', 'TELKOMSEL', 4417500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-26c10d93', 'Telkomsel 47.000', 'Pulsa', 'TELKOMSEL', 4636700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-460150d4', 'Telkomsel 50.000', 'Pulsa', 'TELKOMSEL', 4670000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-20a6b9ad', 'Telkomsel 48.000', 'Pulsa', 'TELKOMSEL', 4735300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  'pulsa-telkomsel-8af057cd', 'Telkomsel 49.000', 'Pulsa', 'TELKOMSEL', 4833900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum')
ON CONFLICT (sku_digiflazz) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  provider = EXCLUDED.provider,
  base_price_minor = EXCLUDED.base_price_minor,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  main_category = EXCLUDED.main_category,
  sub_category = EXCLUDED.sub_category,
  product_type = EXCLUDED.product_type,
  updated_at = NOW();
