-- Chunk 006 from batch-001
-- Products: 50

INSERT INTO demo_products (
  sku_digiflazz, name, category, provider, 
  base_price_minor, is_active, metadata,
  main_category, sub_category, product_type
)
VALUES
  ('pulsa-telkomsel-f786d354', 'Telkomsel 287.000', 'Pulsa', 'TELKOMSEL', 28334400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum',
  ('pulsa-telkomsel-0896a656', 'Telkomsel 288.000', 'Pulsa', 'TELKOMSEL', 28433100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-a5e90296', 'Telkomsel 289.000', 'Pulsa', 'TELKOMSEL', 28531800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-3f3a78de', 'Telkomsel 290.000', 'Pulsa', 'TELKOMSEL', 28630500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-1b96d984', 'Telkomsel 291.000', 'Pulsa', 'TELKOMSEL', 28729200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-03b4f9a8', 'Telkomsel 292.000', 'Pulsa', 'TELKOMSEL', 28827900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-ba1c7df8', 'Telkomsel 293.000', 'Pulsa', 'TELKOMSEL', 28926600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-997b1757', 'Telkomsel 300.000', 'Pulsa', 'TELKOMSEL', 28962500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-f478d27e', 'Telkomsel 294.000', 'Pulsa', 'TELKOMSEL', 29025300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-f07fb9e4', 'Telkomsel 295.000', 'Pulsa', 'TELKOMSEL', 29124000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-49f7a25c', 'Telkomsel 296.000', 'Pulsa', 'TELKOMSEL', 29222700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0871d131', 'Telkomsel 297.000', 'Pulsa', 'TELKOMSEL', 29321400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-8dfe0aad', 'Telkomsel 298.000', 'Pulsa', 'TELKOMSEL', 29420100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5b0ea2cb', 'Telkomsel 299.000', 'Pulsa', 'TELKOMSEL', 29518800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-2b067633', 'Telkomsel 325.000', 'Pulsa', 'TELKOMSEL', 32220000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0ab064e3', 'Telkomsel 350.000', 'Pulsa', 'TELKOMSEL', 34582500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-3a034cce', 'Telkomsel 375.000', 'Pulsa', 'TELKOMSEL', 37200000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-91606c3f', 'Telkomsel 400.000', 'Pulsa', 'TELKOMSEL', 39602500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-fc87831f', 'Telkomsel 425.000', 'Pulsa', 'TELKOMSEL', 41992500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5555e773', 'Telkomsel 450.000', 'Pulsa', 'TELKOMSEL', 44462500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-17403f96', 'Telkomsel 475.000', 'Pulsa', 'TELKOMSEL', 46932500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5d4dbcd4', 'Telkomsel 500.000', 'Pulsa', 'TELKOMSEL', 49402500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0d5ec98c', 'Telkomsel 1.000.000', 'Pulsa', 'TELKOMSEL', 98802500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-xl-ff9add7e', 'Xl 5.000', 'Pulsa', 'XL', 450500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-27188481', 'Xl 10.000', 'Pulsa', 'XL', 930000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-c0dd3f21', 'Xl 15.000', 'Pulsa', 'XL', 1390000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-3db1c222', 'Xl 25.000', 'Pulsa', 'XL', 2330000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-deb27b3e', 'XL 30.000', 'Pulsa', 'XL', 2850000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-4f3c5cd9', 'XL 40.000', 'Pulsa', 'XL', 3815000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-524b8a25', 'Xl 50.000', 'Pulsa', 'XL', 4720000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-428171ef', 'Xl 60.000', 'Pulsa', 'XL', 5900000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-bd7b96ab', 'Xl 70.000', 'Pulsa', 'XL', 6922500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-8c3b41a7', 'Xl 80.000', 'Pulsa', 'XL', 7900000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-1f4c8a60', 'Xl 90.000', 'Pulsa', 'XL', 8925000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-1ad96cff', 'Xl 100.000', 'Pulsa', 'XL', 9650000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-ec43977d', 'Xl 150.000', 'Pulsa', 'XL', 14962500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-0de2d331', 'Xl 200.000', 'Pulsa', 'XL', 19917500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-703c414a', 'Xl 300.000', 'Pulsa', 'XL', 29887500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-541df085', 'Xl 500.000', 'Pulsa', 'XL', 49679500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-xl-ae9c0278', 'Xl 1.000.000', 'Pulsa', 'XL', 99547000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}', 'Pulsa', 'XL', 'Umum'),
  ('pulsa-indosat-5d339beb', 'Indosat 5.000', 'Pulsa', 'INDOSAT', 479000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-f03cc800', 'Indosat 10.000', 'Pulsa', 'INDOSAT', 975000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-1816b8ed', 'Indosat 12.000', 'Pulsa', 'INDOSAT', 1146000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-27f96c39', 'Indosat 15.000', 'Pulsa', 'INDOSAT', 1395000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-31d9c7d6', 'Indosat 12.000 + 1 GB', 'Pulsa', 'INDOSAT', 1901000, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Combo Data'),
  ('pulsa-indosat-d653db74', 'Indosat 20.000', 'Pulsa', 'INDOSAT', 1905000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-b42b1364', 'Indosat 15.000 + 1 GB', 'Pulsa', 'INDOSAT', 2251000, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Combo Data'),
  ('pulsa-indosat-968bb613', 'Indosat 25.000', 'Pulsa', 'INDOSAT', 2305000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Umum'),
  ('pulsa-indosat-4ddb999a', 'Indosat 20.000 + 500 MB', 'Pulsa', 'INDOSAT', 2391000, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Combo Data'),
  'pulsa-indosat-1aea8595', 'Indosat 20.000 + 1 GB', 'Pulsa', 'INDOSAT', 2652500, true, '{"type":"Combo Data","description":"Semua Kuota 24 jam, masa aktif 30 hari, bisa digabung dengan paket data yang sudah ada","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/indosat.png"}', 'Pulsa', 'INDOSAT', 'Combo Data')
ON CONFLICT (sku_digiflazz) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  provider = EXCLUDED.provider,
  base_price_minor = EXCLUDED.base_price_minor,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  main_category = EXCLUDED.main_category,
  sub_category = EXCLUDED.sub_category,
  product_type = EXCLUDED.product_type,
  updated_at = NOW();
