-- Chunk 004 from batch-001
-- Products: 50

INSERT INTO demo_products (
  sku_digiflazz, name, category, provider, 
  base_price_minor, is_active, metadata,
  main_category, sub_category, product_type
)
VALUES
  ('pulsa-telkomsel-53e8a6da', 'Telkomsel 151.000', 'Pulsa', 'TELKOMSEL', 14911200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum',
  ('pulsa-telkomsel-60987d77', 'Telkomsel 152.000', 'Pulsa', 'TELKOMSEL', 15009900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-b6e4ea14', 'Telkomsel 153.000', 'Pulsa', 'TELKOMSEL', 15108600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-16a45003', 'Telkomsel 154.000', 'Pulsa', 'TELKOMSEL', 15207300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-26b97fa5', 'Telkomsel 155.000', 'Pulsa', 'TELKOMSEL', 15306000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-e5baa43a', 'Telkomsel 156.000', 'Pulsa', 'TELKOMSEL', 15404700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-4018e972', 'Telkomsel 157.000', 'Pulsa', 'TELKOMSEL', 15503400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-89d92c75', 'Telkomsel 158.000', 'Pulsa', 'TELKOMSEL', 15602100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-bd962bfa', 'Telkomsel 159.000', 'Pulsa', 'TELKOMSEL', 15700800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-6f042559', 'Telkomsel 160.000', 'Pulsa', 'TELKOMSEL', 15799500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-24b8417c', 'Telkomsel 161.000', 'Pulsa', 'TELKOMSEL', 15898200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0cbbc723', 'Telkomsel 162.000', 'Pulsa', 'TELKOMSEL', 15996900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-e5c6ae1d', 'Telkomsel 163.000', 'Pulsa', 'TELKOMSEL', 16095600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-8b70671d', 'Telkomsel 164.000', 'Pulsa', 'TELKOMSEL', 16194300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-df685371', 'Telkomsel 165.000', 'Pulsa', 'TELKOMSEL', 16293000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-085beb49', 'Telkomsel 166.000', 'Pulsa', 'TELKOMSEL', 16391700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-fb033072', 'Telkomsel 167.000', 'Pulsa', 'TELKOMSEL', 16490400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-066fdc67', 'Telkomsel 168.000', 'Pulsa', 'TELKOMSEL', 16589100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-ae491de9', 'Telkomsel 169.000', 'Pulsa', 'TELKOMSEL', 16687800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-fe8c8a86', 'Telkomsel 170.000', 'Pulsa', 'TELKOMSEL', 16786500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-672431f5', 'Telkomsel 171.000', 'Pulsa', 'TELKOMSEL', 16885200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-fb86b139', 'Telkomsel 172.000', 'Pulsa', 'TELKOMSEL', 16983900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-e31f3313', 'Telkomsel 173.000', 'Pulsa', 'TELKOMSEL', 17082600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-31c2bae0', 'Telkomsel 174.000', 'Pulsa', 'TELKOMSEL', 17181300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-583f0ef3', 'Telkomsel 175.000', 'Pulsa', 'TELKOMSEL', 17280000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-904439b2', 'Telkomsel 176.000', 'Pulsa', 'TELKOMSEL', 17378700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-e83f68c4', 'Telkomsel 177.000', 'Pulsa', 'TELKOMSEL', 17477400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-3ddcb5fa', 'Telkomsel 178.000', 'Pulsa', 'TELKOMSEL', 17576100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-7c0fb659', 'Telkomsel 179.000', 'Pulsa', 'TELKOMSEL', 17674800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-f97c9e07', 'Telkomsel 180.000', 'Pulsa', 'TELKOMSEL', 17773500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-de1638a3', 'Telkomsel 181.000', 'Pulsa', 'TELKOMSEL', 17872200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-88e66bf0', 'Telkomsel 182.000', 'Pulsa', 'TELKOMSEL', 17970900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-f9ed8ab9', 'Telkomsel 183.000', 'Pulsa', 'TELKOMSEL', 18069600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-c5f2fe57', 'Telkomsel 184.000', 'Pulsa', 'TELKOMSEL', 18168300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0977774e', 'Telkomsel 185.000', 'Pulsa', 'TELKOMSEL', 18267000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5ff0456d', 'Telkomsel 186.000', 'Pulsa', 'TELKOMSEL', 18365700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-9c2c3b26', 'Telkomsel 187.000', 'Pulsa', 'TELKOMSEL', 18464400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5b7a347c', 'Telkomsel 188.000', 'Pulsa', 'TELKOMSEL', 18563100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-6d13199e', 'Telkomsel 189.000', 'Pulsa', 'TELKOMSEL', 18661800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-97ad546a', 'Telkomsel 190.000', 'Pulsa', 'TELKOMSEL', 18758000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-bc4eb97d', 'Telkomsel 191.000', 'Pulsa', 'TELKOMSEL', 18859200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-9a4f76cc', 'Telkomsel 192.000', 'Pulsa', 'TELKOMSEL', 18957900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-5cc423ff', 'Telkomsel 193.000', 'Pulsa', 'TELKOMSEL', 19056600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-be814cdf', 'Telkomsel 194.000', 'Pulsa', 'TELKOMSEL', 19155300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-a983140a', 'Telkomsel 195.000', 'Pulsa', 'TELKOMSEL', 19254000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-0dceeef4', 'Telkomsel 200.000', 'Pulsa', 'TELKOMSEL', 19312500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-93869e03', 'Telkomsel 196.000', 'Pulsa', 'TELKOMSEL', 19352700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-70ff0353', 'Telkomsel 197.000', 'Pulsa', 'TELKOMSEL', 19451400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  ('pulsa-telkomsel-c8f057c8', 'Telkomsel 198.000', 'Pulsa', 'TELKOMSEL', 19550100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum'),
  'pulsa-telkomsel-100f5c5a', 'Telkomsel 199.000', 'Pulsa', 'TELKOMSEL', 19648800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}', 'Pulsa', 'TELKOMSEL', 'Umum')
ON CONFLICT (sku_digiflazz) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  provider = EXCLUDED.provider,
  base_price_minor = EXCLUDED.base_price_minor,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  main_category = EXCLUDED.main_category,
  sub_category = EXCLUDED.sub_category,
  product_type = EXCLUDED.product_type,
  updated_at = NOW();
