-- Chunk 008 from batch-001
-- Products: 50

INSERT INTO demo_products (
  sku_digiflazz, name, category, provider, 
  base_price_minor, is_active, metadata,
  main_category, sub_category, product_type
)
VALUES
  ('pulsa-tri-01cd08f8', 'Three 200.000', 'Pulsa', 'TRI', 18761000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum',
  ('pulsa-tri-c4dc136a', 'Three 250.000', 'Pulsa', 'TRI', 23876000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-111e03ff', 'Three 300.000', 'Pulsa', 'TRI', 27790000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-312f1ed4', 'Three 400.000', 'Pulsa', 'TRI', 38889000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-5fa89086', 'Three 500.000', 'Pulsa', 'TRI', 46851300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-tri-3a502fcc', 'Three 1.000.000', 'Pulsa', 'TRI', 98000000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}', 'Pulsa', 'TRI', 'Umum'),
  ('pulsa-smartfren-686caed0', 'Smartfren 2.000', 'Pulsa', 'SMARTFREN', 194900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-16d8de8c', 'Smartfren 3.000', 'Pulsa', 'SMARTFREN', 291500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-42fd55cc', 'Smartfren 4.000', 'Pulsa', 'SMARTFREN', 388500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-5814f5ea', 'Smartfren 5.000', 'Pulsa', 'SMARTFREN', 420000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-294e3ae7', 'Smartfren 6.000', 'Pulsa', 'SMARTFREN', 582500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-dd3ad5e3', 'Smartfren 7.000', 'Pulsa', 'SMARTFREN', 677200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-e017503b', 'Smartfren 8.000', 'Pulsa', 'SMARTFREN', 773700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-02a0747c', 'Smartfren 9.000', 'Pulsa', 'SMARTFREN', 873500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-f4363fa4', 'Smartfren 10.000', 'Pulsa', 'SMARTFREN', 890000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-75500879', 'Smartfren 11.000', 'Pulsa', 'SMARTFREN', 1068000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-b38d2669', 'Smartfren 12.000', 'Pulsa', 'SMARTFREN', 1176600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-17a5179b', 'Smartfren 15.000', 'Pulsa', 'SMARTFREN', 1399000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-f692e27a', 'Smartfren 20.000', 'Pulsa', 'SMARTFREN', 1840000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-817cbd7b', 'Smartfren 25.000', 'Pulsa', 'SMARTFREN', 2290000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-0e3be1dc', 'Smartfren 30.000', 'Pulsa', 'SMARTFREN', 2817500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-231b1a97', 'Smartfren 35.000', 'Pulsa', 'SMARTFREN', 3277500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-53663a11', 'Smartfren 40.000', 'Pulsa', 'SMARTFREN', 3775000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-c2a90844', 'Smartfren 45.000', 'Pulsa', 'SMARTFREN', 4199000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-5fbbf5ca', 'Smartfren 50.000', 'Pulsa', 'SMARTFREN', 4675000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-23961b50', 'Smartfren 55.000', 'Pulsa', 'SMARTFREN', 5160000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-59f347e9', 'Smartfren 60.000', 'Pulsa', 'SMARTFREN', 5655000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-5e748ac3', 'Smartfren 65.000', 'Pulsa', 'SMARTFREN', 6180000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-101c7ebf', 'Smartfren 70.000', 'Pulsa', 'SMARTFREN', 6700000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-979d0d8b', 'Smartfren 72.000', 'Pulsa', 'SMARTFREN', 7052500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-ba51076c', 'Smartfren 75.000', 'Pulsa', 'SMARTFREN', 7175000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-59462bea', 'Smartfren 80.000', 'Pulsa', 'SMARTFREN', 7495000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-292933c2', 'Smartfren 85.000', 'Pulsa', 'SMARTFREN', 8090000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-f7b42c2a', 'Smartfren 90.000', 'Pulsa', 'SMARTFREN', 8482500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-64609c3c', 'Smartfren 95.000', 'Pulsa', 'SMARTFREN', 9065000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-47a37285', 'Smartfren 100.000', 'Pulsa', 'SMARTFREN', 9370000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-fe6d17ad', 'Smartfren 125.000', 'Pulsa', 'SMARTFREN', 12215500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-0bf0c254', 'Smartfren 150.000', 'Pulsa', 'SMARTFREN', 14624300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-d0977610', 'Smartfren 200.000', 'Pulsa', 'SMARTFREN', 19497500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-8ef6189f', 'Smartfren 300.000', 'Pulsa', 'SMARTFREN', 24722500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-d8702a2b', 'Smartfren 250.000', 'Pulsa', 'SMARTFREN', 24907500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-d5f0a0a8', 'Smartfren 400.000', 'Pulsa', 'SMARTFREN', 38853200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-2ed02452', 'Smartfren 500.000', 'Pulsa', 'SMARTFREN', 48747500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-cf257fde', 'Smartfren 600.000', 'Pulsa', 'SMARTFREN', 58902500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-6b1b9021', 'Smartfren 700.000', 'Pulsa', 'SMARTFREN', 68782500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-d7d16f00', 'Smartfren 800.000', 'Pulsa', 'SMARTFREN', 78582500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-26121c97', 'Smartfren 900.000', 'Pulsa', 'SMARTFREN', 88582500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-smartfren-7b06e69a', 'Smartfren 1.000.000', 'Pulsa', 'SMARTFREN', 97607500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/smart.png"}', 'Pulsa', 'SMARTFREN', 'Umum'),
  ('pulsa-axis-99500c59', 'Axis 5.000', 'Pulsa', 'AXIS', 440000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}', 'Pulsa', 'AXIS', 'Umum'),
  'pulsa-axis-38e3fa9f', 'Axis 10.000', 'Pulsa', 'AXIS', 940000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/axis.png"}', 'Pulsa', 'AXIS', 'Umum')
ON CONFLICT (sku_digiflazz) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  provider = EXCLUDED.provider,
  base_price_minor = EXCLUDED.base_price_minor,
  is_active = EXCLUDED.is_active,
  metadata = EXCLUDED.metadata,
  main_category = EXCLUDED.main_category,
  sub_category = EXCLUDED.sub_category,
  product_type = EXCLUDED.product_type,
  updated_at = NOW();
