-- Mini Batch 41
-- Chunks: import-batch-019-chunk-003.sql to import-batch-019-chunk-007.sql
-- Products: ~250

INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-02d8b104', 'Telkomsel 16.000', 'Pulsa', 'TELKOMSEL', 1676000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-19adc975', 'Telkomsel 17.000', 'Pulsa', 'TELKOMSEL', 1776000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9cd9a6c0', 'Telkomsel 20.000', 'Pulsa', 'TELKOMSEL', 1830000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4e67740e', 'Telkomsel 18.000', 'Pulsa', 'TELKOMSEL', 1876000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-848a3616', 'Telkomsel 19.000', 'Pulsa', 'TELKOMSEL', 1973500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ec10e4e7', 'Telkomsel 21.000', 'Pulsa', 'TELKOMSEL', 2080500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-07ef8efd', 'Telkomsel 22.000', 'Pulsa', 'TELKOMSEL', 2179500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4dddc8a9', 'Telkomsel 23.000', 'Pulsa', 'TELKOMSEL', 2278500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0b9aba13', 'Telkomsel 25.000', 'Pulsa', 'TELKOMSEL', 2320000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-af3add0b', 'Telkomsel 24.000', 'Pulsa', 'TELKOMSEL', 2377500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8e0eb499', 'Telkomsel 26.000', 'Pulsa', 'TELKOMSEL', 2571100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ada0af72', 'Telkomsel 27.000', 'Pulsa', 'TELKOMSEL', 2669700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d3d9fbaa', 'Telkomsel 28.000', 'Pulsa', 'TELKOMSEL', 2768300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9005dcad', 'Telkomsel 30.000', 'Pulsa', 'TELKOMSEL', 2777500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fe3e550f', 'Telkomsel 29.000', 'Pulsa', 'TELKOMSEL', 2866900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9e925596', 'Telkomsel 31.000', 'Pulsa', 'TELKOMSEL', 3064100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5822cd0c', 'Telkomsel 32.000', 'Pulsa', 'TELKOMSEL', 3164100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e59dee31', 'Telkomsel 33.000', 'Pulsa', 'TELKOMSEL', 3262900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5406d2ae', 'Telkomsel 35.000', 'Pulsa', 'TELKOMSEL', 3277500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8d123286', 'Telkomsel 34.000', 'Pulsa', 'TELKOMSEL', 3361700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-44e25053', 'Telkomsel 36.000', 'Pulsa', 'TELKOMSEL', 3552100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3ed42e74', 'Telkomsel 37.000', 'Pulsa', 'TELKOMSEL', 3650700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-676adda3', 'Telkomsel 38.000', 'Pulsa', 'TELKOMSEL', 3749300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-389d7684', 'Telkomsel 39.000', 'Pulsa', 'TELKOMSEL', 3847900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1e6b755f', 'Telkomsel 40.000', 'Pulsa', 'TELKOMSEL', 3865000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-45923bfb', 'Telkomsel 41.000', 'Pulsa', 'TELKOMSEL', 4047600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e43b938e', 'Telkomsel 42.000', 'Pulsa', 'TELKOMSEL', 4143700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f6cbea37', 'Telkomsel 43.000', 'Pulsa', 'TELKOMSEL', 4244800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4c339188', 'Telkomsel 44.000', 'Pulsa', 'TELKOMSEL', 4340900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9f766634', 'Telkomsel 46.000', 'Pulsa', 'TELKOMSEL', 4372500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6c49ef35', 'Telkomsel 45.000', 'Pulsa', 'TELKOMSEL', 4417500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a293324e', 'Telkomsel 47.000', 'Pulsa', 'TELKOMSEL', 4636700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-46d59af4', 'Telkomsel 50.000', 'Pulsa', 'TELKOMSEL', 4670000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b960cfdd', 'Telkomsel 48.000', 'Pulsa', 'TELKOMSEL', 4735300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-efe4c85a', 'Telkomsel 49.000', 'Pulsa', 'TELKOMSEL', 4833900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3da8024a', 'Telkomsel 51.000', 'Pulsa', 'TELKOMSEL', 5038600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1ae0d821', 'Telkomsel 52.000', 'Pulsa', 'TELKOMSEL', 5137200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1e64dd9b', 'Telkomsel 53.000', 'Pulsa', 'TELKOMSEL', 5235800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-22feb1ea', 'Telkomsel 54.000', 'Pulsa', 'TELKOMSEL', 5334400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-eee6c6c9', 'Telkomsel 55.000', 'Pulsa', 'TELKOMSEL', 5400000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-20c7fdb2', 'Telkomsel 56.000', 'Pulsa', 'TELKOMSEL', 5531600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-90d679c3', 'Telkomsel 57.000', 'Pulsa', 'TELKOMSEL', 5630200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7c3acb9c', 'Telkomsel 58.000', 'Pulsa', 'TELKOMSEL', 5728800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-09811d0d', 'Telkomsel 59.000', 'Pulsa', 'TELKOMSEL', 5827400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e94b62f9', 'Telkomsel 60.000', 'Pulsa', 'TELKOMSEL', 5835000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d862ea58', 'Telkomsel 61.000', 'Pulsa', 'TELKOMSEL', 6024600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4ecf2cab', 'Telkomsel 62.000', 'Pulsa', 'TELKOMSEL', 6123200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9bb1557b', 'Telkomsel 63.000', 'Pulsa', 'TELKOMSEL', 6221800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-da47aee3', 'Telkomsel 64.000', 'Pulsa', 'TELKOMSEL', 6320400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-524cf027', 'Telkomsel 65.000', 'Pulsa', 'TELKOMSEL', 6385000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-71fecd67', 'Telkomsel 66.000', 'Pulsa', 'TELKOMSEL', 6517600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a90f2aea', 'Telkomsel 67.000', 'Pulsa', 'TELKOMSEL', 6616200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ec8d84c3', 'Telkomsel 70.000', 'Pulsa', 'TELKOMSEL', 6702500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f2a241a6', 'Telkomsel 68.000', 'Pulsa', 'TELKOMSEL', 6714800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-891ed91b', 'Telkomsel 69.000', 'Pulsa', 'TELKOMSEL', 6813400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9f5f75fb', 'Telkomsel 71.000', 'Pulsa', 'TELKOMSEL', 7010600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-946bd9a4', 'Telkomsel 72.000', 'Pulsa', 'TELKOMSEL', 7109200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b938ef88', 'Telkomsel 73.000', 'Pulsa', 'TELKOMSEL', 7207800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0997eced', 'Telkomsel 75.000', 'Pulsa', 'TELKOMSEL', 7250000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-52c80045', 'Telkomsel 74.000', 'Pulsa', 'TELKOMSEL', 7306400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8c07b85a', 'Telkomsel 76.000', 'Pulsa', 'TELKOMSEL', 7503600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-06867196', 'Telkomsel 77.000', 'Pulsa', 'TELKOMSEL', 7602200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-02ac9f1b', 'Telkomsel 78.000', 'Pulsa', 'TELKOMSEL', 7700800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6e4acd72', 'Telkomsel 79.000', 'Pulsa', 'TELKOMSEL', 7799400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f6300dbc', 'Telkomsel 80.000', 'Pulsa', 'TELKOMSEL', 7830000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5b861cb6', 'Telkomsel 81.000', 'Pulsa', 'TELKOMSEL', 7996600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1b2b5dda', 'Telkomsel 82.000', 'Pulsa', 'TELKOMSEL', 8095200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6b85c9b8', 'Telkomsel 83.000', 'Pulsa', 'TELKOMSEL', 8193800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8ace105d', 'Telkomsel 84.000', 'Pulsa', 'TELKOMSEL', 8292400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e069b52a', 'Telkomsel 85.000', 'Pulsa', 'TELKOMSEL', 8350000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7aa82086', 'Telkomsel 86.000', 'Pulsa', 'TELKOMSEL', 8489600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-75f45e25', 'Telkomsel 87.000', 'Pulsa', 'TELKOMSEL', 8588200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6fd9c2c5', 'Telkomsel 88.000', 'Pulsa', 'TELKOMSEL', 8686800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ce56d394', 'Telkomsel 89.000', 'Pulsa', 'TELKOMSEL', 8785400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f3fd2349', 'Telkomsel 90.000', 'Pulsa', 'TELKOMSEL', 8822500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-de3f9b87', 'Telkomsel 91.000', 'Pulsa', 'TELKOMSEL', 8982600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6685ee71', 'Telkomsel 92.000', 'Pulsa', 'TELKOMSEL', 9081200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c6ec600c', 'Telkomsel 93.000', 'Pulsa', 'TELKOMSEL', 9179800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fe128a1d', 'Telkomsel 94.000', 'Pulsa', 'TELKOMSEL', 9278400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5106fdfa', 'Telkomsel 95.000', 'Pulsa', 'TELKOMSEL', 9300000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-63f9098b', 'Telkomsel 100.000', 'Pulsa', 'TELKOMSEL', 9440000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-49ec0a0b', 'Telkomsel 96.000', 'Pulsa', 'TELKOMSEL', 9475600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3872865c', 'Telkomsel 97.000', 'Pulsa', 'TELKOMSEL', 9574200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-493db445', 'Telkomsel 98.000', 'Pulsa', 'TELKOMSEL', 9672800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a0a085dc', 'Telkomsel 99.000', 'Pulsa', 'TELKOMSEL', 9771400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ac565170', 'Telkomsel 101.000', 'Pulsa', 'TELKOMSEL', 9976200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ca192ebf', 'Telkomsel 102.000', 'Pulsa', 'TELKOMSEL', 10074900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8757ecb4', 'Telkomsel 103.000', 'Pulsa', 'TELKOMSEL', 10173600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4d160662', 'Telkomsel 104.000', 'Pulsa', 'TELKOMSEL', 10272300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-98db9e4a', 'Telkomsel 105.000', 'Pulsa', 'TELKOMSEL', 10371000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-78b49687', 'Telkomsel 106.000', 'Pulsa', 'TELKOMSEL', 10469700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8027e4f8', 'Telkomsel 107.000', 'Pulsa', 'TELKOMSEL', 10568400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-36508c1e', 'Telkomsel 108.000', 'Pulsa', 'TELKOMSEL', 10667100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ec6eaedc', 'Telkomsel 109.000', 'Pulsa', 'TELKOMSEL', 10765800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-75b061cd', 'Telkomsel 110.000', 'Pulsa', 'TELKOMSEL', 10864500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d0c63838', 'Telkomsel 111.000', 'Pulsa', 'TELKOMSEL', 10963200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b43df76a', 'Telkomsel 112.000', 'Pulsa', 'TELKOMSEL', 11061900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-798fe424', 'Telkomsel 113.000', 'Pulsa', 'TELKOMSEL', 11160600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d4763595', 'Telkomsel 114.000', 'Pulsa', 'TELKOMSEL', 11259300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9aa08207', 'Telkomsel 115.000', 'Pulsa', 'TELKOMSEL', 11358000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-c843412b', 'Telkomsel 116.000', 'Pulsa', 'TELKOMSEL', 11456700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5d04fd93', 'Telkomsel 117.000', 'Pulsa', 'TELKOMSEL', 11555400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fdf1674f', 'Telkomsel 118.000', 'Pulsa', 'TELKOMSEL', 11654100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1e1ccbc7', 'Telkomsel 119.000', 'Pulsa', 'TELKOMSEL', 11752800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8a51ee42', 'Telkomsel 120.000', 'Pulsa', 'TELKOMSEL', 11851500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-29e6572f', 'Telkomsel 121.000', 'Pulsa', 'TELKOMSEL', 11950200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5f1f8b41', 'Telkomsel 122.000', 'Pulsa', 'TELKOMSEL', 12048900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e7b9c261', 'Telkomsel 123.000', 'Pulsa', 'TELKOMSEL', 12147600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7d0b530f', 'Telkomsel 124.000', 'Pulsa', 'TELKOMSEL', 12246300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-40e0c893', 'Telkomsel 125.000', 'Pulsa', 'TELKOMSEL', 12345000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-22bd21cd', 'Telkomsel 126.000', 'Pulsa', 'TELKOMSEL', 12443700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8c4dc319', 'Telkomsel 127.000', 'Pulsa', 'TELKOMSEL', 12542400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4aa69d73', 'Telkomsel 128.000', 'Pulsa', 'TELKOMSEL', 12641100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d6d8c4d5', 'Telkomsel 129.000', 'Pulsa', 'TELKOMSEL', 12739800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f9be86a3', 'Telkomsel 130.000', 'Pulsa', 'TELKOMSEL', 12838500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a9fa6bb5', 'Telkomsel 131.000', 'Pulsa', 'TELKOMSEL', 12937200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-160c1565', 'Telkomsel 132.000', 'Pulsa', 'TELKOMSEL', 13035900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-46e52a94', 'Telkomsel 133.000', 'Pulsa', 'TELKOMSEL', 13134600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7d5df007', 'Telkomsel 134.000', 'Pulsa', 'TELKOMSEL', 13233300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-72698a65', 'Telkomsel 135.000', 'Pulsa', 'TELKOMSEL', 13332000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-11399d58', 'Telkomsel 136.000', 'Pulsa', 'TELKOMSEL', 13430700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2594e70e', 'Telkomsel 137.000', 'Pulsa', 'TELKOMSEL', 13529400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6fc3414b', 'Telkomsel 138.000', 'Pulsa', 'TELKOMSEL', 13628100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-48eb842f', 'Telkomsel 139.000', 'Pulsa', 'TELKOMSEL', 13726800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-5727ddab', 'Telkomsel 140.000', 'Pulsa', 'TELKOMSEL', 13825500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8d589760', 'Telkomsel 141.000', 'Pulsa', 'TELKOMSEL', 13924200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7fcc1794', 'Telkomsel 142.000', 'Pulsa', 'TELKOMSEL', 14022900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9c14dae4', 'Telkomsel 143.000', 'Pulsa', 'TELKOMSEL', 14121600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e26014bf', 'Telkomsel 144.000', 'Pulsa', 'TELKOMSEL', 14220300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-29cf5683', 'Telkomsel 145.000', 'Pulsa', 'TELKOMSEL', 14319000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ef70c268', 'Telkomsel 146.000', 'Pulsa', 'TELKOMSEL', 14417700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-51a58d2f', 'Telkomsel 150.000', 'Pulsa', 'TELKOMSEL', 14482500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fcc42066', 'Telkomsel 147.000', 'Pulsa', 'TELKOMSEL', 14516400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b5b0aa79', 'Telkomsel 148.000', 'Pulsa', 'TELKOMSEL', 14615100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f8ce584c', 'Telkomsel 149.000', 'Pulsa', 'TELKOMSEL', 14713800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d67755c5', 'Telkomsel 151.000', 'Pulsa', 'TELKOMSEL', 14911200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9c0c2271', 'Telkomsel 152.000', 'Pulsa', 'TELKOMSEL', 15009900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-548a5d1c', 'Telkomsel 153.000', 'Pulsa', 'TELKOMSEL', 15108600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-cc8a4446', 'Telkomsel 154.000', 'Pulsa', 'TELKOMSEL', 15207300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4c288433', 'Telkomsel 155.000', 'Pulsa', 'TELKOMSEL', 15306000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fea9c7bc', 'Telkomsel 156.000', 'Pulsa', 'TELKOMSEL', 15404700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-816d62a8', 'Telkomsel 157.000', 'Pulsa', 'TELKOMSEL', 15503400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-65c77d93', 'Telkomsel 158.000', 'Pulsa', 'TELKOMSEL', 15602100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-92f25b00', 'Telkomsel 159.000', 'Pulsa', 'TELKOMSEL', 15700800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f3e98e48', 'Telkomsel 160.000', 'Pulsa', 'TELKOMSEL', 15799500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8e2759e8', 'Telkomsel 161.000', 'Pulsa', 'TELKOMSEL', 15898200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0ceb186a', 'Telkomsel 162.000', 'Pulsa', 'TELKOMSEL', 15996900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-59df239d', 'Telkomsel 163.000', 'Pulsa', 'TELKOMSEL', 16095600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-7e06621d', 'Telkomsel 164.000', 'Pulsa', 'TELKOMSEL', 16194300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3749f355', 'Telkomsel 165.000', 'Pulsa', 'TELKOMSEL', 16293000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-7dc0f5bf', 'Telkomsel 166.000', 'Pulsa', 'TELKOMSEL', 16391700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c0a7e134', 'Telkomsel 167.000', 'Pulsa', 'TELKOMSEL', 16490400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c2189394', 'Telkomsel 168.000', 'Pulsa', 'TELKOMSEL', 16589100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-642e0ed9', 'Telkomsel 169.000', 'Pulsa', 'TELKOMSEL', 16687800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-dc650e69', 'Telkomsel 170.000', 'Pulsa', 'TELKOMSEL', 16786500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6625440c', 'Telkomsel 171.000', 'Pulsa', 'TELKOMSEL', 16885200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a9e8de1b', 'Telkomsel 172.000', 'Pulsa', 'TELKOMSEL', 16983900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-dfc70a34', 'Telkomsel 173.000', 'Pulsa', 'TELKOMSEL', 17082600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-dd95dd59', 'Telkomsel 174.000', 'Pulsa', 'TELKOMSEL', 17181300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-dcc41469', 'Telkomsel 175.000', 'Pulsa', 'TELKOMSEL', 17280000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f51739ee', 'Telkomsel 176.000', 'Pulsa', 'TELKOMSEL', 17378700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-88830626', 'Telkomsel 177.000', 'Pulsa', 'TELKOMSEL', 17477400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-08c1fb41', 'Telkomsel 178.000', 'Pulsa', 'TELKOMSEL', 17576100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4f9c233e', 'Telkomsel 179.000', 'Pulsa', 'TELKOMSEL', 17674800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d83a2d26', 'Telkomsel 180.000', 'Pulsa', 'TELKOMSEL', 17773500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-f88e3579', 'Telkomsel 181.000', 'Pulsa', 'TELKOMSEL', 17872200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1b9563ee', 'Telkomsel 182.000', 'Pulsa', 'TELKOMSEL', 17970900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a416c0df', 'Telkomsel 183.000', 'Pulsa', 'TELKOMSEL', 18069600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-02a7bc02', 'Telkomsel 184.000', 'Pulsa', 'TELKOMSEL', 18168300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-14eed154', 'Telkomsel 185.000', 'Pulsa', 'TELKOMSEL', 18267000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-554fd5f6', 'Telkomsel 186.000', 'Pulsa', 'TELKOMSEL', 18365700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-38044f62', 'Telkomsel 187.000', 'Pulsa', 'TELKOMSEL', 18464400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d109b297', 'Telkomsel 188.000', 'Pulsa', 'TELKOMSEL', 18563100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-547e9c28', 'Telkomsel 189.000', 'Pulsa', 'TELKOMSEL', 18661800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0c24c120', 'Telkomsel 190.000', 'Pulsa', 'TELKOMSEL', 18758000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fa74f1e1', 'Telkomsel 191.000', 'Pulsa', 'TELKOMSEL', 18859200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-17cfb3e5', 'Telkomsel 192.000', 'Pulsa', 'TELKOMSEL', 18957900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1afed007', 'Telkomsel 193.000', 'Pulsa', 'TELKOMSEL', 19056600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-80d39452', 'Telkomsel 194.000', 'Pulsa', 'TELKOMSEL', 19155300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9dcfb597', 'Telkomsel 195.000', 'Pulsa', 'TELKOMSEL', 19254000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c13a61fa', 'Telkomsel 200.000', 'Pulsa', 'TELKOMSEL', 19312500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4a26f8cd', 'Telkomsel 196.000', 'Pulsa', 'TELKOMSEL', 19352700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-bb481d10', 'Telkomsel 197.000', 'Pulsa', 'TELKOMSEL', 19451400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-90784f3b', 'Telkomsel 198.000', 'Pulsa', 'TELKOMSEL', 19550100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8f4e7b99', 'Telkomsel 199.000', 'Pulsa', 'TELKOMSEL', 19648800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0a3c0841', 'Telkomsel 205.000', 'Pulsa', 'TELKOMSEL', 20241000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8e0fbf0f', 'Telkomsel 210.000', 'Pulsa', 'TELKOMSEL', 20734500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c36ea139', 'Telkomsel 215.000', 'Pulsa', 'TELKOMSEL', 21228000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b1a19507', 'Telkomsel 220.000', 'Pulsa', 'TELKOMSEL', 21721500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b184ca0a', 'Telkomsel 225.000', 'Pulsa', 'TELKOMSEL', 22215000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-62cde792', 'Telkomsel 230.000', 'Pulsa', 'TELKOMSEL', 22708500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-cec87836', 'Telkomsel 235.000', 'Pulsa', 'TELKOMSEL', 23202000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a338148f', 'Telkomsel 240.000', 'Pulsa', 'TELKOMSEL', 23695500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1938e684', 'Telkomsel 245.000', 'Pulsa', 'TELKOMSEL', 24189000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e5e46e79', 'Telkomsel 246.000', 'Pulsa', 'TELKOMSEL', 24287700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3970d08a', 'Telkomsel 247.000', 'Pulsa', 'TELKOMSEL', 24386400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b64b4d28', 'Telkomsel 248.000', 'Pulsa', 'TELKOMSEL', 24485100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a926167a', 'Telkomsel 249.000', 'Pulsa', 'TELKOMSEL', 24583800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e2246bd1', 'Telkomsel 250.000', 'Pulsa', 'TELKOMSEL', 24695000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-32efede6', 'Telkomsel 251.000', 'Pulsa', 'TELKOMSEL', 24781200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('pulsa-telkomsel-89e065c2', 'Telkomsel 252.000', 'Pulsa', 'TELKOMSEL', 24879900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-25f1de6c', 'Telkomsel 253.000', 'Pulsa', 'TELKOMSEL', 24978600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2e6166ff', 'Telkomsel 254.000', 'Pulsa', 'TELKOMSEL', 25077300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9280dccb', 'Telkomsel 255.000', 'Pulsa', 'TELKOMSEL', 25176000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ef511eff', 'Telkomsel 256.000', 'Pulsa', 'TELKOMSEL', 25274700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9806d977', 'Telkomsel 257.000', 'Pulsa', 'TELKOMSEL', 25373400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0ada436e', 'Telkomsel 258.000', 'Pulsa', 'TELKOMSEL', 25472100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-a6cf9800', 'Telkomsel 259.000', 'Pulsa', 'TELKOMSEL', 25570800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-6818324f', 'Telkomsel 260.000', 'Pulsa', 'TELKOMSEL', 25669500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-60bda283', 'Telkomsel 261.000', 'Pulsa', 'TELKOMSEL', 25768200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-166b2228', 'Telkomsel 262.000', 'Pulsa', 'TELKOMSEL', 25866900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b0c85077', 'Telkomsel 263.000', 'Pulsa', 'TELKOMSEL', 25965600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1df27419', 'Telkomsel 264.000', 'Pulsa', 'TELKOMSEL', 26064300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-254d6e17', 'Telkomsel 265.000', 'Pulsa', 'TELKOMSEL', 26163000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1644ceec', 'Telkomsel 266.000', 'Pulsa', 'TELKOMSEL', 26261700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2f413a58', 'Telkomsel 267.000', 'Pulsa', 'TELKOMSEL', 26360400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-1d563717', 'Telkomsel 268.000', 'Pulsa', 'TELKOMSEL', 26459100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8819268b', 'Telkomsel 269.000', 'Pulsa', 'TELKOMSEL', 26557800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-471d6a80', 'Telkomsel 270.000', 'Pulsa', 'TELKOMSEL', 26656500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0c0e876d', 'Telkomsel 271.000', 'Pulsa', 'TELKOMSEL', 26755200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-4008f80c', 'Telkomsel 272.000', 'Pulsa', 'TELKOMSEL', 26853900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-0071cddb', 'Telkomsel 273.000', 'Pulsa', 'TELKOMSEL', 26952600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-17afc4fc', 'Telkomsel 274.000', 'Pulsa', 'TELKOMSEL', 27051300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-cd97ff01', 'Telkomsel 275.000', 'Pulsa', 'TELKOMSEL', 27162500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-d0809caf', 'Telkomsel 276.000', 'Pulsa', 'TELKOMSEL', 27248700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-ef7cf8c9', 'Telkomsel 277.000', 'Pulsa', 'TELKOMSEL', 27347400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-254f3545', 'Telkomsel 278.000', 'Pulsa', 'TELKOMSEL', 27446100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-c11d9901', 'Telkomsel 279.000', 'Pulsa', 'TELKOMSEL', 27544800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-329a508f', 'Telkomsel 280.000', 'Pulsa', 'TELKOMSEL', 27643500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-e6bbf463', 'Telkomsel 281.000', 'Pulsa', 'TELKOMSEL', 27742200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-17fc641d', 'Telkomsel 282.000', 'Pulsa', 'TELKOMSEL', 27840900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-231d08d2', 'Telkomsel 283.000', 'Pulsa', 'TELKOMSEL', 27939600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-09c33df3', 'Telkomsel 284.000', 'Pulsa', 'TELKOMSEL', 28038300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-23f783df', 'Telkomsel 285.000', 'Pulsa', 'TELKOMSEL', 28137000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3cde8f55', 'Telkomsel 286.000', 'Pulsa', 'TELKOMSEL', 28235700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-62b897c2', 'Telkomsel 287.000', 'Pulsa', 'TELKOMSEL', 28334400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2c02867a', 'Telkomsel 288.000', 'Pulsa', 'TELKOMSEL', 28433100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-70ab5d75', 'Telkomsel 289.000', 'Pulsa', 'TELKOMSEL', 28531800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2b166001', 'Telkomsel 290.000', 'Pulsa', 'TELKOMSEL', 28630500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-80e89d0f', 'Telkomsel 291.000', 'Pulsa', 'TELKOMSEL', 28729200, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-fee56082', 'Telkomsel 292.000', 'Pulsa', 'TELKOMSEL', 28827900, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-13d655c8', 'Telkomsel 293.000', 'Pulsa', 'TELKOMSEL', 28926600, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-35ffa421', 'Telkomsel 300.000', 'Pulsa', 'TELKOMSEL', 28962500, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-3cf04f93', 'Telkomsel 294.000', 'Pulsa', 'TELKOMSEL', 29025300, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-2103f2bd', 'Telkomsel 295.000', 'Pulsa', 'TELKOMSEL', 29124000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-16b48134', 'Telkomsel 296.000', 'Pulsa', 'TELKOMSEL', 29222700, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-8dfd1661', 'Telkomsel 297.000', 'Pulsa', 'TELKOMSEL', 29321400, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-9f30f674', 'Telkomsel 298.000', 'Pulsa', 'TELKOMSEL', 29420100, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-b93d1288', 'Telkomsel 299.000', 'Pulsa', 'TELKOMSEL', 29518800, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}'),
  ('pulsa-telkomsel-44d2cd19', 'Telkomsel 325.000', 'Pulsa', 'TELKOMSEL', 32220000, true, '{"type":"Umum","description":"Reguler","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/telkomsel.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


