-- Mini Batch 11
-- Chunks: import-batch-005-chunk-007.sql to import-batch-005-chunk-011.sql
-- Products: ~250

INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-tri-caaf668e', 'Tri Data Mini 1.5 GB 7 Hari', 'Data', 'TRI', 860000, true, '{"type":"Mini","description":"1.5 GB Nasional, 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-89349eea', 'Tri Data Happy 6 GB 2 Hari', 'Data', 'TRI', 891000, true, '{"type":"Happy","description":"6 gb utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6569880a', 'Tri Data Happy 7 GB 2 Hari', 'Data', 'TRI', 900000, true, '{"type":"Happy","description":"7 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-57d17b8a', 'Tri Data Happy Kikida 5 GB 2 Hari', 'Data', 'TRI', 900500, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5877f0a3', 'Tri Data 1.5 GB Lokal / 7 Hari', 'Data', 'TRI', 901000, true, '{"type":"Lokal","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e78d65eb', 'Tri Data Happy 5 GB 1 Hari (Jawa Tengah)', 'Data', 'TRI', 913500, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c1fcde30', 'Tri Data Happy 3 GB 2 Hari (Jawa Tengah)', 'Data', 'TRI', 914000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-0a1e2c04', 'Tri Data Happy 4 GB 3 Hari', 'Data', 'TRI', 917500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-aaa8c245', '300 MB (semua jaringan) Mengikuti Masa Aktif Kartu', 'Data', 'TRI', 930500, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b761f83e', 'Tri Data Happy 1.5 GB 7 Hari (Jawa Tengah)', 'Data', 'TRI', 945000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1e4b456a', 'Tri Data KeepOn 5GB + Viu Premium 3 Hari', 'Data', 'TRI', 987700, true, '{"type":"KeepOn","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6284e271', 'Tri Data KeepOn 5GB + Genflix 3 Hari', 'Data', 'TRI', 987900, true, '{"type":"KeepOn","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-59817865', 'Tri Data Happy 3.5 GB 3 Hari', 'Data', 'TRI', 996000, true, '{"type":"Happy","description":"3.5 gb utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c89202ad', 'Tri Data Happy 2 GB 5 Hari', 'Data', 'TRI', 1003500, true, '{"type":"Happy","description":"Tri Data Happy 2 GB / 5 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b202bad5', 'Tri Data Mini 2 GB 5 Hari', 'Data', 'TRI', 1015900, true, '{"type":"Mini","description":"Tri Data Mini 2 GB / 5 Hari, nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4d4fe091', 'Tri Data 2 GB 30 Hari', 'Data', 'TRI', 1050000, true, '{"type":"Pure 30 Hari","description":"Tri Data 2 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7e8c4119', 'Tri Data Happy 3 GB 3 Hari (Jawa Tengah)', 'Data', 'TRI', 1051000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-86dad504', 'Tri Data H3RO UL1 + Voucher MLBB', 'Data', 'TRI', 1100000, true, '{"type":"H3RO","description":"Kuota Reguler 1 GB, kuota games unlimited FUP 512 MB per hari, voucher games 12 diamond MLBB, masa aktif 7 Hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7cb8ba17', 'Tri Data 2 GB 7 Hari', 'Data', 'TRI', 1121000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8a662ec7', 'Tri Data 2 GB 14 Hari', 'Data', 'TRI', 1123000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9509f881', 'Tri Data 1.5 GB Nasional + 500 MB Lokal / 30 Hari', 'Data', 'TRI', 1127500, true, '{"type":"Lokal","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8f494e67', 'Tri Mix Small 2.75 GB 3 Hari', 'Data', 'TRI', 1128000, true, '{"type":"Mix","description":"0.75 GB (semua jaringan) + 2 GB (jaringan 4G) , Masa Aktif 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-637ae933', 'Tri Data Happy 3.5 GB 5 Hari (Jawa Tengah)', 'Data', 'TRI', 1151000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-008f1cc0', 'Tri Data Happy Play Movies 3 GB 3 Hari', 'Data', 'TRI', 1154500, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1640e86d', 'Tri Data Happy Play Games 3 GB 3 Hari', 'Data', 'TRI', 1154500, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-d3898b6f', 'Tri Data Happy 3 GB 3 Hari (Jawa Barat)', 'Data', 'TRI', 1169900, true, '{"type":"Jawa Barat","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-a5edb46a', 'Tri Data Happy Kikida 3 GB 3 Hari', 'Data', 'TRI', 1175000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9d3ca882', '500 MB (semua jaringan) + 1 GB (Youtube + Netflix) 3Hari', 'Data', 'TRI', 1180500, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-72322d15', 'Tri Data Happy 6 GB 3 Hari', 'Data', 'TRI', 1185000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-288ce0e3', 'Tri Data Happy 5 GB 3 Hari', 'Data', 'TRI', 1207500, true, '{"type":"Happy","description":"Tri Data Happy 5 GB / 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b8c8fcdc', 'Tri Data Happy 8 GB 3 Hari', 'Data', 'TRI', 1210000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ec471ac4', 'Tri Data Happy 2.5 GB 28 Hari', 'Data', 'TRI', 1232500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-70ccd1dd', 'Tri Data Happy 5 GB 3 Hari (Jawa Barat)', 'Data', 'TRI', 1237500, true, '{"type":"Jawa Barat","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f2ddee7e', 'Tri Data Happy 3 GB 28 Hari', 'Data', 'TRI', 1272500, true, '{"type":"Happy","description":"Tri Data Happy 3 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5327b803', 'Tri Data Addon 6 GB 3 Hari', 'Data', 'TRI', 1275000, true, '{"type":"Addon","description":"1 GB 24 jam, 5 GB (01.00-09.00), 3 hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-96d5be63', 'Tri Mix Small 3 GB 3 Hari', 'Data', 'TRI', 1300000, true, '{"type":"Mix","description":"3 GB semua jaringan 24 jam, Masa Aktif 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ca28b413', 'Tri Data 2 GB Nasional + 1 GB Lokal / 30 Hari', 'Data', 'TRI', 1322000, true, '{"type":"Lokal","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-54555498', 'Tri Data Happy Kikida 6 GB 3 Hari', 'Data', 'TRI', 1325000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1640215a', 'Tri Data Happy 3.5 GB 5 Hari', 'Data', 'TRI', 1327500, true, '{"type":"Happy","description":"Tri Data Happy 3.5 GB / 5 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4729df8c', 'Tri Data Happy 4.5 GB 5 Hari', 'Data', 'TRI', 1337500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5c646264', 'Tri Data Happy 5 GB 5 Hari', 'Data', 'TRI', 1360000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9140d23e', 'Tri Data Happy 5 GB 3 Hari (Jawa Tengah)', 'Data', 'TRI', 1371000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-feb9d12a', 'Tri Data Happy 6 GB 5 Hari', 'Data', 'TRI', 1372500, true, '{"type":"Happy","description":"Tri Data Happy 6 GB / 5 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-0a7cab49', 'Tri Data 2.5 GB 14 Hari', 'Data', 'TRI', 1401000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-11d9d12e', 'Tri Data 2.5 GB 30 Hari', 'Data', 'TRI', 1406000, true, '{"type":"Pure 30 Hari","description":"Tri Data 2.5 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ceae94bd', 'Tri Data Mini 3 GB 7 Hari', 'Data', 'TRI', 1437200, true, '{"type":"Mini","description":"Tri Data Mini 3 GB / 7 Hari, nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8a923f9a', 'Tri Data Happy 3 GB 7 Hari', 'Data', 'TRI', 1442500, true, '{"type":"Happy","description":"Tri Data Happy 3 GB / 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e3821abb', 'Tri Data Happy 7 GB 5 Hari', 'Data', 'TRI', 1457500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9a24150b', 'Tri Data AlwaysOn 2.5 GB', 'Data', 'TRI', 1469500, true, '{"type":"AlwaysOn","description":"2.5 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-74b23a5e', 'Tri Data 3 GB 30 Hari', 'Data', 'TRI', 1486200, true, '{"type":"Pure 30 Hari","description":"Tri Data 3 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-tri-adcbd24b', 'Tri Data Happy Kikida 4.5 GB 5 Hari', 'Data', 'TRI', 1548000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-184ff851', 'Three Data Transfer 5 GB / 7 Hari', 'Data', 'TRI', 1591000, true, '{"type":"Data Transfer","description":"2.5 GB Reguler + 2.5 GB jam 01.00 - 09.00, Berlaku 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-42ed5319', 'Tri Data Happy Ramadan 20 GB 3 Hari', 'Data', 'TRI', 1602200, true, '{"type":"Ramadan","description":"Kuota Utama 20 GB","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6836902c', 'Tri Data 2.75 GB 7 Hari', 'Data', 'TRI', 1644500, true, '{"type":"Umum","description":"750MB + 2 GB 4G, 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-317d1944', 'Tri Data Happy 10 GB 5 Hari', 'Data', 'TRI', 1648500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f28a2d68', 'Tri Data Happy 8 GB 5 Hari', 'Data', 'TRI', 1650000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-60269060', 'Tri Data 3 GB 14 Hari', 'Data', 'TRI', 1679000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-eee142a7', 'Tri Data Happy 5G 12 GB 3 Hari', 'Data', 'TRI', 1690000, true, '{"type":"Happy 5G","description":"9 GB Utama + 3 GB 5G 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c7c8c3ea', 'Tri Data 3 GB 7 Hari', 'Data', 'TRI', 1696000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-635aacf7', 'Tri Data AlwaysOn 2 GB', 'Data', 'TRI', 1768000, true, '{"type":"AlwaysOn","description":"2 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4d76e699', 'Tri Data Happy Kikida 7 GB 5 Hari', 'Data', 'TRI', 1801000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9b93f23e', 'Tri Data Happy 4.5 GB 7 Hari', 'Data', 'TRI', 1852500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3c578531', 'Tri Data Happy 5 GB 7 Hari', 'Data', 'TRI', 1852500, true, '{"type":"Happy","description":"Tri Data Happy 5 GB / 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5f7e0c00', 'Tri Data Happy 8 GB 7 Hari', 'Data', 'TRI', 1857500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-93d15799', 'Tri Data GetMore 4 GB / 30 Hari', 'Data', 'TRI', 1890000, true, '{"type":"GetMore","description":"2 GB 24 Jam (60 Hari) + 2 GB Youtube dan Netflix Jam 01.00 - 17.00 (30 hari)","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5a370b1c', 'Tri Data AlwaysOn 1.5 GB', 'Data', 'TRI', 1900000, true, '{"type":"AlwaysOn","description":"1.5 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7660f55d', 'Tri Data Happy 6 GB 5 Hari (Jawa Tengah)', 'Data', 'TRI', 1901000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-38f404e4', 'Tri Data Mini 5 GB 7 Hari', 'Data', 'TRI', 1901800, true, '{"type":"Mini","description":"2.5 GB Nasional, 2.5 GB (01.00 - 09.00), 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-24b1af97', 'Tri Data ++ 650 MB', 'Data', 'TRI', 1911000, true, '{"type":"Umum","description":"Kuota 650 MB mengikuti masa aktif kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c9b10c89', 'Tri Data Happy 11 GB 5 Hari', 'Data', 'TRI', 1949900, true, '{"type":"Happy","description":"11 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-117d1562', 'Tri Data Happy 3.5 GB 28 Hari', 'Data', 'TRI', 1962500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-82b23766', 'Tri Data AlwaysOn 3.5 GB', 'Data', 'TRI', 1970500, true, '{"type":"AlwaysOn","description":"3.5 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-acb879f4', 'Tri Data Happy 9 GB 7 Hari', 'Data', 'TRI', 1980500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e22ababf', 'Tri Data Happy 9 GB 7 Hari (Kalisumapa)', 'Data', 'TRI', 1985000, true, '{"type":"Kalisumapa","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e15a5179', 'Tri Data Happy 5 GB 7 Hari (Jawa Tengah)', 'Data', 'TRI', 1991000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3dc08450', 'Tri Data Happy 3 GB 14 Hari', 'Data', 'TRI', 1999000, true, '{"type":"Happy","description":"Tri Data Happy 3 GB / 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9728c341', 'Tri Data Happy 9 GB 5 Hari', 'Data', 'TRI', 2000000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-40978022', 'Tri Data Happy 10 GB 7 Hari', 'Data', 'TRI', 2002500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c476abf7', 'Tri Data Happy 3 GB 20 Hari', 'Data', 'TRI', 2011700, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4556396d', 'Tri Mix Small 3.75 GB 7 Hari', 'Data', 'TRI', 2026000, true, '{"type":"Mix","description":"1.75 GB (semua jaringan) + 2 GB (jaringan 4G), Masa Aktif 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5633595c', 'Tri Data AlwaysOn 3 GB', 'Data', 'TRI', 2050000, true, '{"type":"AlwaysOn","description":"3 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-66c10ac0', 'Tri Data Happy 7 GB 14 Hari', 'Data', 'TRI', 2072300, true, '{"type":"Happy","description":"7 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3a6383b1', 'Tri Data Happy 4.5 GB 28 Hari', 'Data', 'TRI', 2072500, true, '{"type":"Happy","description":"Tri Data Happy 4.5 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6c6b4c67', 'Tri Data Happy 15 GB 7 Hari', 'Data', 'TRI', 2075000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8af99398', 'Tri Data HiFi Air Booster 20 GB', 'Data', 'TRI', 2091000, true, '{"type":"HiFi Air","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b880b805', 'Tri Mix Small 3.75 GB 14 Hari', 'Data', 'TRI', 2125000, true, '{"type":"Mix","description":"1.75 GB (semua jaringan) + 2 GB (jaringan 4G), Masa Aktif 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-22576a04', 'Tri Data Happy 12 GB 7 Hari', 'Data', 'TRI', 2192500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-a5ae8b99', 'Tri Data Happy Travel 10 GB + 500 MB Roaming 3 Hari', 'Data', 'TRI', 2194800, true, '{"type":"Happy Travel","description":"Malaysia, Singapore, China dan Australia","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-241a9967', 'Tri Data 4 GB 30 Hari', 'Data', 'TRI', 2200000, true, '{"type":"Pure 30 Hari","description":"4 GB Nasional 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e07662bd', 'Tri Data Happy 9 GB 7 Hari (EJBN)', 'Data', 'TRI', 2201000, true, '{"type":"EJBN","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-56668659', 'Tri Data Happy Kikida 10 GB 7 Hari', 'Data', 'TRI', 2231000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5ba6da42', 'Tri Data 4 GB 7 Hari', 'Data', 'TRI', 2232000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b313b0a8', 'Tri Data 4 GB 14 Hari', 'Data', 'TRI', 2235000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-69fabfed', 'Tri Data Happy 9 GB 7 Hari (Jawa Tengah)', 'Data', 'TRI', 2241000, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3bf45bdf', 'Tri Data Happy 6 GB 28 Hari', 'Data', 'TRI', 2244700, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-676bc90a', 'Tri Data Happy Play Games 6 GB 7 Hari', 'Data', 'TRI', 2402500, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5692e55b', 'Tri Data Happy Play Movies 6 GB 7 Hari', 'Data', 'TRI', 2404200, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-19281bd7', 'Tri Data Happy 5 GB 28 Hari', 'Data', 'TRI', 2416800, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-728378dc', 'Tri Data Happy 4 GB 28 Hari', 'Data', 'TRI', 2421800, true, '{"type":"Happy","description":"4 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-2135a358', 'Tri Data Happy 7 GB 28 Hari', 'Data', 'TRI', 2435000, true, '{"type":"Happy","description":"Tri Data Happy 7 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-tri-9a316897', 'Tri Data Happy 5G 18 GB 7 Hari', 'Data', 'TRI', 2462400, true, '{"type":"Happy 5G","description":"15 GB Utama + 3 GB 5G 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7e5ebde3', 'Tri Data 5 GB 30 Hari', 'Data', 'TRI', 2477000, true, '{"type":"Pure 30 Hari","description":"Tri Data 5 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6ad5b06a', 'Tri Data AlwaysOn 4 GB', 'Data', 'TRI', 2490000, true, '{"type":"AlwaysOn","description":"4 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-50ef44b8', 'Tri Data Happy Ramadan 30 GB 5 Hari', 'Data', 'TRI', 2515000, true, '{"type":"Ramadan","description":"Kuota Utama 30 GB","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c7e656d7', 'Tri Data Happy Kikida 15 GB 7 Hari', 'Data', 'TRI', 2530000, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-04dbf607', 'Tri Data Happy 9 GB 10 Hari', 'Data', 'TRI', 2534500, true, '{"type":"Happy","description":"Tri Data Happy 9 GB / 10 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4a6f633f', 'Tri Data AlwaysOn 5 GB', 'Data', 'TRI', 2587500, true, '{"type":"AlwaysOn","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-d4413483', 'Tri Data Happy 10 GB 14 Hari', 'Data', 'TRI', 2591600, true, '{"type":"Happy","description":"10 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c936d81a', 'Tri Data Happy 6 GB 30 Hari', 'Data', 'TRI', 2677000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-fa39630a', 'Tri Data 5 GB 14 Hari', 'Data', 'TRI', 2700000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-524f8466', 'Tri Data 4.5 GB 30 Hari', 'Data', 'TRI', 2703000, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-10c2b1f4', 'Tri Data 6 GB 30 Hari', 'Data', 'TRI', 2710000, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6d6ac372', 'Tri Data Happy 17 GB 7 Hari', 'Data', 'TRI', 2725500, true, '{"type":"Happy","description":"17 GB Nasional Masa Aktif 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8a545008', 'Tri Data Sahabat Ojol 25.000', 'Data', 'TRI', 2751000, true, '{"type":"Sahabat Ojol","description":"2GB Regular + 15GB bebas akses aplikasi (500MB/hari akses WA, Waze, & GMaps) + 100 SMS dan 100 Menit telepon ke sesama Tri dan Indosat, berlaku 30 hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-2d1d54ea', 'Tri Data 7 GB 30 Hari', 'Data', 'TRI', 2766300, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b75a9516', 'Tri Data 5 GB 7 Hari', 'Data', 'TRI', 2782000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-2fe3359d', 'Tri Data AlwaysOn 6 GB', 'Data', 'TRI', 2790000, true, '{"type":"AlwaysOn","description":"6 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-8f837878', 'Tri Data Happy 9 GB 28 Hari', 'Data', 'TRI', 2842500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-36d0041b', 'Tri Data KeepOn 5GB 7 Hari', 'Data', 'TRI', 2862000, true, '{"type":"KeepOn","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-0831d702', 'Tri Data Happy 10 GB 28 Hari', 'Data', 'TRI', 2907500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-abb41877', '5 GB Semua Jaringan + 20 Menit Telepon + SMS Semua Op + TRIXOGO + VIU 7 Hari', 'Data', 'TRI', 2922500, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-700b2780', 'Tri Data Happy 9 GB 10 Hari (Jawa Tengah)', 'Data', 'TRI', 2972500, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7228269b', 'Tri Data 5 GB Nasional + 1 GB Lokal / 30 Hari', 'Data', 'TRI', 3012500, true, '{"type":"Lokal","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f9105a4b', 'Tri Data GetMore 8 GB / 30 Hari', 'Data', 'TRI', 3046000, true, '{"type":"GetMore","description":"4 GB 24 Jam (60 Hari) + 4 GB Youtube dan Netflix Jam 01.00 - 17.00 (30 hari)","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3200444f', 'Tri Data 8 GB 30 Hari', 'Data', 'TRI', 3083000, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-cd30d646', 'Tri Data 4G 10 GB 30 Hari', 'Data', 'TRI', 3102500, true, '{"type":"Umum","description":"2 GB + 8GB 4G + Content, 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1ab45a92', 'Tri Data Happy Kikida 7 GB 28 Hari', 'Data', 'TRI', 3122500, true, '{"type":"Kikida","description":"tidak memperpanjang Masa Aktif","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1da7c2a4', 'Tri Data Happy 7 GB 28 Hari (Jawa Tengah)', 'Data', 'TRI', 3182500, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-9bce239e', 'Tri Mix Kuota++ 1.25GB', 'Data', 'TRI', 3192500, true, '{"type":"Mix","description":"1.25GB  mengikuti masa aktif sim","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-84fe304c', 'Tri Data Happy 11 GB 28 Hari', 'Data', 'TRI', 3200000, true, '{"type":"Happy","description":"Tri Data Happy 11 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3acc0189', 'Tri Data Happy 10 GB 10 Hari', 'Data', 'TRI', 3200000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3eac1ad0', 'Tri Data 6 GB 14 Hari', 'Data', 'TRI', 3202500, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-80e04e0e', 'Tri Data 9 GB 30 Hari', 'Data', 'TRI', 3202500, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-feebba56', 'Tri Data Happy 5G 14 GB 30 Hari', 'Data', 'TRI', 3296000, true, '{"type":"Happy 5G","description":"11 GB Utama + 3 GB 5G 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-eb8f9027', 'Tri Data 5.5 GB 30 Hari', 'Data', 'TRI', 3303000, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ea6ef7f5', 'Tri Data 10 GB 30 Hari', 'Data', 'TRI', 3312000, true, '{"type":"Pure 30 Hari","description":"Kuota 10GB ( 2G/3G/4G ) 24 JAM masa aktif 30 hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-0d2354e4', 'Tri Data 6 GB 7 Hari', 'Data', 'TRI', 3342000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-fc4c390f', 'Tri Data H3RO Max', 'Data', 'TRI', 3392500, true, '{"type":"H3RO","description":"5GB (24 jam akses internet dan semua aplikasi di seluruh jaringan Tri), Unlimited (24 jam akses games Free Fire, MLBB, PUBG, AOV dan CODM di seluruh jaringan Tri) - FUP 512MB/hari, kecepatan akses setelah FUP 128 kbps.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-db9ffa0c', '5GB + 4GB (01 Pagi - 12 Siang) + 10 Menit Telepon All Op 7 Hari', 'Data', 'TRI', 3462500, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-45b09f69', 'Tri Data 2 GB + 20 Menit Telepon / 30 Hari', 'Data', 'TRI', 3490000, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f397294a', 'Tri Data Happy 14 GB 28 Hari', 'Data', 'TRI', 3500000, true, '{"type":"Happy","description":"Tri Data Happy 14 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-398f1d34', 'Tri Data Happy 10.5 GB 28 Hari', 'Data', 'TRI', 3500000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-154c4fc3', 'Tri Data Addon 2 GB + Voice 30 Hari', 'Data', 'TRI', 3523500, true, '{"type":"Addon","description":"2 GB 24 jam, 20 menit sesama, 30 hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-20432fbb', 'Tri Data GetMore 10 GB / 30 Hari', 'Data', 'TRI', 3562500, true, '{"type":"GetMore","description":"5 GB 24 Jam (90 Hari) + 5 GB Youtube dan Netflix Jam 01.00 - 17.00 (30 hari)","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-bbe8fd13', 'Tri Data 7 GB 7 Hari', 'Data', 'TRI', 3572000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-024666cf', 'Tri Data 7 GB 14 Hari', 'Data', 'TRI', 3582000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-303ceacc', 'Tri Data Happy 12 GB 28 Hari', 'Data', 'TRI', 3732500, true, '{"type":"Happy","description":"Tri Data Happy 12 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4911485d', 'Tri Data 6.5 GB 30 Hari', 'Data', 'TRI', 3903000, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c8a63c07', 'Tri Data Happy 13 GB 28 Hari', 'Data', 'TRI', 3972500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-327e4594', 'Tri Data 8 GB 7 Hari', 'Data', 'TRI', 3982000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-tri-dc016367', 'Tri Data 8 GB 14 Hari', 'Data', 'TRI', 3982000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-a7c37a34', 'Tri Data H3RO UL3 + Voucher MLBB', 'Data', 'TRI', 4000000, true, '{"type":"H3RO","description":"Kuota Reguler 3 GB, kuota games unlimited FUP 512 MB per hari, voucher games 85 diamond MLBB, masa aktif 30 Hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ad12c5df', 'Tri Data 9 GB 7 Hari', 'Data', 'TRI', 4012000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c381429e', 'Tri Data 9 GB 14 Hari', 'Data', 'TRI', 4012000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-769eaec2', 'Tri Data 10 GB 7 Hari', 'Data', 'TRI', 4022000, true, '{"type":"Pure 7 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-46d7fb90', 'Tri Data 10 GB 14 Hari', 'Data', 'TRI', 4022000, true, '{"type":"Pure 14 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-6ebb4fcc', 'Tri Data AlwaysOn 9 GB', 'Data', 'TRI', 4180000, true, '{"type":"AlwaysOn","description":"9 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-fca64147', 'Tri Data AlwaysOn 8 GB', 'Data', 'TRI', 4200000, true, '{"type":"AlwaysOn","description":"8 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-38316598', 'Tri Data AlwaysOn 7 GB', 'Data', 'TRI', 4232500, true, '{"type":"AlwaysOn","description":"7 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-19211b3f', 'Tri Data Happy 15 GB 28 Hari', 'Data', 'TRI', 4250000, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e161317c', 'Tri Data Happy 16 GB 28 Hari', 'Data', 'TRI', 4250000, true, '{"type":"Happy","description":"Tri Data Happy 16 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-857fb160', 'Tri Data Sahabat Ojol 40.000', 'Data', 'TRI', 4252500, true, '{"type":"Sahabat Ojol","description":"6GB Regular + 15GB bebas akses aplikasi (500MB/hari akses WA, Waze, & GMaps) + 200 SMS  dan 200 Menit telepon ke sesama Tri dan Indosat, berlaku 30 hari.","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-03361cb0', 'Tri Data Happy Play Games 9 GB 28 Hari', 'Data', 'TRI', 4262500, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-bb8a0782', 'Tri Data Happy Play Movies 9 GB 28 Hari', 'Data', 'TRI', 4273200, true, '{"type":"Happy Play","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-659ad962', 'Tri Data HiFi Air Booster 50 GB', 'Data', 'TRI', 4277500, true, '{"type":"HiFi Air","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5aa75c20', 'Tri Data Happy Ramadan 75 GB 7 Hari', 'Data', 'TRI', 4293500, true, '{"type":"Ramadan","description":"Kuota Utama 75 GB","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-54bc4275', 'Tri Data Happy 13.5 GB 28 Hari', 'Data', 'TRI', 4372500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-618bb228', 'Tri Data Happy 11 GB 28 Hari (Jawa Tengah)', 'Data', 'TRI', 4392500, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-c8916964', 'Tri Data 15 GB / 30 Hari', 'Data', 'TRI', 4437500, true, '{"type":"Umum","description":"Kuota 15GB ( 2G/3G/4G ) 24 JAM masa aktif 30 hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-997144a7', 'Tri Data 3 GB + 30 Menit Telepon / 30 Hari', 'Data', 'TRI', 4460000, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-702413de', 'Tri Data Happy 18 GB 28 Hari', 'Data', 'TRI', 4500000, true, '{"type":"Happy","description":"Tri Data Happy 18 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-756acece', 'Tri Mix Super 10 GB 30 Hari', 'Data', 'TRI', 4502500, true, '{"type":"Mix","description":"2 GB (semua jaringan) + 8 GB (jaringan 4G), Masa Aktif 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-85c4673f', 'Tri Data 7.5 GB 30 Hari', 'Data', 'TRI', 4503000, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-4fcd8a45', 'Tri Data H3RO 9 GB / 30 Hari', 'Data', 'TRI', 4530000, true, '{"type":"Umum","description":"2 GB kuota utama + 7 GB kuota Games + 30 Menit Telepon Sesama Tri, masa aktif 30 Hari (sesuai zona/area)","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-39cb6984', 'Tri Data Happy 23 GB 14 Hari', 'Data', 'TRI', 4577500, true, '{"type":"Happy","description":"23 GB Nasional Masa Aktif 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-30d2a433', 'Tri Data 12 GB / 30 Hari', 'Data', 'TRI', 4682500, true, '{"type":"Umum","description":"10GB Regular + 2GB Youtube/Netflix, 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b0623a15', 'Tri Data 4G 15 GB / 30 Hari', 'Data', 'TRI', 4692500, true, '{"type":"Umum","description":"3 GB + 9GB 4G + 3 GB (Youtube/Netflix) 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-3a3b5172', 'Tri Data 3 GB Vidio FIFA World Cup Mobile', 'Data', 'TRI', 4762500, true, '{"type":"FIFA World Cup","description":"Tri Data 3 GB 30 Hari dan Vidio FIFA World Cup Mobile","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-5d8e30bc', 'Tri Data Happy Spesial 30 GB 30 Hari', 'Data', 'TRI', 4866000, true, '{"type":"Happy","description":"Pembagian kuota 1GB/hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-26a4c0b4', 'Tri Data Happy Ramadan 30 GB 30 Hari', 'Data', 'TRI', 4868200, true, '{"type":"Ramadan","description":"1GB per hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-2a87b130', 'Tri Data Happy 20 GB 28 Hari', 'Data', 'TRI', 4902500, true, '{"type":"Happy","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-1edce68d', 'Tri Data KeepOn 16GB + Viu Premium 30 Hari', 'Data', 'TRI', 4934200, true, '{"type":"KeepOn","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-559a9e70', 'Tri Data KeepOn 16GB + Klikfilm 30 Hari', 'Data', 'TRI', 4934200, true, '{"type":"KeepOn","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-be737c2c', 'Tri Data KeepOn 16GB + Genflix 30 Hari', 'Data', 'TRI', 4934300, true, '{"type":"KeepOn","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-dcf66e4d', 'Tri Data 4G 10 GB + Genflix 30 hari', 'Data', 'TRI', 4962500, true, '{"type":"Umum","description":"2 GB (semua jaringan)  + 8 GB 4G + Genflix 30 hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-64db3dcb', 'Tri Data Happy 5G 22 GB 30 Hari', 'Data', 'TRI', 4987500, true, '{"type":"Happy 5G","description":"12 GB Utama + 10 GB 5G 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-0d884e9b', 'Tri Mix Kuota++ 2.25GB', 'Data', 'TRI', 5025000, true, '{"type":"Mix","description":"2.25GB mengikuti masa aktif sim","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-da883629', 'Tri Data Happy 30 GB 28 Hari', 'Data', 'TRI', 5103000, true, '{"type":"Happy","description":"Tri Data Happy 30 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-cdbc012a', 'Tri Data 8.5 GB 30 Hari', 'Data', 'TRI', 5103000, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b800fee1', 'Tri Data Happy 5G 24 GB 30 Hari', 'Data', 'TRI', 5178000, true, '{"type":"Happy 5G","description":"16 GB Utama + 8 GB 5G 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-ad5b88d1', 'Tri Data Happy 24 GB 28 Hari', 'Data', 'TRI', 5200000, true, '{"type":"Happy","description":"24 GB Utama","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-a2bff713', 'Tri Data 4G 12 GB / 30 Hari', 'Data', 'TRI', 5240000, true, '{"type":"Umum","description":"2 GB + 8GB 4G + 2 GB (Youtube/Netflix), 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-522781d3', 'Tri Data AlwaysOn 12 GB', 'Data', 'TRI', 5300000, true, '{"type":"AlwaysOn","description":"12 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7da70924', 'Tri Data AlwaysOn 10 GB', 'Data', 'TRI', 5302500, true, '{"type":"AlwaysOn","description":"10 GB Nasional, Mengikuti Masa Aktif Kartu","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-b0fc8971', 'Tri Data Happy 25 GB 28 Hari', 'Data', 'TRI', 5387500, true, '{"type":"Happy","description":"Tri Data Happy 25 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-f143dea3', 'Tri Data Happy 14 GB 28 Hari (Jawa Tengah)', 'Data', 'TRI', 5487500, true, '{"type":"Jawa Tengah","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-7ab34796', 'Tri Data 20 GB / 30 Hari', 'Data', 'TRI', 5692500, true, '{"type":"Umum","description":"Kuota 20GB ( 2G/3G/4G ) 24 JAM masa aktif 30 hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-e0cc5514', 'Tri Data 9.5 GB 30 Hari', 'Data', 'TRI', 5703000, true, '{"type":"Pure 30 Hari","description":"24 jam nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-de39b49c', '8,5 GB +100 Menit Telepon + SMS Semua Op + TRIXOGO + VIU 30 Hari', 'Data', 'TRI', 5872500, true, '{"type":"Umum","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}'),
  ('data-tri-d9c3fc75', 'Tri Data Happy 26 GB 28 Hari', 'Data', 'TRI', 5897500, true, '{"type":"Happy","description":"Tri Data Happy 26 GB / 28 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/three.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
ON CONFLICT (sku_digiflazz) DO UPDATE SET
  name = EXCLUDED.name
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


