-- Mini Batch 6
-- Chunks: import-batch-003-chunk-004.sql to import-batch-003-chunk-008.sql
-- Products: ~250

INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-5cb44620', 'XL HOTROD 1.5 GB 3 Hari', 'Data', 'XL', 890000, true, '{"type":"Hotrod","description":"Hotrod Baru 1.5GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1172c77d', 'XL XTRA KUOTA 3 GB Facebook 7 Hari', 'Data', 'XL', 892500, true, '{"type":"Xtra Kuota","description":"XTRA Kuota Facebook 3GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7ca3a1eb', 'XL XTRA KUOTA 3 GB Instagram 7 Hari', 'Data', 'XL', 892500, true, '{"type":"Xtra Kuota","description":"XTRA Kuota Instagram 3GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-95cf3e3b', 'XL XTRA KUOTA 3 GB Youtube 7 Hari', 'Data', 'XL', 892500, true, '{"type":"Xtra Kuota","description":"XTRA Kuota YouTube 3GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c49dcd05', 'XL XTRA KUOTA 3 GB TikTok 7 Hari', 'Data', 'XL', 892500, true, '{"type":"Xtra Kuota","description":"XTRA Kuota TikTok 3GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1f07131c', 'XL Data Flex Mini 6 GB 2 Hari', 'Data', 'XL', 900000, true, '{"type":"Flex Mini","description":"6 GB Nasional 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-03305a3d', 'XL Data Bonus Harian 2 GB 3 Hari', 'Data', 'XL', 900000, true, '{"type":"Bonus Harian","description":"2 GB Nasional, 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0952b222', 'XL Data Bonus Harian 4 GB 2 Hari', 'Data', 'XL', 900000, true, '{"type":"Bonus Harian","description":"4 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-10b1511c', 'XL XTRA KUOTA 2 GB 12 Jam', 'Data', 'XL', 900000, true, '{"type":"Xtra Kuota","description":"XTRA Kuota Utama 2GB, 12jam","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8ccd4055', 'XL Data Bebas Puas 3.6 GB 2 Hari', 'Data', 'XL', 900000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-954c9e0d', 'XL Xtra Combo Mini Gift 1.5 GB 7 Hari', 'Data', 'XL', 908000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini Gift 1.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d11dde32', 'XL Xtra Combo Mini 1.5 GB 3 Hari', 'Data', 'XL', 912500, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 1.5GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1dbb02b3', 'XL Data Paket Harian M 3 Hari', 'Data', 'XL', 915000, true, '{"type":"Harian","description":"Paket Harian M, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8520c0a0', 'XL Data Blue 3 GB 2 Hari', 'Data', 'XL', 938000, true, '{"type":"Blue","description":"Paket Blue 3GB, 2hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0101999d', 'XL Xtra Combo Mini Gift 2 GB 3 Hari', 'Data', 'XL', 940000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini 2GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-61f1cf02', 'XL XTRA Hotrod Special 1.5 GB 7 Hari', 'Data', 'XL', 977500, true, '{"type":"Hotrod Special","description":"1 GB nasional + 500 MB Youtube (00:00 - 12:00), berlaku 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b991b3da', 'XL Xtra Combo Mini 1.5 GB 7 Hari', 'Data', 'XL', 980000, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 1.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d91a7564', 'XL XTRA KUOTA 10 GB Mobile Legends 30 Hari', 'Data', 'XL', 984500, true, '{"type":"Xtra Kuota","description":"Xtra Kuota Mobile Legends 10GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a2a94d78', 'XL XTRA KUOTA 2 GB Instagram - 30 Hari', 'Data', 'XL', 985500, true, '{"type":"Xtra Kuota","description":"2 GB Instagram 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-117e632c', 'XL XTRA KUOTA 2 GB Facebook 30 Hari', 'Data', 'XL', 985500, true, '{"type":"Xtra Kuota","description":"Xtra Kuota Facebook 2GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-92918f4c', 'XL XTRA KUOTA 5 GB Midnight - 30 Hari', 'Data', 'XL', 985500, true, '{"type":"Xtra Kuota","description":"5 GB Midnight 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-be3008f2', 'XL Data Blue 5 GB 2 Hari', 'Data', 'XL', 988500, true, '{"type":"Blue","description":"Paket Blue 5GB, 2hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8970496e', 'XL XTRA KUOTA 2 GB Joox - 30 Hari', 'Data', 'XL', 990000, true, '{"type":"Xtra Kuota","description":"2 GB Joox 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b55e1e85', 'XL XTRA KUOTA 2 GB Youtube 30 Hari', 'Data', 'XL', 991000, true, '{"type":"Xtra Kuota","description":"Xtra Kuota YouTube 2GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-88faa43c', 'XL XTRA KUOTA 5 GB IFLIX 30 Hari', 'Data', 'XL', 992000, true, '{"type":"Xtra Kuota","description":"Xtra Kuota iFlix 5GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c0eceeb3', 'XL XTRA KUOTA 10 GB Waze - 30 Hari', 'Data', 'XL', 992000, true, '{"type":"Xtra Kuota","description":"10 GB Waze 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c1126b04', 'XL Xtra Combo Mini 3 GB 3 Hari', 'Data', 'XL', 1000000, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 3GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fc908e35', 'XL Xtra Combo Mini Gift 1.5 GB 3 Hari', 'Data', 'XL', 1000000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini 1.5GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-34c8cb46', 'XL Xtra Combo Mini Gift 3 GB 3 Hari', 'Data', 'XL', 1000000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini 3GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-92ff7379', 'XL Data Bonus Harian 5 GB 2 Hari', 'Data', 'XL', 1000000, true, '{"type":"Bonus Harian","description":"5 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-28884d62', 'XL Data Bonus Harian 5 GB 1 Hari', 'Data', 'XL', 1000000, true, '{"type":"Bonus Harian","description":"5 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-67ae3142', 'XL Data Bebas Puas 1.5 GB 6 Hari', 'Data', 'XL', 1000000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a807225a', 'XL Xtra Conference 15 GB 7 Hari', 'Data', 'XL', 1002300, true, '{"type":"Conference","description":"Xtra Conference 15GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-5c2eaa61', 'XL XTRA Hotrod Special 1.5 GB 3 Hari', 'Data', 'XL', 1016500, true, '{"type":"Hotrod Special","description":"1.5 gb utama, 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2ce88569', 'XL XTRA Hotrod Special 2 GB 7 Hari - Central', 'Data', 'XL', 1051000, true, '{"type":"Central","description":"Xtra Hotrod Special 2GB, 7hr - Central","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-da212f6b', 'XL Data Bebas Puas 2 GB 4 Hari', 'Data', 'XL', 1085500, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-16b21fc4', 'XL XTRA KUOTA 2 GB 24 Jam', 'Data', 'XL', 1100000, true, '{"type":"Xtra Kuota","description":"XTRA Kuota Utama 2GB, 24jam","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-690ecf20', 'XL XTRA Hotrod Special S 7 Hari', 'Data', 'XL', 1102500, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special S, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d4d5298b', 'XL Data 3 GB 30 Hari', 'Data', 'XL', 1123000, true, '{"type":"Umum","description":"DRP DATA 3 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9dca3a4f', 'XL XTRA KUOTA 30 GB 30 HARI', 'Data', 'XL', 1125000, true, '{"type":"Xtra Kuota","description":"Packet Xtra Kuota 30GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-84e9652f', 'XL Data Flex Mini 3.5 GB 3 Hari', 'Data', 'XL', 1125900, true, '{"type":"Flex Mini","description":"3.5 GB Nasional 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-bf20cc4a', 'XL Data Paket Harian L 3 Hari', 'Data', 'XL', 1130000, true, '{"type":"Harian","description":"Paket Harian L, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7e217309', 'XL Data Flex Mini 4 GB 3 Hari', 'Data', 'XL', 1131000, true, '{"type":"Flex Mini","description":"4 GB Nasional 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4f4b6774', 'XL HOTROD 2 GB 7 Hari', 'Data', 'XL', 1131000, true, '{"type":"Hotrod","description":"Hotrod Baru 2GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8a054479', 'XL Data Paket Harian S 5 Hari', 'Data', 'XL', 1135000, true, '{"type":"Harian","description":"Paket Harian S, 5hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b3db20fb', 'XL XTRA Hotrod Special 2 GB 7 Hari', 'Data', 'XL', 1146400, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 2GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a1ee8afe', 'XL Data Bebas Puas 1.75 GB 7 Hari', 'Data', 'XL', 1160000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7c6cfc32', 'XL Data 2 GB 30 Hari', 'Data', 'XL', 1174500, true, '{"type":"Umum","description":"DRP DATA 2 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d4186d9e', 'XL Data Paket Harian XS 7 Hari', 'Data', 'XL', 1175000, true, '{"type":"Harian","description":"Paket Harian XS, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fdb343a2', 'XL XTRA Hotrod Special 2.5 GB 3 Hari - West', 'Data', 'XL', 1200000, true, '{"type":"West","description":"Xtra Hotrod Special 2.5GB, 3hr - West","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-97a2dc81', 'XL Data 4 GB 30 Hari', 'Data', 'XL', 1200000, true, '{"type":"Umum","description":"DRP DATA 4 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9eeeb8d7', 'XL Data Bebas Puas 6rb/hr - 2 Hari', 'Data', 'XL', 1211000, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a0d438b2', 'XL Xtra Kuota Vidio 5 GB & Vidio Platinum Mobile 30 hari', 'Data', 'XL', 1243500, true, '{"type":"Xtra Kuota Vidio","description":"Xtra Kuota Vidio 5GB & Vidio Platinum Mobile 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3d48621b', 'XL Data Paket Harian XS 10 Hari', 'Data', 'XL', 1250000, true, '{"type":"Harian","description":"Paket Harian XS, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-83a4b318', 'XL Data Bebas Puas 2.5 GB 5 Hari', 'Data', 'XL', 1250000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0f61869a', 'XL Data 1.5 GB 30 Hari', 'Data', 'XL', 1262500, true, '{"type":"Umum","description":"XL Data 1.5 GB 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-84b084df', 'XL Data Paket Harian M 5 Hari', 'Data', 'XL', 1287500, true, '{"type":"Harian","description":"Paket Harian M, 5hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3e155245', 'XL Data Flex Mini 12 GB 2 Hari', 'Data', 'XL', 1300000, true, '{"type":"Flex Mini","description":"12 GB Nasional 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a6d68140', 'XL XTRA ON 1GB', 'Data', 'XL', 1302300, true, '{"type":"Xtra On","description":"XTRA ON 1GB","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-92dbb208', 'XL Data Flex Mini 6 GB 3 Hari', 'Data', 'XL', 1305000, true, '{"type":"Flex Mini","description":"6 GB Nasional 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e412f5f1', 'XL Data Bebas Puas 5.4 GB 3 Hari', 'Data', 'XL', 1310000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a29a329f', 'XL Data Bebas Puas 2 GB 8 Hari', 'Data', 'XL', 1330000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-343ffb59', 'XL Xtra Combo Mini 2 GB 3 Hari', 'Data', 'XL', 1350500, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 2GB, 3hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-674dbf2e', 'XL Data Games 3 GB 30 Hari', 'Data', 'XL', 1350500, true, '{"type":"Games","description":"DRP MAIN+GAMES 3GB 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-29c6420e', 'XL Data Mini 2.5 GB 7 Hari', 'Data', 'XL', 1370000, true, '{"type":"Mini","description":"2,5GB FULL 24 JAM NASIONAL, 7 HARI","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ae121d30', 'XL Data Kuota Apps & Games 2.5 GB 30 Hari', 'Data', 'XL', 1380500, true, '{"type":"Apps Games","description":"Quota Apps & Games 2,5GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ebc73210', 'XL Xtra Combo Mini 2.5 GB 7 Hari', 'Data', 'XL', 1383000, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 2.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1b93f3dc', 'XL Data Bonus Harian 6 GB 1 Hari', 'Data', 'XL', 1400000, true, '{"type":"Bonus Harian","description":"6 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ac361614', 'XL Data Bonus Harian 6 GB 2 Hari', 'Data', 'XL', 1400000, true, '{"type":"Bonus Harian","description":"6 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-23c241b6', 'XL XTRA Hotrod Special 2 GB 7 Hari - West', 'Data', 'XL', 1400000, true, '{"type":"West","description":"Xtra Hotrod Special 2GB, 7hr - West","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-11fcef01', 'XL Data 5 GB 30 Hari', 'Data', 'XL', 1402500, true, '{"type":"Umum","description":"DRP DATA 5 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b39ec7b1', 'XL XTRA Hotrod Special M 7 Hari', 'Data', 'XL', 1421000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special M, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-384d1678', 'XL Data Paket Harian S 7 Hari', 'Data', 'XL', 1425000, true, '{"type":"Harian","description":"Paket Harian S, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0917e298', 'XL XTRA Hotrod Special 2.5 GB / 7 Hari', 'Data', 'XL', 1429000, true, '{"type":"Hotrod Special","description":"1.5 GB nasional + 1 GB Youtube (00:00 - 12:00), berlaku 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e7d6a7b8', 'XL Xtra Combo Mini Gift 2.5 GB 7 Hari', 'Data', 'XL', 1430000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini Gift 2.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-beb2102c', 'XL Data Paket Harian L 5 Hari', 'Data', 'XL', 1437500, true, '{"type":"Harian","description":"Paket Harian L, 5hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2aec7fbc', 'XL XTRA Hotrod Special 3 GB 7 Hari', 'Data', 'XL', 1438800, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 3GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a1b6e174', 'XL Data Flex Mini 4 GB 7 Hari', 'Data', 'XL', 1448400, true, '{"type":"Flex Mini","description":"4 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a7ffac72', 'XL XTRA HotRod Special 3 GB 10 Hari', 'Data', 'XL', 1449000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 3GB, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-19f83742', 'XL HOTROD 3 GB 5 Hari', 'Data', 'XL', 1456000, true, '{"type":"Hotrod","description":"HotRod Baru 3GB, 5hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9122364a', 'XL Data Paket Harian S 10 Hari', 'Data', 'XL', 1495000, true, '{"type":"Harian","description":"Paket Harian S, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-86e8cb7f', 'XL Data Mini 4 GB 7 Hari', 'Data', 'XL', 1495000, true, '{"type":"Mini","description":"4GB FULL 24 JAM NASIONAL, 7 HARI","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4d58e81f', 'XL Data Bonus Harian 7 GB 1 Hari', 'Data', 'XL', 1500000, true, '{"type":"Bonus Harian","description":"7 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f33f22a6', 'XL Data Bonus Harian 7 GB 2 Hari', 'Data', 'XL', 1500000, true, '{"type":"Bonus Harian","description":"7 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a6aa5071', 'XL Data Bebas Puas 2.25 GB 9 Hari', 'Data', 'XL', 1500000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2b38ac5f', 'XL XTRA ON 2GB', 'Data', 'XL', 1501000, true, '{"type":"Xtra On","description":"XTRA ON 2GB","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c36c313c', 'XL Data Bebas Puas 3 GB 6 Hari', 'Data', 'XL', 1537500, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-5bda99f0', 'XL Data Bonus Harian 8 GB 1 Hari', 'Data', 'XL', 1600000, true, '{"type":"Bonus Harian","description":"8 GB Nasional, 1 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d9353aa7', 'XL HOTROD 3 GB 7 Hari', 'Data', 'XL', 1620000, true, '{"type":"Hotrod","description":"Hotrod 3GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a767a596', 'XL XTRA HotRod Special 4 GB 10 Hari', 'Data', 'XL', 1653000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 4GB, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-59f35cf4', 'XL Data Bebas Puas 2.5 GB 10 Hari', 'Data', 'XL', 1680000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-15f5aa31', 'XL Data Bebas Puas 6rb/hr - 3 Hari', 'Data', 'XL', 1698400, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-06db12a4', 'XL Data Bonus Harian 8 GB 2 Hari', 'Data', 'XL', 1700000, true, '{"type":"Bonus Harian","description":"8 GB Nasional, 2 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-12f5ab3e', 'XL Xtra Kuota Vidio 5 GB & Vidio Platinum Big Screen 30 hari', 'Data', 'XL', 1742500, true, '{"type":"Xtra Kuota Vidio","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-62a3ecc8', 'XL Data Grab Gacor 4 GB 7 Hari', 'Data', 'XL', 1743500, true, '{"type":"Grab Gacor","description":"Paket Grab Gacor 4GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9023105d', 'XL Data Bebas Puas 3.5 GB 7 Hari', 'Data', 'XL', 1750000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-61f2e0e3', 'XL Data Kuota Apps & Games 3.5 GB 30 Hari', 'Data', 'XL', 1751000, true, '{"type":"Apps Games","description":"Quota Apps & Games 3,5GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-92137698', 'XL Data Bebas Puas 7.2 GB 4 Hari', 'Data', 'XL', 1770000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-cc745979', 'XL Data Flex Mini 6 GB 7 Hari', 'Data', 'XL', 1785000, true, '{"type":"Flex Mini","description":"6 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3c172373', 'XL Xtra Combo Mini 4 GB 7 Hari', 'Data', 'XL', 1790000, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 4GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-39b3fdd9', 'XL Xtra Combo Mini Gift 4 GB 7 Hari', 'Data', 'XL', 1800000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini Gift 4GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0f33168d', 'XL XTRA Hotrod Special L 7 Hari', 'Data', 'XL', 1800000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special L, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-732db64c', 'XL XTRA Hotrod Special 4 GB / 7 Hari', 'Data', 'XL', 1818500, true, '{"type":"Hotrod Special","description":"2 GB nasional + 2 GB Youtube (00:00 - 12:00), berlaku 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-73f071d3', 'XL Data Paket Harian M 7 Hari', 'Data', 'XL', 1822500, true, '{"type":"Harian","description":"Paket Harian M, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-82be324c', 'XL Data Mini 6 GB 7 Hari', 'Data', 'XL', 1825000, true, '{"type":"Mini","description":"6GB FULL24 JAM  NASIONAL, 7 HARI","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-be17787c', 'XL Data Flex Mini 3 GB 14 Hari', 'Data', 'XL', 1844000, true, '{"type":"Flex Mini","description":"3 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-08446070', 'XL HOTROD 1.5 GB 30 Hari', 'Data', 'XL', 1857500, true, '{"type":"Hotrod","description":"Hotrod 1.5GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-44e78438', 'XL Data Bebas Puas 2.75 GB 11 Hari', 'Data', 'XL', 1861000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-bf36a626', 'XL Data Flex Mini 20 GB 3 Hari', 'Data', 'XL', 1877000, true, '{"type":"Flex Mini","description":"20 GB Nasional 3 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ad32016d', 'XL Data Games 4 GB 30 Hari', 'Data', 'XL', 1890500, true, '{"type":"Games","description":"DRP MAIN+GAMES 4GB 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7819cedf', 'XL Data Paket Harian M 10 Hari', 'Data', 'XL', 1895000, true, '{"type":"Harian","description":"Paket Harian M, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fe7d11fa', 'XL XTRA Hotrod Special 4.5 GB 7 Hari', 'Data', 'XL', 1903700, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 4.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4b3a029d', 'XL Xtra Combo Flex S 14 Hari', 'Data', 'XL', 1931000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex S, 14hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e4a886a0', 'XL Xtra Combo Flex S 21 Hari', 'Data', 'XL', 1990000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex S, 21hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-53b0c73b', 'XL XTRA Hotrod Special 2.5 GB 3 Hari - East', 'Data', 'XL', 2000000, true, '{"type":"East","description":"Xtra Hotrod Special 2.5GB, 3hr - East","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-94e7eb22', 'XL Data 6 GB 30 Hari', 'Data', 'XL', 2000000, true, '{"type":"Umum","description":"DRP DATA 6 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-11d81ea6', 'XL Data 7 GB 30 Hari', 'Data', 'XL', 2000000, true, '{"type":"Umum","description":"DRP DATA 7 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2d2d6bd1', 'XL Xtra Combo Flex XS 28 Hari', 'Data', 'XL', 2001000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex Xs","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-353b7aab', 'XL Data Bebas Puas 3 GB 12 Hari', 'Data', 'XL', 2010000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-08d07e86', 'XL XTRA HotRod Special 6 GB 10 Hari', 'Data', 'XL', 2011000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 6GB, 10hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ee2bbd92', 'XL Data Bebas Puas 4 GB 8 Hari', 'Data', 'XL', 2020000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-99311310', 'XL Combo Lite M', 'Data', 'XL', 2050000, true, '{"type":"Combo Lite","description":"Xtra Combo Lite M, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-04918dd0', 'XL Data Bebas Puas 9 GB 5 Hari', 'Data', 'XL', 2150000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ce613808', 'XL XTRA Hotrod Special XL 7 Hari', 'Data', 'XL', 2187500, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special XL, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b0cfc50a', 'XL Data 10 GB 30 Hari', 'Data', 'XL', 2192500, true, '{"type":"Umum","description":"XL Data 10 GB 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-06ada804', 'XL Data Bebas Puas 3.25 GB 13 Hari', 'Data', 'XL', 2192500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-cffd98ff', 'XL Combo Lite S', 'Data', 'XL', 2200000, true, '{"type":"Combo Lite","description":"deskripsi produk cek di link https://www.xl.co.id/id/bantuan/produk/xtra-combo-lite","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-25f37553', 'XL Data Flex Mini 6 GB 14 Hari', 'Data', 'XL', 2226000, true, '{"type":"Flex Mini","description":"6 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-837387fd', 'XL Data Grab Gacor 4.5 GB 30 Hari', 'Data', 'XL', 2236000, true, '{"type":"Grab Gacor","description":"Paket Grab Gacor 4.5GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b206669d', 'XL Data Flex Mini 10 GB 7 Hari', 'Data', 'XL', 2248500, true, '{"type":"Flex Mini","description":"10 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b7b763bc', 'XL Xtra Combo Mini 6 GB 7 Hari', 'Data', 'XL', 2250000, true, '{"type":"Xtra Combo Mini","description":"Xtra Combo Mini 6GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3832b3d2', 'XL Data Paket Harian L 7 Hari', 'Data', 'XL', 2285000, true, '{"type":"Harian","description":"Paket Harian L, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8298cd63', 'XL Data 8 GB 30 Hari', 'Data', 'XL', 2300000, true, '{"type":"Umum","description":"DRP DATA 8 GB, 2G3G4G, 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b88c31d5', 'XL XTRA Hotrod Special 6.5 GB 7 Hari', 'Data', 'XL', 2301000, true, '{"type":"Hotrod Special","description":"Xtra Hotrod Special 6.5GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-96d4856a', 'XL Data Bebas Puas 4.5 GB 9 Hari', 'Data', 'XL', 2315000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b6f148f0', 'XL Xtra Combo Mini Gift 6 GB 7 Hari', 'Data', 'XL', 2335200, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Mini Gift 6GB, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-26b1b804', 'XL XTRA Hotrod Special 6 GB 7 Hari', 'Data', 'XL', 2341000, true, '{"type":"Hotrod Special","description":"3 GB nasional + 3 GB Youtube (00:00 - 12:00), berlaku 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c60cab88', 'XL Data Bebas Puas 3.5 GB 14 Hari', 'Data', 'XL', 2350000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fc60cfe6', 'XL Data 9 GB 30 Hari', 'Data', 'XL', 2400000, true, '{"type":"Umum","description":"XL Data 9 GB 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6bf84723', 'XL Data Bebas Puas 3.75 GB 15 Hari', 'Data', 'XL', 2442500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e30167af', 'XL Data Bebas Puas 5 GB 10 Hari', 'Data', 'XL', 2540000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e9ce486c', 'XL Data Flex Mini 8 GB 14 Hari', 'Data', 'XL', 2588000, true, '{"type":"Flex Mini","description":"8 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-72f61a4a', 'XL XTRA Hotrod Special 2 GB 7 Hari - East', 'Data', 'XL', 2600000, true, '{"type":"East","description":"Xtra Hotrod Special 2GB, 7hr - East","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b15fa8a6', 'XL Data Bebas Puas 4 GB 16 Hari', 'Data', 'XL', 2690000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f44d7b4d', 'XL Data Bebas Puas 10.8 GB 6 Hari', 'Data', 'XL', 2720000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ebdcedbd', 'XL Data Flex Mini 20 GB 7 Hari', 'Data', 'XL', 2733500, true, '{"type":"Flex Mini","description":"20 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8e22bb0c', 'XL Data Kuota Apps & Games 5 GB 30 Hari', 'Data', 'XL', 2760500, true, '{"type":"Apps Games","description":"Quota Apps & Games 5GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a49227b7', 'XL Data Flex Mini 15 GB 7 Hari', 'Data', 'XL', 2762500, true, '{"type":"Flex Mini","description":"15 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b725545a', 'XL Xtra Combo Flex S 28 Hari', 'Data', 'XL', 2780000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex S","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b3f09e8c', 'XL Xtra Combo 2 GB + 4 GB / 30 Hari', 'Data', 'XL', 2785000, true, '{"type":"Xtra Combo","description":"2GB (2G/3G/4G) + Nelp Anynet 20 mins. Youtube 24 Jam 4GB. Youtube 01:00-06:00 Tanpa kuota Unlimited.\n","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-2ec04c21', 'XL Data FlexMax 6 GB 28 Hari', 'Data', 'XL', 2790000, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-63c3e73a', 'XL Xtra Combo Flex S+ 28 Hari', 'Data', 'XL', 2812500, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex S+","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-36a088ec', 'XL Data Bebas Puas 6rb/hr - 5 Hari', 'Data', 'XL', 2830400, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8c35b95f', 'XL Xtra Kuota Vidio 5 GB & Vidio Platinum F1 30 hari', 'Data', 'XL', 2839100, true, '{"type":"Xtra Kuota Vidio","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e15554ec', 'XL Data Games 6 GB 30 Hari', 'Data', 'XL', 2843200, true, '{"type":"Games","description":"DRP MAIN 3GB+GAMES 3GB 30D","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-80eadc35', 'XL Data Bebas Puas 5.5 GB 11 Hari', 'Data', 'XL', 2852500, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-df8ab7e9', 'XL Data Bebas Puas 4.25 GB 17 Hari', 'Data', 'XL', 2872500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fbc05c31', 'XL Data Paket Harian XL 7 Hari', 'Data', 'XL', 2897500, true, '{"type":"Harian","description":"Paket Harian XL, 7hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6061146c', 'XL Data Grab Gacor 6.5 GB 30 Hari', 'Data', 'XL', 2935000, true, '{"type":"Grab Gacor","description":"Paket Grab Gacor 6.5GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ed92bed7', 'XL Data Bebas Puas 12.6 GB 7 Hari', 'Data', 'XL', 2960000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4ed10293', 'XL Xtra Combo Special 8 GB 30 Hari', 'Data', 'XL', 3016500, true, '{"type":"Xtra Combo","description":"Xtra Combo Special 8GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f489507e', 'XL Data Bebas Puas 4.5 GB 18 Hari', 'Data', 'XL', 3022500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2d79fe5c', 'XL Data Bebas Puas 6 GB 12 Hari', 'Data', 'XL', 3090000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e592f48b', 'XL Data Bebas Puas 4.75 GB 19 Hari', 'Data', 'XL', 3142500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c72a62f5', 'XL Data Games 8 GB 30 Hari', 'Data', 'XL', 3160000, true, '{"type":"Games","description":"DRP MAIN+GAMES 8GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-aced449b', 'XL Data Flex S 28 Hari', 'Data', 'XL', 3171000, true, '{"type":"Xtra Combo Flex","description":"Flex S, 28hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f7fbd153', 'XL Data FlexMax 7 GB 28 Hari', 'Data', 'XL', 3183900, true, '{"type":"FlexMax","description":"7 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9c316bd2', 'XL Data Flex 7 GB 28 Hari', 'Data', 'XL', 3188800, true, '{"type":"Flex","description":"7 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f88eb22a', 'XL Data Bebas Puas 5 GB 20 Hari', 'Data', 'XL', 3262500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-31a38e19', 'XL Data FlexMax 10 GB 28 Hari', 'Data', 'XL', 3302500, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6a6524b3', 'XL Data Bebas Puas 6.5 GB 13 Hari', 'Data', 'XL', 3350000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f7405303', 'XL Data Bebas Puas 14.4 GB 8 Hari', 'Data', 'XL', 3420000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-116fef6e', 'XL Data Kuota Apps & Games 6 GB 30 Hari', 'Data', 'XL', 3450500, true, '{"type":"Apps Games","description":"Quota Apps & Games 6GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f7e15008', 'XL Xtra Combo Plus 5 GB 30 Hari', 'Data', 'XL', 3500000, true, '{"type":"Xtra Combo Plus","description":"Xtra Combo Plus 5GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-23bad4ec', 'XL Xtra Combo Plus 3 GB 30 Hari', 'Data', 'XL', 3500000, true, '{"type":"Xtra Combo Plus","description":"Xtra Combo Plus 3GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ebab8023', 'XL Data Bebas Puas 5.25 GB 21 Hari', 'Data', 'XL', 3500000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-78b36187', 'XL Data Flex Mini 40 GB 7 Hari', 'Data', 'XL', 3532500, true, '{"type":"Flex Mini","description":"40 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-20f02c31', 'XL Xtra Combo Flex M 28 Hari', 'Data', 'XL', 3550000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex M","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4eccf8d5', 'XL Data Flex Mini 15 GB 14 Hari', 'Data', 'XL', 3585300, true, '{"type":"Flex Mini","description":"15 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fb7da435', 'XL Data Bebas Puas 7 GB 14 Hari', 'Data', 'XL', 3610000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a44948b3', 'XL Data Bebas Puas 5.5 GB 22 Hari', 'Data', 'XL', 3670000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6c22c13e', 'XL Data Bebas Puas 7.5 GB 15 Hari', 'Data', 'XL', 3732500, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1f5c2f2d', 'XL Data Bebas Puas 16.2 GB 9 Hari', 'Data', 'XL', 3830000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-313ef359', 'XL Data Bebas Puas 5.75 GB 23 Hari', 'Data', 'XL', 3860000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-81bea787', 'XL Data Bebas Puas 6rb/hr - 7 Hari', 'Data', 'XL', 3962000, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-5fc52e07', 'XL Data Games 10 GB 30 Hari', 'Data', 'XL', 4002000, true, '{"type":"Games","description":"DRP MAIN+GAMES 10GB 30D XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1144d703', 'XL Data Bebas Puas 6 GB 24 Hari', 'Data', 'XL', 4030000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2c355085', 'XL Data Bebas Puas 6.25 GB 25 Hari', 'Data', 'XL', 4160000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-67cfde13', 'XL Xtra Combo Special 14 GB 30 Hari', 'Data', 'XL', 4161100, true, '{"type":"Xtra Combo","description":"Xtra Combo Special 14GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-9bf3d5f8', 'XL Data FlexMax 15 GB 28 Hari', 'Data', 'XL', 4185700, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ee2a0032', 'XL Data Bebas Puas 8 GB 16 Hari', 'Data', 'XL', 4210100, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3b8a8cd1', 'XL Data Bebas Puas 18 GB 10 Hari', 'Data', 'XL', 4230000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-3fac8a2d', 'XL Data Flex Mini 75 GB 7 Hari', 'Data', 'XL', 4285500, true, '{"type":"Flex Mini","description":"75 GB Nasional 7 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-06448e9d', 'XL Xtra Combo Flex M+ 28 Hari', 'Data', 'XL', 4350000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex M+","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a2efe6fe', 'XL Data Bebas Puas 6.5 GB 26 Hari', 'Data', 'XL', 4350000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-73c4c45b', 'XL Data Akrab S', 'Data', 'XL', 4402500, true, '{"type":"Paket Akrab","description":"Paket Akrab S, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0d7eadf3', 'XL Data Bebas Puas 8.5 GB 17 Hari', 'Data', 'XL', 4447500, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-51935863', 'XL Data Flex 13 GB 28 Hari', 'Data', 'XL', 4450000, true, '{"type":"Flex","description":"13 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d6c4c6f8', 'XL Data FlexMax 16 GB 28 Hari', 'Data', 'XL', 4450000, true, '{"type":"FlexMax","description":"16 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ce65ad85', 'XL Data Flex Mini 30 GB 14 Hari', 'Data', 'XL', 4479500, true, '{"type":"Flex Mini","description":"30 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


INSERT INTO demo_products (sku_digiflazz, name, category, provider, base_price_minor, is_active, metadata)
VALUES
  ('data-xl-ac2cebaf', 'XL Xtra Combo Weekend 5 GB + 5 GB / 30 Hari', 'Data', 'XL', 4500000, true, '{"type":"Xtra Combo Weekend","description":"5GB + 5GB (Youtube)+20Menit All 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a803a4c5', 'XL Data Bebas Puas 6.75 GB 27 Hari', 'Data', 'XL', 4530000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-2769ab9b', 'XL Data FlexMax 20 GB 28 Hari', 'Data', 'XL', 4584100, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ba546d30', 'XL Xtra Combo Flex L 28 Hari', 'Data', 'XL', 4590500, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex L","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a63e57b1', 'XL Data Bebas Puas 9 GB 18 Hari', 'Data', 'XL', 4650000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4cb7e427', 'XL Data Bebas Puas 7 GB 28 Hari', 'Data', 'XL', 4680000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-ce4e6afa', 'XL Data 30 GB 30 Hari', 'Data', 'XL', 4692500, true, '{"type":"Umum","description":"XL Data 30 GB / 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a8af239e', 'XL Data FlexMax 33 GB 14 Hari', 'Data', 'XL', 4705500, true, '{"type":"FlexMax","description":"33 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-be4a3e0b', 'XL Data Bebas Puas 19.8 GB 11 Hari', 'Data', 'XL', 4742500, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8efa4aae', 'XL Data Bebas Puas 7.25 GB 29 Hari', 'Data', 'XL', 4885000, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-97649565', 'XL Data Bebas Puas 7.5 GB 30 Hari', 'Data', 'XL', 4892500, true, '{"type":"Bebas Puas 2rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-dbfe69e4', 'XL Data Bebas Puas 9.5 GB 19 Hari', 'Data', 'XL', 4910000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-654f84d9', 'XL Data Grab Gacor 12 GB 30 Hari', 'Data', 'XL', 4912500, true, '{"type":"Grab Gacor","description":"Paket Grab Gacor 12GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-bbabeeed', 'XL Xtra Kuota Vidio 5 GB & Vidio Diamond Mobile 30 hari', 'Data', 'XL', 4977500, true, '{"type":"Xtra Kuota Vidio","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-fe7c5675', 'XL Data Bebas Puas 10 GB 20 Hari', 'Data', 'XL', 5150000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-79a92c45', 'XL Data Bebas Puas 21.6 GB 12 Hari', 'Data', 'XL', 5172500, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e77c570c', 'XL Xtra Combo Plus Gift 10 GB 30 Hari', 'Data', 'XL', 5295000, true, '{"type":"Xtra Combo Gift","description":"Xtra Combo Plus Gift 10GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e717dffb', 'XL Xtra Combo Gift 10 GB / 30 Hari', 'Data', 'XL', 5350000, true, '{"type":"Xtra Combo Gift","description":"10 GB Utama + 2 GB Aplikasi + 3 GB Lokal + 20 Menit Sesama, 30 Hari, jalur gift","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-1da638fe', 'XL Data Bebas Puas 10.5 GB 21 Hari', 'Data', 'XL', 5410000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-125b00b8', 'XL Data Flex 19 GB 28 Hari', 'Data', 'XL', 5420400, true, '{"type":"Flex","description":"19 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-65fb3526', 'XL Data FlexMax 23 GB 28 Hari', 'Data', 'XL', 5423200, true, '{"type":"FlexMax","description":"23 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7c49a6bf', 'XL Data FlexMax 25 GB 28 Hari', 'Data', 'XL', 5480500, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-0f6cf0c2', 'XL Data FlexMax 12 GB 28 Hari (East Kalsul)', 'Data', 'XL', 5480500, true, '{"type":"East Kalsul","description":"12 GB Utama + Lokal East Kalsul","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-34dc29ac', 'XL Data FlexMax 12 GB 28 Hari (Sumatera)', 'Data', 'XL', 5520000, true, '{"type":"Sumatera","description":"XL Data FlexMax 12 GB 28 Hari (Sumatera)","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-a9c01d6a', 'XL Data Bebas Puas 23.4 GB 13 Hari', 'Data', 'XL', 5530000, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-8df9cf04', 'XL Xtra Combo 5 GB + 10 GB 28 Hari', 'Data', 'XL', 5550000, true, '{"type":"Xtra Combo","description":"Xtra Combo 5+10 Double Youtube","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b2996f51', 'XL Data Bebas Puas 11 GB 22 Hari', 'Data', 'XL', 5600000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-953bbcbe', 'XL Data Bebas Puas 6rb/hr - 10 Hari', 'Data', 'XL', 5602500, true, '{"type":"Bebas Puas 6rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-f01acc9b', 'XL Xtra Combo Plus 10 GB 30 Hari', 'Data', 'XL', 5613100, true, '{"type":"Xtra Combo Plus","description":"Xtra Combo Plus 10GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4691e5c1', 'XL Data Akrab Kuota Bersama 10 GB / 30 Hari', 'Data', 'XL', 5615000, true, '{"type":"Paket Akrab","description":"cek deskripsi pada link https://www.xl.co.id/id/mobile/prabayar/paket-dan-tarif/internet/paket-akrab","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-e7c2b50f', 'XL Xtra Combo VIP Gift 10 GB 30 Hari', 'Data', 'XL', 5700000, true, '{"type":"Xtra Combo VIP Gift","description":"Xtra Combo VIP Plus Gift 10GB, 30hr","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d72c37ae', 'XL Data Bebas Puas 11.5 GB 23 Hari', 'Data', 'XL', 5930000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-70a497f2', 'XL Xtra Kuota Vidio 5 GB & Vidio Diamond Big Screen 30 hari', 'Data', 'XL', 5977000, true, '{"type":"Xtra Kuota Vidio","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4de42a03', 'XL Xtra Combo Weekend 10 GB + 10 GB / 30 Hari', 'Data', 'XL', 6000000, true, '{"type":"Xtra Combo Weekend","description":"10GB + 10GB (Youtube)+30Menit All 30 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-6e24d528', 'XL Data Bebas Puas 25.2 GB 14 Hari', 'Data', 'XL', 6032500, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-005868dc', 'XL XTRA ON 20 GB 365 Hari', 'Data', 'XL', 6052500, true, '{"type":"Xtra On","description":"XL XTRA ON 20 GB 365 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-20fe2558', 'XL Data FlexMax 31 GB 28 Hari', 'Data', 'XL', 6092500, true, '{"type":"FlexMax","description":"31 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-27284879', 'XL Data Bebas Puas 12 GB 24 Hari', 'Data', 'XL', 6100000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-bcd4ef0d', 'XL Data Flex 26 GB 28 Hari', 'Data', 'XL', 6132500, true, '{"type":"Flex","description":"26 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-55f1ad1b', 'XL Data Bebas Puas 27 GB 15 Hari', 'Data', 'XL', 6142500, true, '{"type":"Bebas Puas 5rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-7fa67b6b', 'XL Xtra Combo Flex L+ 28 Hari', 'Data', 'XL', 6152500, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex L+","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-c4a6b7f2', 'XL Xtra Combo Flex XL 28 Hari', 'Data', 'XL', 6190000, true, '{"type":"Xtra Combo Flex","description":"Xtra Combo Flex XL","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-048ebf63', 'XL Data FlexMax 32 GB 28 Hari', 'Data', 'XL', 6282500, true, '{"type":"FlexMax","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-b6cc40ef', 'XL Xtra Combo VIP Plus 10 GB / 30 Hari', 'Data', 'XL', 6285000, true, '{"type":"Xtra Combo VIP Plus","description":"https://www.xl.co.id/id/mobile/prabayar/paket-dan-tarif/internet/xtra-combo-plus","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4fddf372', 'XL Xtra Combo VIP 5 GB + 10 GB 30 Hari', 'Data', 'XL', 6335400, true, '{"type":"Xtra Combo","description":"Xtra Combo 5+10 VIP Double Youtube","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-4ebc9778', 'XL Combo Lite L', 'Data', 'XL', 6400000, true, '{"type":"Combo Lite","description":"deskripsi produk cek di link https://www.xl.co.id/id/bantuan/produk/xtra-combo-lite","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-16a9fbe4', 'XL Data Bebas Puas 12.5 GB 25 Hari', 'Data', 'XL', 6440000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-09321e7f', 'XL Data Bebas Puas 13 GB 26 Hari', 'Data', 'XL', 6620000, true, '{"type":"Bebas Puas 3rb","description":"-","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-22d0fb3b', 'XL Data Flex Mini 75 GB 14 Hari', 'Data', 'XL', 6710500, true, '{"type":"Flex Mini","description":"75 GB Nasional 14 Hari","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}'),
  ('data-xl-d5931b3e', 'XL Data FlexMax 75 GB 14 Hari', 'Data', 'XL', 6757900, true, '{"type":"FlexMax","description":"75 GB Nasional","image_url":"https://cdn.mobilepulsa.net/img/logo/pulsa/small/xl.png"}')
  base_price_minor = EXCLUDED.base_price_minor,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();


